var Cession;
(function(){var a=-1,b="",d=0,c=0,g=0,k="127.0.0.1",f=8E3,l=!1,m=!1,h="",s=!1,n=!1,p=0,e="",u=[],q={},z=null;Cession=function(){};Cession.prototype._64=function(){return a};Cession.prototype._23=function(c){a=c};Cession.prototype._67=function(){return d};Cession.prototype._26=function(a){d=a};Cession.prototype._66=function(){return g};Cession.prototype._25=function(a){g=a};Cession.prototype._59=function(){return b};Cession.prototype._20=function(a){b=
a};Cession.prototype._62=function(){return c};Cession.prototype._22=function(a){c=a};Cession.prototype._54=function(){return k};Cession.prototype._16=function(a){k=a};Cession.prototype._53=function(){return f};Cession.prototype._15=function(a){f=a};Cession.prototype._65=function(){return l};Cession.prototype._24=function(a){l=a};Cession.prototype._72=function(){return m};Cession.prototype._28=function(a){m=a};Cession.prototype._52=
function(){return h};Cession.prototype._14=function(a){h=a};Cession.prototype._55=function(){return s};Cession.prototype._17=function(a){s=a};Cession.prototype._61=function(){return p};Cession.prototype._21=function(a){p=a};Cession.prototype._49=function(){return e};Cession.prototype._12=function(a){e=a};Cession.prototype._48=function(){return n};Cession.prototype._11=function(a){n=a};Cession.prototype._74=function(){return u};Cession.prototype._29=
function(a){u=a};Cession.prototype._91=function(a){u.push(a)};Cession.prototype._87=function(){u=[];u.push([0,"IdUser_",a])};Cession.prototype._79=function(a){for(var c=u.length-1,b=!0;0<=c&&b;)u[c][0]>=a?(u.pop(),c--):b=!1};Cession.prototype._57=function(){return q};Cession.prototype._19=function(a){q=a};Cession.prototype._56=function(){return z};Cession.prototype._18=function(a){z=a};Cession.prototype._68=function(){return"../imgs/"};Cession.prototype._63=
function(){return"../codebase/imgs/"}})();var _39=new Cession,_43;
window.onload=function(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()},!1);window.applicationCache.addEventListener("obsolete",function(a){window.applicationCache.update()},!1);dhtmlx.image_path="codebase/imgs/";_43=new dhtmlXLayoutObject({parent:document.body,pattern:"3T",skin:"dhx_skyblue"});_43.cells("a").setText("Web@Report V1.0");_43.cells("b").setText("Menu");var a=_43.cells("c"),
b=_43.cells("b"),d=_43.cells("a");_43.cells("b").setWidth(150);_43.cells("a").setHeight(100);_43.setAutoSize("a","b;c");b.collapse();b.hideArrow();d.attachHTMLString("<style type='text/css'>#texte{text-align:center;font-weight:bold;color:#709AFC;font-size:40px;}</style><div id='texte'> Web@Report Vers 1.0 </div>");var c=_43.cells("b").attachTree();c.setSkin("dhx_skyblue");c.setImagePath("../codebase/imgs/dhxtree_skyblue/");c.enableHighlighting(!0);c.attachEvent("onSelect",
function(c){if(c&&c.startsWith("M")&&null!=a&&0<_39._64()){for(;0<_39._62();)a.unloadView("Page"+_39._62()),_39._22(_39._62()-1);_39._87();a.showView("def");var b=c.substring(1,2);c=parseInt(c.substring(2));0<c?"A"==b||"B"==b?_8(a,b,c,1):"C"==b||"D"==b?_9(a,b,c,1):"E"==b||"F"==b?_10(a,b,c,1):"G"==b?_40(c,LibIdent,rId):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."}):
dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."})}});a.hideHeader();_39._19(a);_7(a,c,d,b)};window.onunload=function(){if(null!=_39._57()){var a=_39._57().getAttachedToolbar();a&&(_39._57().detachToolbar(),a.unload())}};function _30(a,b,d){a=b.split(String.fromCharCode(199));b=null;for(b=0;b<a.length;b++){var c=a[b].split(String.fromCharCode(198));0==c[1]&&""!=c[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:c[4]});"LOGIN"==c[2]&&"PROCEDURE"==c[3]&&1<=c[5].length?(c=_6(c[5]),_39._23(_51(c,"IdUser_")),_39._20(_51(c,"LibUser_")),_39._26(_51(c,"IdEcran_")),_39._25(_51(c,"IdPub_"))):"MENU"==c[2]&&"SELECT"==c[3]&&10<=c[5].length&&
(c=_83(c[5]),d[0].deleteChildItems(0),d[0].loadCSVString(c),d[0].openAllItems(0))}a=null;d[1]&&(d[1].hide(),d[1].unload(),d[1]=null);for(;0<_39._62();)d[2].unloadView("Page"+_39._62()),_39._22(_39._62()-1);_39._87();d[2].showView("def");d[0].selectItem("G1");d[4].isCollapsed()&&(d[4].expand(),d[4].showArrow());_46(_39._56())&&_37();_38(d[3]);a=setInterval(function(){_38(d[3])},3E5);_39._18(a)}
function _7(a,b,d,c){var g={login:"Votre login personnel",pwd:"Votre Mot de Passe Confidentiel."},k=Math.round((a.getWidth()-350)/2),f=Math.round((a.getHeight()-300)/2),k=[{type:"settings",position:"label-top",labelWidth:"150",inputWidth:"280"},{type:"fieldset",label:"Bienvenue",width:"auto",offsetLeft:k,offsetTop:f,list:[{type:"block",list:[{type:"label",name:"Titre",label:"<img src='../imgs/about.gif' />   NafysWeb"}]},{type:"input",name:"login",label:"Login",value:"",tooltip:"Login",
required:!0},{type:"password",name:"pwd",label:"Mot de Passe",value:"",required:!0},{type:"button",name:"proceed",value:"Valider",width:"120",offsetLeft:"50"}]}];_39._22(_39._62()+1);a.showView("Page"+_39._62());var l=a.attachForm(k),m=new dhtmlXPopup({form:l,id:["login","pwd"]});l.attachEvent("onFocus",function(a){m.attachHTML("<div style='margin: 5px 10px;'>"+g[a]+"</div>");m.show(a)});l.attachEvent("onBlur",function(a){m&&m.hide()});l.attachEvent("onButtonClick",
function(f){if("proceed"==f){f=l.getItemValue("login");var g=l.getItemValue("pwd");f=_33(_39._54(),f,g,_39._53(),0);_78("XMLZ",f,_30,null,[b,m,a,d,c],!1)}})};function _10(a,b,d,c){function g(){_39._79(c);f.forEachItem(function(a){var b="",d=f.getItemType(a);"calendar"==d?(d=f.getItemValue(a),_46(d)&&(b=d.toString("dd/MM/yyyy")),"30/12/1899"==b&&(b=""),_39._91([c,a,b])):"input"==d?(b=f.getItemValue(a),_39._91([c,a,b])):"checkbox"==d&&(b=f.getItemValue(a),_39._91([c,a,b]))})}var k,f,l=0,m=0,h="",s,n;_39._79(c);_35(a,!0);var p=_92(null,1,"GRIDEF","WRDIAG","WRPSGRIDEF"),
p=_90(p,1,0,"IdEcran_",d),p=_89(p,1,0,_39._74()),e=_1(p),p=null;_78("XMLZ",e,function(d,e,p){if(_46(p)&&0<_39._64()){d=e.split(String.fromCharCode(199));e=null;for(e=0;e<d.length;e++)if(p=d[e].split(String.fromCharCode(198)),0==p[1]&&""!=p[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:p[4]}),"GRIDEF"==p[2]&&"WRDIAG"==p[3]&&1<=p[5].length){var t=_6(p[5]);p=_51(t,"fForm_");l=parseInt(_51(t,"fWinHeight_"));m=parseInt(_51(t,
"fWinWidth_"));h=_51(t,"fDblClick_");t=null;0==m&&(m=2*a.getWidth()/3);0==l&&(l=2*a.getHeight()/3);if("E"==b)var t=Math.round((a.getWidth()-m)/2),x=Math.round((a.getHeight()-l)/2);else q.setDimension(m+100,l+100),q.centerOnScreen(),x=t=50;p=p.replace("NtsOffsetLeft",t);p=p.replace("NtsOffsetTop",x);var r;eval("r="+p);f.loadStruct(r);p=r=null;f.forEachItem(function(a){var b="",b=null,b=f.getItemType(a),d=f.getUserData(a,"Key"),e=f.getUserData(a,"Sql");_46(d)&&_46(e)&&s.id.push(a);
if("calendar"==b)f.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=f.getInput(a),b.style.textAlign="center",b=f.getItemValue(a),_39._91([c,a,b]);else if("input"==b){b=f.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";b=f.getItemValue(a);_39._91([c,a,b])}else"checkbox"==b&&(b=f.getItemValue(a),_39._91([c,a,b]),"0"==b||"N"==b?f.uncheckItem(a):f.checkItem(a))});n=new dhtmlXPopup(s);""!=h&&f.attachEvent("onButtonClick",
function(d,f){_46(k)&&(k.unload(),k=null);if("BtOui"==d){g();var e=h.substring(0,1),l=parseInt(h.substring(1));0<l&&("F"==b&&_46(q)&&(_46(n)&&(n.unload(),s=n=null),q.close()),"A"==e||"B"==e?_8(a,e,l,c+1):"C"==e||"D"==e?_9(a,e,l,c+1):"E"==e||"F"==e?_10(a,e,l,c+1):"G"==e&&_40(l,"",""))}else"BtNon"==d&&("E"==b?(_46(n)&&(n.unload(),s=n=null),a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),e=_39._62(),
0==e?(a.showView("def"),_39._87()):(a.showView("Page"+e),_39._79(c))):"F"==b&&_46(q)&&(_46(n)&&(n.unload(),s=n=null),q.close(),_39._79(c)))})}else if(!("GRIDEF"==p[2]&&"DATA"==p[3]&&10<=p[5].length)&&"GRIDEF"==p[2]&&"TOOLS"==p[3]&&10<=p[5].length)for(p=p[5].split(String.fromCharCode(197)),e=0;e<p.length;e++)t=p[e].split(String.fromCharCode(196)),"A"==t[2]?u.addButton("A"+e,e,t[1],t[5],t[6]):"B"==t[2]?u.addButton("B"+e,e,t[1],t[5],t[6]):"C"==t[2]?
u.addText("C"+e,e,t[1]):"D"==t[2]?u.addSeparator("D"+e,e):u.addButton("E"+t[4]+t[3],e,t[1],t[5],t[6]);d=null;_35(a,!1)}},null,[a],!0);a.setText("Liste");if("E"==b){_39._22(_39._62()+1);a.showView("Page"+_39._62());var u=a.attachToolbar();f=a.attachForm()}else{var p=_39._62(),q=_43.dhxWins.createWindow("myWind"+p,100,100,400,400);q.centerOnScreen();q.setModal(!0);q.denyPark();q.setText("Web@Report");f=q.attachForm();u=q.attachToolbar()}s=
{form:f,id:[]};u.setIconsPath(_39._68());u.attachEvent("onClick",function(f){_46(k)&&(k.unload(),k=null);var e=f.substring(0,1);"A"==e?(g(),k=_42(a,d,"","")):"B"==e&&"E"==b?(_46(n)&&(n.unload(),s=n=null),a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),f=_39._62(),0==f?(a.showView("def"),_39._87()):(a.showView("Page"+f),_39._79(c))):"B"==e&&"F"==b?_46(q)&&(_46(n)&&(n.unload(),
s=n=null),q.close(),_39._79(c)):"E"==e&&(e=f.substring(1,2),f=parseInt(f.substring(2)),0<f&&(g(),"F"==b&&_46(q)&&(_46(n)&&(n.unload(),s=n=null),q.close()),"A"==e||"B"==e?_8(a,e,f,c+1):"C"==e||"D"==e?_9(a,e,f,c+1):"E"==e||"F"==e?_10(a,e,f,c+1):"G"==e&&_40(f,"","")))});f.enableLiveValidation(!0);f.setFontSize("14px");_39._11(!1);f.attachEvent("onKeyUp",function(b,c,d){if(9!=c.keyCode&&0<=s.id.indexOf(d)){b=f.getUserData(d,"Key");var e=
f.getUserData(d,"Sql");c=String.fromCharCode(c.keyCode);g();_31(f,a,n,b,d,b,d,e,c,350)}})};function _9(a,b,d,c){var g,k,f=0,l=0;_39._79(c);_35(a,!0);var m=_92(null,1,"GRIDCD","WRFORM","WRPSGRIDCD"),m=_90(m,1,0,"IdEcran_",d),m=_89(m,1,0,_39._74()),h=_1(m),m=null;_78("XMLZ",h,function(d,e,g){if(_46(g)&&0<_39._64()){d=e.split(String.fromCharCode(199));e=null;for(e=0;e<d.length;e++)if(g=d[e].split(String.fromCharCode(198)),0==g[1]&&""!=g[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:g[4]}),
"GRIDCD"==g[2]&&"WRFORM"==g[3]&&1<=g[5].length){var h=_6(g[5]);g=_51(h,"fForm_");f=parseInt(_51(h,"fWinHeight_"));l=parseInt(_51(h,"fWinWidth_"));h=null;0==l&&(l=2*a.getWidth()/3);0==f&&(f=2*a.getHeight()/3);if("C"==b)var m=Math.round((a.getWidth()-l)/2),y=Math.round((a.getHeight()-f)/2);else n.setDimension(l+100,f+100),n.centerOnScreen(),y=m=50;g=g.replace("NtsOffsetLeft",m);g=g.replace("NtsOffsetTop",y);var w;eval("w="+g);k.loadStruct(w);g=w=null}else if("GRIDCD"==g[2]&&"DATA"==
g[3]&&10<=g[5].length)h=_6(g[5]),k.forEachItem(function(a){var b="",b=null,b=k.getItemType(a);if("calendar"==b)k.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=k.getInput(a),b.style.textAlign="center",(b=_51(h,a))&&k.setItemValue(a,b),_39._91([c,a,b]);else if("input"==b){b=k.getInput(a);if("0"==b.value||"0.00"==b.value)b.style.textAlign="right";(b=_51(h,a))&&k.setItemValue(a,b);_39._91([c,a,b])}else"checkbox"==b&&(b=_51(h,a),"0"==b||"N"==b?k.uncheckItem(a):
k.checkItem(a),_39._91([c,a,b]))}),h=null;else if("GRIDCD"==g[2]&&"TOOLS"==g[3]&&10<=g[5].length)for(g=g[5].split(String.fromCharCode(197)),e=0;e<g.length;e++)m=g[e].split(String.fromCharCode(196)),"A"==m[2]?s.addButton("A"+e,e,m[1],m[5],m[6]):"B"==m[2]?s.addButton("B"+e,e,m[1],m[5],m[6]):"C"==m[2]?s.addText("C"+e,e,m[1]):"D"==m[2]?s.addSeparator("D"+e,e):s.addButton("E"+m[4]+m[3],e,m[1],m[5],m[6]);d=null;_35(a,!1)}},null,[a],!0);a.setText("Liste");if("C"==b){_39._22(_39._62()+
1);a.showView("Page"+_39._62());var s=a.attachToolbar();k=a.attachForm()}else{var m=_39._62(),n=_43.dhxWins.createWindow("myWind"+m,100,100,400,400);n.centerOnScreen();n.setModal(!0);n.denyPark();n.setText("Web@Report");k=n.attachForm();s=n.attachToolbar()}s.setIconsPath(_39._68());s.attachEvent("onClick",function(f){_46(g)&&(g.unload(),g=null);var e=f.substring(0,1);"A"==e?g=_42(a,d,"",""):"B"==e&&"C"==b?(a.unloadView("Page"+_39._62()),
_39._22(_39._62()-1),f=_39._62(),0==f?(a.showView("def"),_39._87()):(a.showView("Page"+f),_39._79(c))):"B"==e&&"D"==b?_46(n)&&(n.close(),_39._79(c)):"E"==e&&(e=f.substring(1,2),f=parseInt(f.substring(2)),0<f&&("D"==b&&_46(n)&&n.close(),"A"==e||"B"==e?_8(a,e,f,c+1):"C"==e||"D"==e?_9(a,e,f,c+1):"E"==e||"F"==e?_10(a,e,f,c+1):"G"==e&&_40(f,"","")))});k.enableLiveValidation(!0);k.setFontSize("14px");
_39._11(!1)};function _8(a,b,d,c){function g(b,c,d){h.startFastOperations();h.clearAll();_46(c)&&h.loadCSVString(c);h.stopFastOperations();_35(a,!1)}var k,f,l,m,h,s=null,n="",p="",e=0,u=0;_35(a,!0);var q=_92(null,1,"GRIDAB","WRGRID","WRPSGRIDAB"),q=_90(q,1,0,"IdEcran_",d),q=_89(q,1,0,_39._74()),z=_1(q),q=null;_78("XMLZ",z,function(t,x,r){if(_46(r)&&0<_39._64()){t=x.split(String.fromCharCode(199));x=null;for(x=0;x<
t.length;x++)if(r=t[x].split(String.fromCharCode(198)),0==r[1]&&""!=r[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:r[4]}),"GRIDAB"==r[2]&&"WRGRID"==r[3]&&1<=r[5].length){r=_6(r[5]);var q=_51(r,"gHeader_"),v=_51(r,"gFilter_"),z=_51(r,"gTypes_"),C=_51(r,"gColAlig_"),D=_51(r,"gColSort_"),A=_51(r,"gColType_"),E=_51(r,"gColWidth_");s=_51(r,"gCmdeSQL_");var F=_51(r,"gColVars_");n=_51(r,"gLibIdent_");p=_51(r,"gDblClick_");e=parseInt(_51(r,"gWinHeight"));
u=parseInt(_51(r,"gWinWidth"));var B="O"==_51(r,"gRecSrv_");f=A.split(",");l=B?F.split(","):null;A=r=null;h.startFastOperations();h.setHeader(q.split(","));""!=v&&h.attachHeader(v);h.setColTypes(z);h.setColAlign(C);h.setColSorting(D);h.enableValidation(!0,!1);h.setInitWidths(E);h.init();h.csv.row=String.fromCharCode(197);h.csv.cell=String.fromCharCode(196);h.enableCSVAutoID(!1);h.clearAll();h.stopFastOperations()}else if("GRIDAB"==r[2]&&"DATA"==r[3]&&10<=r[5].length)h.startFastOperations(),
h.loadCSVString(r[5]),h.stopFastOperations();else if("GRIDAB"==r[2]&&"TOOLS"==r[3]&&10<=r[5].length)for(r=r[5].split(String.fromCharCode(197)),q=0;q<r.length;q++)v=r[q].split(String.fromCharCode(196)),"A"==v[2]?y.addButton("A"+q,q,v[1],v[5],v[6]):"B"==v[2]?y.addButton("B"+q,q,v[1],v[5],v[6]):"C"==v[2]?y.addText("C"+q,q,v[1]):"D"==v[2]?y.addSeparator("D"+q,q):y.addButton("E"+v[4]+v[3],q,v[1],v[5],v[6]);t=null;for(x=0;x<f.length;x++)t=parseInt(f[x].substring(1)),2==t?h.setNumberFormat("0,000.00",x,
","," "):3==t&&h.setNumberFormat("0,000.00%",x,","," ");"B"==b&&_46(w)&&(0==u&&(u=2*a.getWidth()/3),0==e&&(e=2*a.getHeight()/3),w.setDimension(u,e),w.centerOnScreen());""!=p&&h.attachEvent("onRowDblClicked",function(d,f){_46(m)&&(m.unload(),m=null);if(null!=d){_39._79(c);_39._91([c,n,d]);for(var e=0;e<l.length;e++){var g=l[e],k=h.cells(d,e).getValue();_39._91([c,g,k])}}e=p.substring(0,1);g=parseInt(p.substring(1));0<g&&("B"==b&&_46(w)&&w.close(),
"A"==e||"B"==e?_8(a,e,g,c+1):"C"==e||"D"==e?_9(a,e,g,c+1):"E"==e||"F"==e?_10(a,e,g,c+1):"G"==e&&_40(g,n,d))});B&&(h.attachEvent("onFilterEnd",function(b){_46(m)&&(m.unload(),m=null);if(25>h.getRowsNum()){_35(a,!0);_39._79(c);for(var e=_92(null,1,"SQL","SELECT",s),e=_90(e,1,0,"IdEcran_",d),p=!0,n=0;n<b.length;n++){var r=b[n][1],t=parseInt(f[r].substring(1));if(4==t||5==t)p=p&&(""==k[n]||_45(k[n]));e=_90(e,1,0,l[r],k[n])}p&&(e=
_89(e,1,0,_39._74()),b=_1(e),_78("XMLA",b,g,null,[a],!1))}}),h.attachEvent("onFilterStart",function(a,b){k=b;for(var c=!0,d=0;d<a.length;d++){var e=parseInt(f[a[d]].substring(1));if(4==e||5==e)c=c&&(""==k[d]||_45(k[d]))}return c}));_35(a,!1)}},null,[a],!0);a.setText("Liste");if("A"==b){_39._22(_39._62()+1);a.showView("Page"+_39._62());var y=a.attachToolbar();h=a.attachGrid()}else{var q=_39._62(),w=_43.dhxWins.createWindow("myWind"+
q,100,100,2*a.getWidth()/3,2*a.getHeight()/3);w.centerOnScreen();w.setModal(!0);w.denyPark();w.setText("Web@Report");h=w.attachGrid();y=w.attachToolbar()}y.setIconsPath(_39._68());y.attachEvent("onClick",function(f){_46(m)&&(m.unload(),m=null);var e=f.substring(0,1);if("A"==e){if(_39._79(c),f=h.getSelectedRowId(),null!=f){_39._91([c,n,f]);for(var g=0;g<l.length;g++){var k=l[g],p=h.cells(f,g).getValue();_39._91([c,k,p])}m=_42(a,d,n,
f)}}else if("B"==e&&"A"==b)a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),e=_39._62(),0==e?(a.showView("def"),_39._87()):(a.showView("Page"+e),_39._79(c));else if("B"==e&&"B"==b)_46(w)&&(w.close(),_39._79(c));else if("E"==e){var e=f.substring(1,2),s=parseInt(f.substring(2));_39._79(c);f=h.getSelectedRowId();if(null!=f)for(_39._91([c,n,f]),g=0;g<l.length;g++)k=l[g],p=h.cells(f,
g).getValue(),_39._91([c,k,p]);0<s&&("B"==b&&_46(w)&&w.close(),"A"==e||"B"==e?_8(a,e,s,c+1):"C"==e||"D"==e?_9(a,e,s,c+1):"E"==e||"F"==e?_10(a,e,s,c+1):"G"==e&&_40(s,n,rId))}});h.startFastOperations();h.setIconsPath(_39._68());h.setImagePath(_39._63());h.enableValidation(!0,!1);h.enableDistributedParsing(!0,10,300);h.setDateFormat("%d/m/Y");h.i18n.decimal_separator=".";h.i18n.group_separator=" ";h.enableCSVAutoID(!1);h.stopFastOperations();
_39._11(!1);h.attachEvent("onRowSelect",function(a,b){_46(m)&&(m.unload(),m=null)})};function _38(a){function b(a,b,c){if(_46(c)&&0<_39._64()){var d=a=_39._66();b=b.split(String.fromCharCode(199));for(var m=0;m<b.length;m++){var h=b[m].split(String.fromCharCode(198));0==h[1]&&""!=h[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:h[4]});"PUBIDT"==h[2]&&"PROCEDURE"==h[3]&&1<=h[5].length?(d=_6(h[5]),d=_51(d,"IdPub_"),d=parseInt(d),0<d&&_39._25(d)):"PUBDET"==h[2]&&"BLOB"==h[3]&&10<=h[5].length&&a!=d&&c[0].attachHTMLString(h[5])}}else _37()}
if(0>=_39._64()||!_46(a))_37();else{var d=_92(null,1,"PUBIDT","PROCEDURE","WRPsPub"),d=_90(d,1,0,"IdUser_",_39._64()),d=_90(d,1,0,"IdPub_",_39._66()),d=_92(d,2,"PUBDET","BLOB","Select * From WRfnPub(:IdPub_)"),d=_90(d,2,1,"IdPub_",0),c=_1(d),d=null;_78("XMLZ",c,b,null,[a],!1)}}function _37(){var a=_39._56();_46(a)&&clearInterval(_39._56());_39._18(null)}var DEBUG=!1;
if(!DEBUG){window.console||(window.console={});for(var methods="log debug warn info dir dirxml trace profile".split(" "),i=0;i<methods.length;i++)console[methods[i]]=function(){}}function _2(a,b,d,c,g,k){a()?window.setTimeout(_2,k,a,b,d,c,g,k):b(d,c,g)}function _36(a){(window.dhx4.isIPad||window.dhx4.isChrome||window.dhx4.isOpera||window.dhx4.isKHTML||window.dhx4.isFF)&&a.enableEditEvents(!0,!1,!1)}
function _75(a){return 1==a?"doc":2==a?"xls":3==a?"rtf":4==a?"xls":5==a?"pdf":6==a||7==a?"jpg":8==a?"zip":9==a?"rar":"pdf"}function _76(a){return"doc"==a?1:"xls"==a?2:"rtf"==a?3:"pdf"==a?5:"jpg"==a?6:"zip"==a?8:"rar"==a?9:"txt"==a?3:5}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});String.prototype.formatedfloat||(String.prototype.formatedfloat=function(){return parseFloat(this.replace(",",".").replace(" ",""))});
"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return this.slice(0,a.length)==a});"function"!=typeof Number.prototype.toMoney&&(Number.prototype.toMoney=function(a,b,d){var c=this;a=isNaN(a)?2:Math.abs(a);b=b||".";d="undefined"===typeof d?" ":d;var g=0>c?"-":"",k=parseInt(c=Math.abs(c).toFixed(a))+"",f=3<(f=k.length)?f%3:0;return g+(f?k.substr(0,f)+d:"")+k.substr(f).replace(/(\d{3})(?=\d)/g,"$1"+d)+(a?b+Math.abs(c-k).toFixed(a).slice(2):"")});
function _46(a){return"undefined"!=typeof a&&null!=a&&""!=a}function _70(a){return a.substr((~-a.lastIndexOf(".")>>>0)+2)}function _82(a,b){var d=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()),c=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate());return Math.floor((c-d)/864E5)}
function _84(a){var b=String.fromCharCode(197),d=String.fromCharCode(196);a=a.split(b);for(var b=[],c=[],g=-1,k=-1,f=[],l={},m=0;m<a.length;m++){var h=a[m].split(d),l={},k=parseInt(h[3]);g!=k&&(-1!=g&&(l.id=f[0]+"_"+f[3],l.text=f[4],l.item=c,b.push(l),l={},c=[]),g=k,f=h);l.id=h[0];l.text=h[2];c.push(l)}l={};l.id=f[0]+"_"+f[3];l.text=f[4];l.item=c;b.push(l);return"{id:0,  item:"+JSON.stringify(b)+"}"}
function _83(a){var b=String.fromCharCode(197),d=String.fromCharCode(196);a=a.split(b);for(var c=b=-1,g="",k="",f=0;f<a.length;f++){var l=a[f].split(d),c=parseInt(l[4]);b!=c&&(b=c,g="G"+(f+1),k=k+"\n"+g+",0,"+l[5]);k=k+"\nM"+l[1]+l[0]+","+g+","+l[3]}return k}
function _85(a){var b=String.fromCharCode(197),d=String.fromCharCode(196);a=a.split(b);var b=[],c=a[0].split(d);c[0]="value";c[1]="text";for(var g=0;g<a.length;g++){var k={},f=a[g].split(d);k[c[0]]=f[0];k[c[1]]=f[1];b.push(k)}return"{options:"+JSON.stringify(b)+"}"}
var _58=function(){var a;if("undefined"!=typeof window.ActiveXObject)for(var b="Msxml2.DOMDocument.6.0 Msxml2.DOMDocument.5.0 Msxml2.DOMDocument.4.0 Msxml2.DOMDocument.3.0 MSXML2.DOMDocument MSXML.DOMDocument Microsoft.XMLDOM".split(" "),d=0;d<b.length;d++)try{a=new ActiveXObject(b[d]);_58=function(){return new ActiveXObject(b[d])};break}catch(c){}return a};
function _6(a){var b=null;if(window.DOMParser&&!window.ActiveXObject){var d=new DOMParser;try{b=d.parseFromString(a,"text/xml")}catch(c){try{b=_58(),b.async=!1,b.loadXML(a)}catch(g){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}}}else try{b=_58(),b.async=!1,b.loadXML(a)}catch(k){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}return b}
function _1(a){return window.ActiveXObject?a.xml:(new XMLSerializer).serializeToString(a)}function _35(a,b){}
function _92(a,b,d,c,g){_46(a)||(a=_6("<?xml version='1.0' encoding='UTF-16'?><Actions></Actions>"));var k=a.getElementsByTagName("Actions"),f=a.createElement("Action"),l=a.createElement("Type"),m=a.createElement("SQL");c=a.createTextNode(c);g=a.createTextNode(g);m.appendChild(g);l.appendChild(c);f.setAttribute("ID",b);f.setAttribute("Name",d);f.appendChild(l);f.appendChild(m);k[0].appendChild(f);return a}
function _89(a,b,d,c){for(var g=c.length-1,k="",f=0,l=0;l<=g;l++)f=k.search(c[g-l][1]),0>f&&(k=k+";"+c[g-l][1],a=_90(a,b,d,c[g-l][1],c[g-l][2]));return a}function _90(a,b,d,c,g){var k=a.getElementsByTagName("Action"),f=a.createElement("Param"),l=a.createElement("Value");null==g&&(g="");g=a.createTextNode(g);l.appendChild(g);f.setAttribute("Source",d);f.setAttribute("Name",c);f.appendChild(l);for(d=0;d<k.length;d++)k[d].getAttribute("ID")==b&&k[d].appendChild(f);return a}
function _60(a){var b=a.match(/[^\x00-\xff]/g);return a.length+(b?b.length:0)}function _86(a,b){var d=new XMLHttpRequest;"withCredentials"in d?d.open(a,b,!0):"undefined"!=typeof XDomainRequest?(d=new XDomainRequest,d.open(a,b)):d=null;return d}
var _47=function(){var a;try{a=new XMLHttpRequest,_47=function(){return new XMLHttpRequest}}catch(b){for(var d=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0,g=d.length;c<g;++c)try{a=new ActiveXObject(d[c]);_47=function(){return new ActiveXObject(d[c])};break}catch(k){}}return a};
function _88(a){var b=a.byteLength;a=new Uint8Array(a);if(8192>b)return String.fromCharCode.apply(null,a);for(var d=0,c="";d<b;)c+=String.fromCharCode.apply(null,a.subarray(d,d+8192)),d+=8192;return c}var _32=function(a,b){try{return a.readAsBinaryString(b),_32=function(a,b){a.readAsBinaryString(b);return 1},1}catch(d){return a.readAsArrayBuffer(b),_32=function(a,b){a.readAsArrayBuffer(b);return 2},2}};
function _78(a,b,d,c,g,k){function f(a,b,d){dhtmlx.alert({title:a,type:b,text:d});c&&c(g)}var l=!1,m=null;k&&_39._11(!0);var h="http://"+_39._54()+":"+_39._53()+"/"+a;if(500<b.length){var s=new JSZip;s.file("Z.ZIP",b,{base64:!1,binary:!0,compression:"DEFLATE"});b=s.generate({type:"blob"})}else b=new Blob([b],{type:"image/png"});m=_47();_46(m)&&(m.ontimeout=function(){f("Nafys","alert-error","Erreur Systeme : TimeOut")},m.onload=function(b){if(4===
m.readyState)if(200===m.status){b=new Uint8Array(this.response,0,4);if(4==b.byteLength&&80==b[0]&&75==b[1]&&3==b[2]&&4==b[3])try{var c=(new JSZip(this.response,{base64:!1})).file("Z.ZIP").asBinary()}catch(e){f("Nafys","alert-error","Erreur : "+e);return}else c=_88(this.response);"XMLA"==a?(c=c.split(String.fromCharCode(198)),3!=c.length?f("Nafys","alert-error","Donn\u00e9es non lues du serveur"):(l=c[0],_39._14(c[2]),0!=l&&3>c[1].length?_46(d)&&(k?_2(_39._48,
d,this,c[2],g,100):d(this,c[2],g)):0!=l&&3<c[1].length?(_46(d)&&(k?_2(_39._48,d,this,c[2],g,100):d(this,c[2],g)),f("Nafys","alert-warning",c[1])):3<c[1].length?f("Nafys","alert-warning",c[1]):f("Nafys","alert-error","Erreur Systeme"))):(_39._14(c),_46(d)&&(k?_2(_39._48,d,this,c,g,100):d(this,c,g)))}else f("Nafys","alert-error","Donn\u00e9es non lues du serveur")},m.open("POST",h,!0),m.timeout=3E4,m.responseType="arraybuffer",m.send(b))}
function _77(a,b,d){var c="http://"+_39.getsAdrGed()+":"+_39._53Ged()+"/DOWNLOAD?FileName="+encodeURIComponent(a),g=null,g=_47();_46(g)&&(g.ontimeout=function(){dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Erreur Systeme : TimeOut"})},g.onload=function(c){if(4===g.readyState&&200===g.status){c=new Blob([this.response],{type:"image/png"});var f=new FileReader;f.addEventListener("loadend",function(){var c=(new JSZip(f.result,{base64:!1})).file("Z.ZIP").asBinary();
_46(b)&&b(this,a,c,d)});f.readAsArrayBuffer(c)}},g.open("POST",c,!0),g.timeout=3E4,g.responseType="blob",g.send(null))}function _33(a,b,d,c,g){a=(new Fingerprint({canvas:!0,ie_activex:!0,screen_resolution:!0})).get();c=_92(null,1,"LOGIN","PROCEDURE","WRpsLogin");c=_90(c,1,0,"Login_",b);c=_90(c,1,0,"PassWord_",d);c=_90(c,1,0,"MachineId_",a);c=_92(c,2,"MENU","SELECT","Select * From WRfnListeMenus(:IdUser_)");c=_90(c,2,1,"IdUser_",0);return _1(c)}
function _45(a){var b=/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(a);if(b){a=a.split("/");var d=new Date(+a[2],a[1]-1,+a[0]);"[object Date]"===Object.prototype.toString.call(d)&&(b=!isNaN(d.getTime())&&d.getDate()==a[0]&&d.getMonth()==a[1]-1)}return b}function _3(a,b){"D"==b?a||(a="NULL"):"N"==b?a||(a=0):"S"==b?a||(a=""):"M"==b&&(a||(a=1));return a}function _73(){return Date.today().toString("dd/MM/yyyy")}
function _69(a,b){var d=a.getItemValue(b,!0).toString("dd/MM/yyyy");return"30/12/1899"==d?"":d}function _4(a){return 0==a.length?"&nbsp;":a}function _44(a,b){return null==a?!0:a.match(/^\d+$/)?!0:b&&a.match(/^\d+\.\d+$/)?!0:b&&a.match(/^\d+\,\d+$/)?!0:!1}function _34(a,b,d){b=b.keyCode;var c=String.fromCharCode(b);if(null==b||0==b||8==b||9==b||13==b||27==b||-1<"0123456789".indexOf(c))return!0;d&&"."==c&&a.form.elements[d].focus();return!1}
function _71(a,b){for(var d=b.split(String.fromCharCode(201)),c=0;c<d.length;c++){var g=d[c].split(String.fromCharCode(200));a.put(g[0],g[1])}}
function _27(a,b,d,c){6==a.cells(b,d[0]).getValue()?c?a.setCellExcellType(b,d[1],"ron"):(a.setCellExcellType(b,d[1],"edn"),a.setCellTextStyle(b,d[1],"color:red;border:1px solid gray;")):7==a.cells(b,d[0]).getValue()?c?a.setCellExcellType(b,d[1],"ro"):(a.setCellExcellType(b,d[1],"coro"),a.setCellTextStyle(b,d[1],"color:red;border:1px solid gray;"),c=a.getCustomCombo(b,d[1]),a=a.cells(b,d[2]).getValue(),_71(c,a)):a.setCellExcellType(b,d[1],"ron")}
function _51(a,b){try{var d=a.getElementsByTagName(b)[0].childNodes[0].nodeValue}catch(c){d=""}return d}function _81(a){a=a.split(/\D/);return new Date(Date.UTC(+a[0],--a[1],+a[2],+a[3],+a[4],+a[5],0))}function _80(a,b){b=b.replace("DD",(10>a.getDate()?"0":"")+a.getDate());b=b.replace("MM",(9>a.getMonth()?"0":"")+(a.getMonth()+1));return b=b.replace("YYYY",a.getFullYear())}function _5(a){a=_81(a);return _80(a,"DD/MM/YYYY")}
function _50(a,b){try{var d=a.getElementsByTagName(b)[0].childNodes[0].nodeValue,c=_81(d),d=1900>c.getFullYear()?"":_80(c,"DD/MM/YYYY")}catch(g){d=""}return d}function _13(a,b,d){try{a.getElementsByTagName(b)[0].childNodes[0].nodeValue=d}catch(c){alert("Erreur ==> "+c.message)}return a}
function _31(a,b,d,c,g,k,f,l,m,h,s){function n(a,c,d){e.startFastOperations();e.clearAll();_46(c)&&e.loadCSVString(c);e.stopFastOperations();_35(b,!1)}var p="",e,u=_92(null,1,k,"SELECT",l),u=_90(u,1,0,f,m+"%"),u=_90(u,1,0,"IdUser",_39._64()),u=_89(u,1,0,_39._74()),q=_1(u),u=null;_78("XMLA",q,n,null,[e],!0);_35(b,!0);e=d.attachGrid(h,320);e.startFastOperations();e.setIconsPath(_39._68());e.setImagePath(_39._63());
e.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;background-color:yellow;"]);e.attachHeader("#text_filter");e.setColTypes("ro");e.setColAlign("left");e.setColSorting("str");e.enableValidation(!0,!1);e.enableAutoWidth(!0);e.setInitWidths("300");e.enableDistributedParsing(!0,10,300);e.init();_36(e);e.csv.row=String.fromCharCode(197);e.csv.cell=String.fromCharCode(196);e.enableCSVAutoID(!1);e.clearAll();e.stopFastOperations();_35(b,!1);e.attachEvent("onHeaderClick",
function(b,f){var h=e.getSelectedRowId();h&&(_39._24(!0),a.setItemValue(c,h),a.setItemValue(g,e.cells(h,0).getValue()),d.hide(),e.clearSelection(),_46(s)&&s())});e.attachEvent("onRowDblClicked",function(b){_39._24(!0);a.setItemValue(c,b);a.setItemValue(g,e.cells(b,0).getValue());d.hide();e.clearSelection();_46(s)&&s()});e.attachEvent("onFilterEnd",function(a){if(15>=e.getRowsNum()){_35(b,!0);a=_92(null,1,k,"SELECT",l);var c=p[0].trim();a=_90(a,
1,0,f,""==c?"%":"%"+c+"%");a=_90(a,1,0,"IdUser",_39._64());a=_89(a,1,0,_39._74());a=_1(a);_78("XMLA",a,n,null,[e],!1)}});e.attachEvent("onFilterStart",function(a,b){p=b;return!0});d.show(g);e.getFilterElement(0).focus();e.getFilterElement(0).value=m;_39._11(!1)}
function _40(a,b,d){var c=_92(null,1,"FILETEST.PDF","IMPRIME",a);""!=b&&(c=_90(c,1,0,b,d));c=_90(c,1,0,"IdUser",_39._64());c=_89(c,1,0,_39._74());b=_1(c);c=null;_78("XMLA",b,function(a,b,c){_46(c)&&_46(c[0])&&(a="http://"+_39._54()+":"+_39._53()+"/DOWNLOAD?FileName="+encodeURIComponent(b),window.open(a,"_self"))},null,[a],!1)}
function _42(a,b,d,c){function g(b,c,d){f.startFastOperations();f.clearAll();_46(c)&&f.loadCSVString(c);f.stopFastOperations();_35(a,!1)}var k="",f,l="Select TOP 20 IdEtat, Libelle From dbo.WRFnPrint(IdEcran, IdUser) Where Libelle Like :Libelle Order By Libelle",l=l.replace("IdEcran",b),l=l.replace("IdUser",_39._64()),l=l.replace("Identifiant",c);b=_92(null,1,"ETATS","SELECT",l);b=_90(b,1,0,"LIBELLE","%");var m=_1(b);b=null;_78("XMLA",
m,g,null,[f],!0);_35(a,!0);var h=new dhtmlXPopup({mode:"right"});f=h.attachGrid(350,320);f.startFastOperations();f.setIconsPath(_39._68());f.setImagePath(_39._63());f.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;"]);f.attachHeader("#text_filter");f.setColTypes("ro");f.setColAlign("left");f.setColSorting("str");f.enableValidation(!0,!1);f.setInitWidths("*");f.enableDistributedParsing(!0,10,300);f.init();_36(f);f.csv.row=String.fromCharCode(197);
f.csv.cell=String.fromCharCode(196);f.enableCSVAutoID(!1);f.stopFastOperations();_35(a,!1);f.attachEvent("onHeaderClick",function(a,b){var g=f.getSelectedRowId();g&&(h.hide(),f.clearSelection(),_40(g,d,c))});f.attachEvent("onRowDblClicked",function(a){h.hide();f.clearSelection();_40(a,d,c)});f.attachEvent("onFilterEnd",function(b){if(15>=f.getRowsNum()){_35(a,!0);b=_92(null,1,"ETATS","SELECT",l);var c=k[0].trim();b=_90(b,1,0,"LIBELLE",""==c?"%":"%"+c+"%");b=_1(b);
_78("XMLA",b,g,null,[f],!1)}});f.attachEvent("onFilterStart",function(a,b){k=b;return!0});h.show(50,50,350,300);f.getFilterElement(0).focus();_39._11(!1);return h};
