var Cession;
(function(){var a=-1,b="",d="",c=0,f=0,h="192.168.1.167",e=8E3,k="",n=!1,g=0,l="http://dhtmlxgrid.appspot.com/export/pdf",r="http://dhtmlxgrid.appspot.com/export/excel",w="",m="E",A="",z=[],y={};Cession=function(){};Cession.prototype._77=function(){return a};Cession.prototype._29=function(c){a=c};Cession.prototype._80=function(){return c};Cession.prototype._32=function(a){c=a};Cession.prototype._72=function(){return b};Cession.prototype._26=function(a){b=a};
Cession.prototype._75=function(){return f};Cession.prototype._28=function(a){f=a};Cession.prototype._66=function(){return h};Cession.prototype._21=function(a){h=a};Cession.prototype._65=function(){return e};Cession.prototype._20=function(a){e=a};Cession.prototype._64=function(){return k};Cession.prototype._19=function(a){k=a};Cession.prototype._74=function(){return g};Cession.prototype._27=function(a){g=a};Cession.prototype._60=
function(){return A};Cession.prototype._16=function(a){A=a};Cession.prototype._57=function(){return n};Cession.prototype._13=function(a){n=a};Cession.prototype._58=function(){return l};Cession.prototype._14=function(a){l=a};Cession.prototype._59=function(){return r};Cession.prototype._15=function(a){r=a};Cession.prototype._87=function(){return m};Cession.prototype._35=function(a){m=a};Cession.prototype._71=function(){return d};Cession.prototype._25=
function(a){d=a};Cession.prototype._61=function(){return w};Cession.prototype._17=function(a){w=a};Cession.prototype._88=function(){return z};Cession.prototype._36=function(a){z=a};Cession.prototype._112=function(a){z.push(a)};Cession.prototype._106=function(){z=[];z.push([0,"IdUser_",a])};Cession.prototype._96=function(a){for(var c=z.length-1,b=!0;0<=c&&b;)z[c][0]>=a?(z.pop(),c--):b=!1};Cession.prototype._69=function(){return y};Cession.prototype._24=
function(a){y=a};Cession.prototype._81=function(){return"../imgs/"};Cession.prototype._76=function(){return"../codebase/imgs/"}})();var _47=new Cession,_52,_107;
window.onload=function(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()},!1);window.applicationCache.addEventListener("obsolete",function(a){window.applicationCache.update()},!1);dhtmlx.image_path="codebase/imgs/";_52=new dhtmlXLayoutObject({parent:document.body,pattern:"4I",skin:"dhx_skyblue"});var a=_52.cells("a");a.setText("Entete");a.setHeight("120");a.hideHeader();a.fixSize(0,1);var b=a.attachLayout("2E"),
a=b.cells("a");a.setText("Logo");a.setHeight("70");a.hideHeader();a.fixSize(0,1);a.attachHTMLString('<div id="MyCssGris" <span style="color:#F1F5F8;font-family:tahoma;font-size:58px;text-align:center;"><strong>Web@Report</strong></span></div>');_107=b.cells("b");_107.hideHeader();_107.fixSize(0,1);_107.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">Titre Etat</span></div>');_107.setHeight("30");
b=_52.cells("b");b.setText("Menu");b.setWidth("220");b.fixSize(1,0);var d=b.attachTree();d.setSkin("dhx_skyblue");d.setImagePath("../codebase/imgs/dhxtree_skyblue/");var c=_52.cells("c");c.setText("Etat");c.hideHeader();var f=_52.cells("d");f.hideHeader();f.fixSize(0,1);f.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:17px;text-align:center;z-index:20;">Copyright \u00a9 2014 by NtSoft &nbsp;&nbsp; &#0149;&nbsp;&nbsp;All Rights reserved  &nbsp;&nbsp; &#0149;&nbsp;&nbsp; E-Mail: support@nt-soft.ma</span></div>');
f.setHeight("25");_52.attachEvent("onResizeFinish",function(){_107.setHeight("30");f.setHeight("25")});b.collapse();b.hideArrow();d.enableHighlighting(!0);d.attachEvent("onSelect",function(a){if(a&&a.startsWith("M")&&null!=c&&0<_47._77()){for(;0<_47._75();)c.unloadView("Page"+_47._75()),_47._28(_47._75()-1);_47._25(d.getItemText(a));_2("{USERNAME} : {MENU}",[],_107);_47._106();c.showView("def");
var b=a.substring(1,2);a=parseInt(a.substring(2));0<a?"A"==b||"B"==b?_10(c,b,a,1):"C"==b||"D"==b?_11(c,b,a,1):"E"==b||"F"==b?_12(c,b,a,1):"G"==b?_49(a,LibIdent,rId):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."}):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."})}});c.hideHeader();_47._24(c);_8(c,d,a,b)};
window.onunload=function(){if(null!=_47._69()){var a=_47._69().getAttachedToolbar();a&&(_47._69().detachToolbar(),a.unload())}};function _37(a,b,d){a=b.split(String.fromCharCode(5));for(b=0;b<a.length;b++){var c=a[b].split(String.fromCharCode(4));0==c[1]&&""!=c[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:c[4]});"LOGIN"==c[2]&&"PROCEDURE"==c[3]&&1<=c[5].length?(c=_7(c[5]),_47._29(_63(c,"IdUser_")),_47._26(_63(c,"LibUser_")),_47._32(_63(c,"IdEcran_")),_47._14(_63(c,"UrlPdf_")),_47._15(_63(c,"UrlExcel_")),_47._35(_63(c,
"Auteur_")),c='<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">'+_47._72()+"</span></div>",_107.attachHTMLString(c)):"MENU"==c[2]&&"SELECT"==c[3]&&10<=c[5].length&&(c=_100(c[5]),d[0].deleteChildItems(0),d[0].loadCSVString(c),d[0].openAllItems(0))}d[1]&&d[1].hide&&(d[1].hide(),d[1].unload(),d[1]=null);if(d[2]&&d[2].showView){for(d[2].detachObject(!0);0<_47._75();)d[2].unloadView("Page"+_47._75()),
_47._28(_47._75()-1);d[2].showView("def")}_47._106();d[0].selectItem("G1");d[4]&&d[4].isCollapsed&&d[4].isCollapsed()&&(d[4].expand(),d[4].showArrow());d[5]&&d[5].unload}
function _8(a,b,d,c){var f={login:"Votre login personnel",pwd:"Votre Mot de Passe Confidentiel."};_47._28(_47._75()+1);a.showView("Page"+_47._75());_103("MyContainer");_105("#MyContainer","position:absolute;left: 50%;top: 50%;width: 350px; height: 280px; margin-left: -175px; margin-top: -140px;");_109("#MyContainer","MyContainer",!1);a.attachObject("MyContainer");var h=new dhtmlXForm("MyContainer",[{type:"settings",position:"label-top",
labelWidth:"150",inputWidth:"280"},{type:"fieldset",label:"Bienvenue",width:320,offsetLeft:10,offsetTop:10,list:[{type:"block",list:[{type:"label",name:"Titre",label:"<img src='../imgs/about.gif' />   NafysWeb"}]},{type:"input",name:"login",label:"Login",value:"",tooltip:"Login",required:!0},{type:"password",name:"pwd",label:"Mot de Passe",value:"",required:!0},{type:"button",name:"proceed",value:"Valider",width:"120",offsetLeft:"50"}]}]);h.setFontSize("17px");var e=new dhtmlXPopup({form:h,id:["login",
"pwd"]});h.attachEvent("onFocus",function(a){e.attachHTML("<div style='margin: 5px 10px;'>"+f[a]+"</div>");e.show(a)});h.attachEvent("onBlur",function(a){e&&e.hide&&e.hide()});h.attachEvent("onButtonClick",function(f){if("proceed"==f){f=h.getItemValue("login");var n=h.getItemValue("pwd");f=_41(_47._66(),f,n,_47._65(),0);_94("XMLZ",f,_37,null,[b,e,a,d,c,h],!1)}})};function _12(a,b,d,c){function f(){_47._96(c);e&&e.forEachItem(function(a){var b="",d=e.getItemType(a);"calendar"==d?(d=e.getItemValue(a),_55(d)&&(b=d.toString("dd/MM/yyyy")),"30/12/1899"==b&&(b=""),_47._112([c,a,b])):"input"==d?(b=e.getItemValue(a),_47._112([c,a,b])):"checkbox"==d&&(b=e.getItemValue(a),_47._112([c,a,b]))})}var h,e,k=0,n=0,g="",l,r,w="MyContainer"+b+"_"+d+"_"+c,m=_47._61();_47._96(c);_43(a,
!0);var A=_113(null,1,"GRIDEF","WRDIAG","WRPSGRIDEF"),A=_111(A,1,0,"IdEcran_",d),A=_110(A,1,0,_47._88()),z=_1(A),A=null;_94("XMLZ",z,function(d,t,v){if(_55(v)&&0<_47._77()){d=t.split(String.fromCharCode(5));t=null;for(t=0;t<d.length;t++)if(v=d[t].split(String.fromCharCode(4)),0==v[1]&&""!=v[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:v[4]}),"GRIDEF"==v[2]&&"WRDIAG"==v[3]&&1<=v[5].length){var s=_7(v[5]);v=_63(s,
"fForm_");var u=_63(s,"fTitre_");k=parseInt(_63(s,"fWinHeight_"));n=parseInt(_63(s,"fWinWidth_"));g=_63(s,"fDblClick_");s=null;_2(u,_47._88(),_107);0==n&&(n=2*a.getWidth()/3);0==k&&(k=2*a.getHeight()/3);s="E"==b?10:20;u=10;v=v.replace("NtsOffsetLeft",s);v=v.replace("NtsOffsetTop",u);v=eval(v);_103(w);s="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;overflow:auto;";s=s.replace("wwpx",n+"px");s=s.replace("hhpx",
k+"px");s=s.replace("llpx",Math.round(n/2)+"px");s=s.replace("ttpx",Math.round(k/2)+"px");_105("#"+w,s);_109("#"+w,w,!1);"E"==b?a.attachObject(w):(x.detachObject(!0),x.setDimension(n+100,k+100),x.centerOnScreen(),x.attachObject(w),x.attachEvent("onClose",function(a){_95(w);_95("#"+w);return!0}));e=new dhtmlXForm(w);l.form=e;e.enableLiveValidation(!0);e.setFontSize("17px");e.loadStruct(v);v=null;e.forEachItem(function(a){var b="",b=null,b=e.getItemType(a),d=e.getUserData(a,
"Key"),f=e.getUserData(a,"Sql");_55(d)&&_55(f)&&l.id.push(a);if("calendar"==b)e.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=e.getInput(a),b.style.textAlign="center",b=e.getItemValue(a),_47._112([c,a,b]);else if("input"==b){b=e.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";b=e.getItemValue(a);_47._112([c,a,b])}else"checkbox"==b&&(b=e.getItemValue(a),_47._112([c,a,b]),"0"==b||"N"==b?e.uncheckItem(a):
e.checkItem(a))});e.attachEvent("onKeyUp",function(b,c,d){if(9!=c.keyCode&&0<=l.id.indexOf(d)){b=e.getUserData(d,"Key");var g=e.getUserData(d,"Sql");c=String.fromCharCode(c.keyCode);f();_39(e,a,r,b,d,b,d,g,c,350)}});r=new dhtmlXPopup(l);""!=g&&e.attachEvent("onButtonClick",function(d,e){_55(h)&&(h.unload(),h=null);if("BtOui"==d){f();var s=g.substring(0,1),k=parseInt(g.substring(1));0<k&&("A"==s||"B"==s?("F"==b&&"A"==s&&_55(x)&&(_55(r)&&(r.unload(),l=r=null),x.close()),_10(a,
s,k,c+1)):"C"==s||"D"==s?("F"==b&&"C"==s&&_55(x)&&(_55(r)&&(r.unload(),l=r=null),x.close()),_11(a,s,k,c+1)):"E"==s||"F"==s?("F"==b&&"E"==s&&_55(x)&&(_55(r)&&(r.unload(),l=r=null),x.close()),_12(a,s,k,c+1)):"G"==s&&_49(k,"",""))}else"BtNon"==d&&("E"==b?(_55(r)&&(r.unload(),l=r=null),_95(w),_95("#"+w),a.unloadView("Page"+_47._75()),_47._28(_47._75()-1),s=_47._75(),0==s?(a.showView("def"),_47._106()):
(a.showView("Page"+s),_47._96(c)),_2(m,[],_107)):"F"==b&&_55(x)&&(_55(r)&&(r.unload(),l=r=null),_47._96(c),_2(m,[],_107),x.close()))})}else if(!("GRIDEF"==v[2]&&"DATA"==v[3]&&10<=v[5].length)&&"GRIDEF"==v[2]&&"TOOLS"==v[3]&&10<=v[5].length)for(v=v[5].split(String.fromCharCode(3)),s=0;s<v.length;s++)u=v[s].split(String.fromCharCode(2)),"A"==u[2]?y.addButton("A"+s,s,u[1],u[5],u[6]):"B"==u[2]?y.addButton("B"+s,s,u[1],u[5],u[6]):"C"==u[2]?
y.addText("C"+s,s,u[1]):"D"==u[2]?y.addSeparator("D"+s,s):"E"==u[2]?y.addButton("E"+u[4]+u[3],s,u[1],u[5],u[6]):"F"==u[2]?y.addButton("F"+u[7],s,u[1],u[5],u[6]):"G"==u[2]?y.addButton("G"+u[7],s,u[1],u[5],u[6]):y.addButton("E"+u[4]+u[3],s,u[1],u[5],u[6]);d=null;_43(a,!1)}},null,[a],!0);a.setText("Liste");if("E"==b){_47._28(_47._75()+1);a.showView("Page"+_47._75());var y=a.attachToolbar()}else{var A=_47._75(),x=_52.dhxWins.createWindow("myWind"+
A,100,100,400,400);x.centerOnScreen();x.setModal(!0);x.denyPark();x.setText("Web@Report");y=x.attachToolbar()}l={form:null,id:[]};y.setIconsPath(_47._81());y.attachEvent("onClick",function(e){_55(h)&&(h.unload(),h=null);var g=e.substring(0,1);"A"==g?(f(),h=_51(a,d,"","")):"B"==g&&"E"==b?(_55(r)&&(r.unload(),l=r=null),_95(w),_95("#"+w),a.unloadView("Page"+_47._75()),_47._28(_47._75()-1),e=_47._75(),0==e?(a.showView("def"),
_47._106()):(a.showView("Page"+e),_47._96(c)),_2(m,[],_107)):"B"==g&&"F"==b?_55(x)&&(_55(r)&&(r.unload(),l=r=null),_47._96(c),_2(m,[],_107),x.close()):"F"==g&&"E"==b?(e=e.substring(1),window.open(e,"_top")):"F"==g&&"F"==b?(e=e.substring(1),x.attachURL(e)):"G"==g?(e=e.substring(1),window.open(e,"_blank")):"E"==g&&(g=e.substring(1,2),e=parseInt(e.substring(2)),0<e&&(f(),"A"==g||"B"==g?("F"==b&&"A"==g&&_55(x)&&(_55(r)&&
(r.unload(),l=r=null),x.close()),_10(a,g,e,c+1)):"C"==g||"D"==g?("F"==b&&"C"==g&&_55(x)&&(_55(r)&&(r.unload(),l=r=null),x.close()),_11(a,g,e,c+1)):"E"==g||"F"==g?("F"==b&&"E"==g&&_55(x)&&(_55(r)&&(r.unload(),l=r=null),x.close()),_12(a,g,e,c+1)):"G"==g&&_49(e,"","")))});_47._13(!1)};function _11(a,b,d,c){var f,h,e=0,k=0,n="MyContainer"+b+"_"+d+"_"+c,g=_47._61();_47._96(c);_43(a,!0);var l=_113(null,1,"GRIDCD","WRFORM","WRPSGRIDCD"),l=_111(l,1,0,"IdEcran_",d),l=_110(l,1,0,_47._88()),r=_1(l),l=null;_94("XMLZ",r,function(d,f,g){if(_55(g)&&0<_47._77()){d=f.split(String.fromCharCode(5));f=null;for(f=0;f<d.length;f++)if(g=d[f].split(String.fromCharCode(4)),0==g[1]&&""!=g[4]&&dhtmlx.alert({title:"Web@Report",
type:"alert-error",text:g[4]}),"GRIDCD"==g[2]&&"WRFORM"==g[3]&&1<=g[5].length){var r=_7(g[5]);g=_63(r,"fForm_");var l=_63(r,"fTitre_");e=parseInt(_63(r,"fWinHeight_"));k=parseInt(_63(r,"fWinWidth_"));r=null;_2(l,_47._88(),_107);0==k&&(k=2*a.getWidth()/3);0==e&&(e=2*a.getHeight()/3);if("C"==b)var t=l=10;else l=20,t=10;g=g.replace("NtsOffsetLeft",l);g=g.replace("NtsOffsetTop",t);g=eval(g);_103(n);l="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;overflow:auto;";
l=l.replace("wwpx",k+"px");l=l.replace("hhpx",e+"px");l=l.replace("llpx",Math.round(k/2)+"px");l=l.replace("ttpx",Math.round(e/2)+"px");_105("#"+n,l);_109("#"+n,n,!1);"C"==b?a.attachObject(n):(m.detachObject(!0),m.setDimension(k+100,e+100),m.centerOnScreen(),m.attachObject(n),m.setText("Web@Report"),m.setModal(!0),m.denyPark(),m.button("close").enable(),m.attachEvent("onClose",function(a){_95(n);_95("#"+n);return!0}));h=new dhtmlXForm(n);h.enableLiveValidation(!0);h.setFontSize("17px");
h.loadStruct(g);g=null}else if("GRIDCD"==g[2]&&"DATA"==g[3]&&10<=g[5].length)r=_7(g[5]),h.forEachItem(function(a){var b="",b=null,b=h.getItemType(a);if("calendar"==b)h.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=h.getInput(a),b.style.textAlign="center",(b=_63(r,a))&&h.setItemValue(a,b),_47._112([c,a,b]);else if("input"==b){b=h.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";(b=_63(r,a))&&h.setItemValue(a,b);_47._112([c,
a,b])}else"checkbox"==b&&(b=_63(r,a),"0"==b||"N"==b?h.uncheckItem(a):h.checkItem(a),_47._112([c,a,b]))}),r=null;else if("GRIDCD"==g[2]&&"TOOLS"==g[3]&&10<=g[5].length)for(g=g[5].split(String.fromCharCode(3)),l=0;l<g.length;l++)t=g[l].split(String.fromCharCode(2)),"A"==t[2]?w.addButton("A"+l,l,t[1],t[5],t[6]):"B"==t[2]?w.addButton("B"+l,l,t[1],t[5],t[6]):"C"==t[2]?w.addText("C"+l,l,t[1]):"D"==t[2]?w.addSeparator("D"+l,l):"E"==t[2]?w.addButton("E"+t[4]+t[3],l,t[1],t[5],t[6]):"F"==t[2]?
w.addButton("F"+t[7],l,t[1],t[5],t[6]):"G"==t[2]?w.addButton("G"+t[7],l,t[1],t[5],t[6]):w.addButton("E"+t[4]+t[3],l,t[1],t[5],t[6]);d=null;_43(a,!1)}},null,[a],!0);a.setText("Liste");if("C"==b){_47._28(_47._75()+1);a.showView("Page"+_47._75());var w=a.attachToolbar()}else{var l=_47._75(),m=_52.dhxWins.createWindow("myWind"+l,20,30,50,50),w=m.attachToolbar();m.setText("Web@Report : En cours ... ");m.centerOnScreen();m.denyPark();m.button("close").disable()}w.setIconsPath(_47._81());
w.attachEvent("onClick",function(e){_55(f)&&(f.unload(),f=null);var h=e.substring(0,1);"A"==h?f=_51(a,d,"",""):"B"==h&&"C"==b?(_95(n),_95("#"+n),a.unloadView("Page"+_47._75()),_47._28(_47._75()-1),e=_47._75(),0==e?(a.showView("def"),_47._106()):(a.showView("Page"+e),_47._96(c)),_2(g,[],_107)):"B"==h&&"D"==b?_55(m)&&(_47._96(c),_2(g,[],_107),m.close()):"F"==
h&&"C"==b?(e=e.substring(1),window.open(e,"_top")):"F"==h&&"D"==b?(e=e.substring(1),m.attachURL(e)):"G"==h?(e=e.substring(1),window.open(e,"_blank")):"E"==h&&(h=e.substring(1,2),e=parseInt(e.substring(2)),0<e&&("A"==h||"B"==h?("F"==b&&"A"==h&&_55(m)&&m.close(),_10(a,h,e,c+1)):"C"==h||"D"==h?("F"==b&&"C"==h&&_55(m)&&m.close(),_11(a,h,e,c+1)):"E"==h||"F"==h?("F"==b&&"E"==h&&_55(m)&&m.close(),_12(a,h,e,c+1)):"G"==h&&_49(e,"","")))});_47._13(!1)}
;function _10(a,b,d,c){function f(b,c,d){g.startFastOperations();g.clearAll();_55(c)&&g.loadCSVString(c);g.stopFastOperations();_43(a,!1)}var h=[],e=[],k=[],n,g,l=null,r="",w="",m=0,A=0,z=_47._61();_43(a,!0);var y=_113(null,1,"GRIDAB","WRGRID","WRPSGRIDAB"),y=_111(y,1,0,"IdEcran_",d),y=_110(y,1,0,_47._88()),x=_1(y),y=null;_94("XMLZ",x,function(v,s,u){if(_55(u)&&0<_47._77()){var y=u="",x=s.split(String.fromCharCode(5));
s=null;for(v=0;v<x.length;v++){var q=x[v].split(String.fromCharCode(4));0==q[1]&&""!=q[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:q[4]});if("GRIDAB"==q[2]&&"WRGRID"==q[3]&&1<=q[5].length){var p=_7(q[5]),q=_63(p,"gHeader_"),z=_63(p,"gTitre_"),E=_63(p,"gFilter_"),B=_63(p,"gTypes_"),G=_63(p,"gColAlig_"),H=_63(p,"gColSort_"),F=_63(p,"gColType_"),C=_63(p,"gColWidth_");l=_63(p,"gCmdeSQL_");u=_63(p,"gTotaux_");var y=_63(p,"gFooter_"),I=_63(p,
"gColVars_");r=_63(p,"gLibIdent_");w=_63(p,"gDblClick_");m=parseInt(_63(p,"gWinHeight"));A=parseInt(_63(p,"gWinWidth"));var J="O"==_63(p,"gRecSrv_");e=F.split(",");k=I.split(",");F=p=null;g.startFastOperations();g.setHeader(q.split(","));""!=E&&g.attachHeader(E);if(0<B.indexOf("imgrw")){p=B.split(",");for(q=0;q<p.length;q++)g.setColumnId(q,p[q]+"_"+q);p=null;B=B.replace("imgro","img");B=B.replace("imgrw","img");g.attachEvent("onRowSelect",function(b,c){_55(n)&&(n.unload(),n=
null);if(_55(b)&&_55(c)&&"img"==g.getColType(c)&&g.getColumnId(c).startsWith("imgrw")){var d=g.cells(b,c).getValue(),d=d.substring(d.lastIndexOf("/")+1,d.lastIndexOf("."));_9(a,b,d)}})}else 0<B.indexOf("imgro")&&(B=B.replace("imgro","img"));g.setColTypes(B);g.setColAlign(G);g.setColSorting(H);g.enableValidation(!0,!1);if(0<C.indexOf("*"))g.setInitWidths(C);else{p=C.split(",");for(q=B=0;q<p.length;q++)B+=parseFloat(p[q]);p=null;99<B&&101>B?g.setInitWidthsP(C):g.setInitWidths(C)}if("O"==
u){p=y.split(String.fromCharCode(10));for(q=0;q<p.length;q++)C=p[q].trim(),5<C.length&&(C=C.split("&&"),g.attachFooter(C[0],C[1]),C=C=null);p=null}_2(z,_47._88(),_107);g.init();g.csv.row=String.fromCharCode(3);g.csv.cell=String.fromCharCode(2);g.enableCSVAutoID(!1);g.clearAll();g.stopFastOperations()}else if("GRIDAB"==q[2]&&"DATA"==q[3]&&10<=q[5].length)s=q[5];else if("GRIDAB"==q[2]&&"FOOTER"==q[3]&&10<=q[5].length&&"O"==u){p=_7(q[5]);z=_91(y,' id="','"');
for(q=0;q<z.length;q++)if(C=document.getElementById(z[q]))if(B=_63(p,z[q]))B=parseFloat(B),C.innerHTML=B.toMoney();p=z=null}else if("GRIDAB"==q[2]&&"TOOLS"==q[3]&&10<=q[5].length)for(z=q[5].split(String.fromCharCode(3)),q=0;q<z.length;q++)p=z[q].split(String.fromCharCode(2)),"A"==p[2]?D.addButton("A"+q,q,p[1],p[5],p[6]):"B"==p[2]?D.addButton("B"+q,q,p[1],p[5],p[6]):"C"==p[2]?D.addText("C"+q,q,p[1]):"D"==p[2]?D.addSeparator("D"+q,q):"E"==p[2]?D.addButton("E"+p[4]+p[3],q,p[1],p[5],p[6]):"F"==p[2]?
D.addButton("F"+p[7],q,p[1],p[5],p[6]):"G"==p[2]?D.addButton("G"+p[7],q,p[1],p[5],p[6]):"P"==p[2]?D.addButton("P"+q,q,p[1],p[5],p[6]):"X"==p[2]?D.addButton("X"+q,q,p[1],p[5],p[6]):D.addButton("E"+p[4]+p[3],q,p[1],p[5],p[6])}x=q=null;for(v=0;v<e.length;v++)u=parseInt(e[v].substring(1)),2==u?g.setNumberFormat("0,000.00",v,"."," "):3==u&&g.setNumberFormat("0,000.00%",v,"."," ");g.startFastOperations();_55(s)&&g.loadCSVString(s);g.stopFastOperations();s=null;"B"==b&&_55(t)&&(0==A&&(A=2*
a.getWidth()/3),0==m&&(m=2*a.getHeight()/3),t.setDimension(A,m),t.centerOnScreen());""!=w&&g.attachEvent("onRowDblClicked",function(b,d){_55(n)&&(n.unload(),n=null);if(null!=b){_47._96(c);_47._112([c,r,b]);for(var e=0;e<k.length;e++){var f=k[e],h=g.cells(b,e).getValue();_47._112([c,f,h])}}e=w.substring(0,1);f=parseInt(w.substring(1));0<f&&("A"==e||"B"==e?_10(a,e,f,c+1):"C"==e||"D"==e?_11(a,e,f,c+1):"E"==e||"F"==e?_12(a,e,f,c+1):"G"==
e&&_49(f,r,b))});J&&(g.attachEvent("onFilterEnd",function(b){_55(n)&&(n.unload(),n=null);if(25>g.getRowsNum()){_43(a,!0);_47._96(c);for(var r=_113(null,1,"SQL","SELECT",l),r=_111(r,1,0,"IdEcran_",d),s=!0,m=0;m<b.length;m++){var p=b[m][1],q=parseInt(e[p].substring(1));if(4==q||5==q)s=s&&(""==h[m]||_54(h[m]));r=_111(r,1,0,k[p],h[m])}s&&(r=_110(r,1,0,_47._88()),b=_1(r),_94("XMLA",b,f,null,[a],!1))}}),g.attachEvent("onFilterStart",
function(a,b){h=b;for(var c=!0,d=0;d<a.length;d++){var g=parseInt(e[a[d]].substring(1));if(4==g||5==g)c=c&&(""==h[d]||_54(h[d]))}return c}));_43(a,!1)}},null,[a],!0);a.setText("Liste");if("A"==b){_47._28(_47._75()+1);a.showView("Page"+_47._75());var D=a.attachToolbar();g=a.attachGrid()}else{var y=_47._75(),t=_52.dhxWins.createWindow("myWind"+y,100,100,2*a.getWidth()/3,2*a.getHeight()/3);t.centerOnScreen();t.setModal(!0);t.denyPark();t.setText("Web@Report");
g=t.attachGrid();D=t.attachToolbar()}D.setIconsPath(_47._81());D.attachEvent("onClick",function(e){_55(n)&&(n.unload(),n=null);var f=e.substring(0,1);if("A"==f){if(_47._96(c),e=g.getSelectedRowId(),null!=e){_47._112([c,r,e]);for(var h=0;h<k.length;h++){var l=k[h],m=g.cells(e,h).getValue();_47._112([c,l,m])}n=_51(a,d,r,e)}}else if("B"==f&&"A"==b)a.unloadView("Page"+_47._75()),_47._28(_47._75()-1),f=_47._75(),
0==f?(a.showView("def"),_47._106()):(a.showView("Page"+f),_47._96(c)),_2(z,[],_107);else if("B"==f&&"B"==b)_55(t)&&(_47._96(c),_2(z,[],_107),t.close());else if("P"==f)g.toPDF(_47._58());else if("X"==f)g.toPDF(_47._59());else if("F"==f&&"A"==b)f=e.substring(1),window.open(f,"_top");else if("F"==f&&"B"==b)f=e.substring(1),t.attachURL(f);else if("G"==f)f=e.substring(1),window.open(f,"_blank");else if("E"==
f){var f=e.substring(1,2),q=parseInt(e.substring(2));_47._96(c);e=g.getSelectedRowId();if(null!=e)for(_47._112([c,r,e]),h=0;h<k.length;h++)l=k[h],m=g.cells(e,h).getValue(),_47._112([c,l,m]);0<q&&("A"==f||"B"==f?_10(a,f,q,c+1):"C"==f||"D"==f?_11(a,f,q,c+1):"E"==f||"F"==f?_12(a,f,q,c+1):"G"==f&&_49(q,r,e))}});g.startFastOperations();g.setIconsPath(_47._81());g.setImagePath(_47._76());g.enableValidation(!0,!1);
g.enableDistributedParsing(!0,10,300);g.setDateFormat("%d/m/Y");g.i18n.decimal_separator=".";g.i18n.group_separator=" ";g.enableCSVAutoID(!1);g.stopFastOperations();g.attachEvent("onRowSelect",function(a,b){_55(n)&&(n.unload(),n=null)});g.attachEvent("onEditCell",function(a,b,c,d,e){_55(n)&&(n.unload(),n=null);return!1});_47._13(!1)};"undefined"===typeof Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});function _91(a,b,d){for(var c=[],f=_92(a,b,d);0<f.length;)c.push(f),a=_38(a,f),f=_92(a,b,d);return c}function _92(a,b,d){return(a=a.match(b+"(.*?)"+d))&&0<a.length?a[1]:""}function _38(a,b){var d=a.indexOf(b);return-1!=d?a.substr(d+b.length):a}
function _48(a,b){var d=[a];for("string"==typeof b&&(b=[b]);0<b.length;){for(var c=0;c<d.length;c++)var f=d[c].split(b[0]),d=d.slice(0,c).concat(f).concat(d.slice(c+1));b.shift()}return d}function _95(a){(a=document.getElementById(a))&&a.parentNode.removeChild(a)}
function _103(a){var b=document.getElementById(a);b?(b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)"):(b=document.createElement("div"),b.id=a,b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)",document.body.appendChild(b))}function _105(a,b){var d=document.createElement("style");d.type="text/css";document.getElementsByTagName("head")[0].appendChild(d);(d.sheet||{}).insertRule?d.sheet.insertRule(a+"{"+b+"}",0):(d.styleSheet||d.sheet).addRule(a,b)}
function _109(a,b,d){"string"==typeof b.valueOf()&&(b=document.getElementById(b));b&&(b.className=d?b.className.replace(new RegExp("\\b"+a+"\\b","g"),""):b.className+" "+a)}
function _46(a){function b(a,b,c){if(_55(c)&&0<_47._77()){var d=a=_47._79();b=b.split(String.fromCharCode(5));for(var n=0;n<b.length;n++){var g=b[n].split(String.fromCharCode(4));0==g[1]&&""!=g[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:g[4]});"PUBIDT"==g[2]&&"PROCEDURE"==g[3]&&1<=g[5].length?(d=_7(g[5]),d=_63(d,"IdPub_"),d=parseInt(d),0<d&&_47._31(d)):"PUBDET"==g[2]&&"BLOB"==g[3]&&10<=g[5].length&&a!=d&&c[0].attachHTMLString(g[5])}}else _45()}
if(0>=_47._77()||!_55(a))_45();else{var d=_113(null,1,"PUBIDT","PROCEDURE","WRPsPub"),d=_111(d,1,0,"IdUser_",_47._77()),d=_111(d,1,0,"IdPub_",_47._79()),d=_113(d,2,"PUBDET","BLOB","Select * From WRfnPub(:IdPub_)"),d=_111(d,2,1,"IdPub_",0),c=_1(d),d=null;_94("XMLZ",c,b,null,[a],!1)}}function _45(){var a=_47._68();_55(a)&&clearInterval(_47._68());_47._23(null)}var DEBUG=!1;
if(!DEBUG){window.console||(window.console={});for(var methods="log debug warn info dir dirxml trace profile".split(" "),i=0;i<methods.length;i++)console[methods[i]]=function(){}}function _3(a,b,d,c,f,h){a()?window.setTimeout(_3,h,a,b,d,c,f,h):b(d,c,f)}function _44(a){(window.dhx4.isIPad||window.dhx4.isChrome||window.dhx4.isOpera||window.dhx4.isKHTML||window.dhx4.isFF)&&a.enableEditEvents(!0,!1,!1)}
function _89(a){return 1==a?"doc":2==a?"xls":3==a?"rtf":4==a?"xls":5==a?"pdf":6==a||7==a?"jpg":8==a?"zip":9==a?"rar":"pdf"}function _90(a){return"doc"==a?1:"xls"==a?2:"rtf"==a?3:"pdf"==a?5:"jpg"==a?6:"zip"==a?8:"rar"==a?9:"txt"==a?3:5}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});String.prototype.formatedfloat||(String.prototype.formatedfloat=function(){return parseFloat(this.replace(",",".").replace(" ",""))});
"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return this.slice(0,a.length)==a});"function"!=typeof Number.prototype.toMoney&&(Number.prototype.toMoney=function(a,b,d){var c=this;a=isNaN(a)?2:Math.abs(a);b=b||".";d="undefined"===typeof d?" ":d;var f=0>c?"-":"",h=parseInt(c=Math.abs(c).toFixed(a))+"",e=3<(e=h.length)?e%3:0;return f+(e?h.substr(0,e)+d:"")+h.substr(e).replace(/(\d{3})(?=\d)/g,"$1"+d)+(a?b+Math.abs(c-h).toFixed(a).slice(2):"")});
function _55(a){return"undefined"!=typeof a&&null!=a&&""!=a}function _83(a){return a.substr((~-a.lastIndexOf(".")>>>0)+2)}function _99(a,b){var d=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()),c=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate());return Math.floor((c-d)/864E5)}
function _101(a){var b=String.fromCharCode(3),d=String.fromCharCode(2);a=a.split(b);for(var b=[],c=[],f=-1,h=-1,e=[],k={},n=0;n<a.length;n++){var g=a[n].split(d),k={},h=parseInt(g[3]);f!=h&&(-1!=f&&(k.id=e[0]+"_"+e[3],k.text=e[4],k.item=c,b.push(k),k={},c=[]),f=h,e=g);k.id=g[0];k.text=g[2];c.push(k)}k={};k.id=e[0]+"_"+e[3];k.text=e[4];k.item=c;b.push(k);return"{id:0,  item:"+JSON.stringify(b)+"}"}
function _100(a){var b=String.fromCharCode(3),d=String.fromCharCode(2);a=a.split(b);for(var c=b=-1,f="",h="",e=0;e<a.length;e++){var k=a[e].split(d),c=parseInt(k[4]);b!=c&&(b=c,f="G"+(e+1),h=h+"\n"+f+",0,"+k[5]);h=h+"\nM"+k[1]+k[0]+","+f+","+k[3]}return h}
function _102(a){var b=String.fromCharCode(3),d=String.fromCharCode(2);a=a.split(b);var b=[],c=a[0].split(d);c[0]="value";c[1]="text";for(var f=0;f<a.length;f++){var h={},e=a[f].split(d);h[c[0]]=e[0];h[c[1]]=e[1];b.push(h)}return"{options:"+JSON.stringify(b)+"}"}
var _70=function(){var a;if("undefined"!=typeof window.ActiveXObject)for(var b="Msxml2.DOMDocument.6.0 Msxml2.DOMDocument.5.0 Msxml2.DOMDocument.4.0 Msxml2.DOMDocument.3.0 MSXML2.DOMDocument MSXML.DOMDocument Microsoft.XMLDOM".split(" "),d=0;d<b.length;d++)try{a=new ActiveXObject(b[d]);_70=function(){return new ActiveXObject(b[d])};break}catch(c){}return a};
function _7(a){var b=null;if(window.DOMParser&&!window.ActiveXObject){var d=new DOMParser;try{b=d.parseFromString(a,"text/xml")}catch(c){try{b=_70(),b.async=!1,b.loadXML(a)}catch(f){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}}}else try{b=_70(),b.async=!1,b.loadXML(a)}catch(h){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}return b}
function _1(a){return window.ActiveXObject?a.xml:(new XMLSerializer).serializeToString(a)}function _43(a,b){}
function _113(a,b,d,c,f){_55(a)||(a=_7("<?xml version='1.0' encoding='UTF-16'?><Actions></Actions>"));var h=a.getElementsByTagName("Actions"),e=a.createElement("Action"),k=a.createElement("Type"),n=a.createElement("SQL");c=a.createTextNode(c);f=a.createTextNode(f);n.appendChild(f);k.appendChild(c);e.setAttribute("ID",b);e.setAttribute("Name",d);e.appendChild(k);e.appendChild(n);h[0].appendChild(e);return a}
function _2(a,b,d){for(var c=_91(a,"{","}"),f=0;f<c.length;f++){var h=c[f];if("USERNAME"==h)a=a.replace("{USERNAME}",_47._72());else if("MENU"==h)a=a.replace("{MENU}",_47._71());else for(var e=!1,k=b.length;!e&&0<k;)k--,h==b[k][1].toUpperCase()&&(e=!0),e&&(a=a.replace("{"+h+"}",b[k][2]))}""!=a.trim()&&(d.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">'+a+"</span></div>"),_47._17(a))}
function _110(a,b,d,c){for(var f=c.length-1,h="",e=0,k=0;k<=f;k++)e=h.search(c[f-k][1]),0>e&&(h=h+";"+c[f-k][1],a=_111(a,b,d,c[f-k][1],c[f-k][2]));return a}function _111(a,b,d,c,f){var h=a.getElementsByTagName("Action"),e=a.createElement("Param"),k=a.createElement("Value");null==f&&(f="");f=a.createTextNode(f);k.appendChild(f);e.setAttribute("Source",d);e.setAttribute("Name",c);e.appendChild(k);for(d=0;d<h.length;d++)h[d].getAttribute("ID")==b&&h[d].appendChild(e);return a}
function _73(a){var b=a.match(/[^\x00-\xff]/g);return a.length+(b?b.length:0)}function _104(a,b){var d=new XMLHttpRequest;"withCredentials"in d?d.open(a,b,!0):"undefined"!=typeof XDomainRequest?(d=new XDomainRequest,d.open(a,b)):d=null;return d}
var _56=function(){var a;try{a=new XMLHttpRequest,_56=function(){return new XMLHttpRequest}}catch(b){for(var d=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0,f=d.length;c<f;++c)try{a=new ActiveXObject(d[c]);_56=function(){return new ActiveXObject(d[c])};break}catch(h){}}return a};
function _108(a){var b=a.byteLength;a=new Uint8Array(a);if(8192>b)return String.fromCharCode.apply(null,a);for(var d=0,c="";d<b;)c+=String.fromCharCode.apply(null,a.subarray(d,d+8192)),d+=8192;return c}var _40=function(a,b){try{return a.readAsBinaryString(b),_40=function(a,b){a.readAsBinaryString(b);return 1},1}catch(d){return a.readAsArrayBuffer(b),_40=function(a,b){a.readAsArrayBuffer(b);return 2},2}};
function _94(a,b,d,c,f,h){function e(a,b,d){dhtmlx.alert({title:a,type:b,text:d});c&&c(f)}var k=!1,n=null;h&&_47._13(!0);var g="http://"+_47._66()+":"+_47._65()+"/"+a;if(500<b.length){var l=new JSZip;l.file("Z.ZIP",b,{base64:!1,binary:!0,compression:"DEFLATE"});b=l.generate({type:"blob"})}else b=new Blob([b],{type:"image/png"});n.setRequestHeader("Content-type","application/x-www-form-urlencoded");n=_56();_55(n)&&(n.ontimeout=function(){e("Nafys","alert-error","Erreur Systeme : TimeOut")},n.onload=function(b){if(4===
n.readyState)if(200===n.status){try{var c=new Uint8Array(this.response,0,4);if(4==c.byteLength&&80==c[0]&&75==c[1]&&3==c[2]&&4==c[3])try{var g=(new JSZip(this.response,{base64:!1})).file("Z.ZIP").asBinary()}catch(l){e("Nafys","alert-error","Erreur : "+l);return}else g=_108(this.response)}catch(z){g=_108(this.response)}"XMLA"==a?(b=g.split(String.fromCharCode(4)),3!=b.length?e("Nafys","alert-error","Donn\u00e9es non lues du serveur"):(k=b[0],_47._19(b[2]),
0!=k&&3>b[1].length?_55(d)&&(h?_3(_47._57,d,this,b[2],f,100):d(this,b[2],f)):0!=k&&3<b[1].length?(_55(d)&&(h?_3(_47._57,d,this,b[2],f,100):d(this,b[2],f)),e("Nafys","alert-warning",b[1])):3<b[1].length?e("Nafys","alert-warning",b[1]):e("Nafys","alert-error","Erreur Systeme"))):(_47._19(g),_55(d)&&(h?_3(_47._57,d,this,g,f,100):d(this,g,f)))}else e("Nafys","alert-error","Donn\u00e9es non lues du serveur")},n.open("POST",
g,!0),n.timeout=3E4,n.responseType="arraybuffer",n.send(b))}
function _93(a,b,d){var c="http://"+_47.getsAdrGed()+":"+_47._65Ged()+"/DOWNLOAD?FileName="+encodeURIComponent(a),f=null,f=_56();_55(f)&&(f.ontimeout=function(){dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Erreur Systeme : TimeOut"})},f.onload=function(c){if(4===f.readyState&&200===f.status){c=new Blob([this.response],{type:"image/png"});var e=new FileReader;e.addEventListener("loadend",function(){var c=(new JSZip(e.result,{base64:!1})).file("Z.ZIP").asBinary();
_55(b)&&b(this,a,c,d)});e.readAsArrayBuffer(c)}},f.open("POST",c,!0),f.timeout=3E4,f.responseType="blob",f.send(null))}function _41(a,b,d,c,f){a=(new Fingerprint({canvas:!0,ie_activex:!0,screen_resolution:!0})).get();c=_113(null,1,"LOGIN","PROCEDURE","WRpsLogin");c=_111(c,1,0,"Login_",b);c=_111(c,1,0,"PassWord_",d);c=_111(c,1,0,"MachineId_",a);c=_113(c,2,"MENU","SELECT","Select * From WRfnListeMenus(:IdUser_)");c=_111(c,2,1,"IdUser_",0);return _1(c)}
function _54(a){var b=/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(a);if(b){a=a.split("/");var d=new Date(+a[2],a[1]-1,+a[0]);"[object Date]"===Object.prototype.toString.call(d)&&(b=!isNaN(d.getTime())&&d.getDate()==a[0]&&d.getMonth()==a[1]-1)}return b}function _4(a,b){"D"==b?a||(a="NULL"):"N"==b?a||(a=0):"S"==b?a||(a=""):"M"==b&&(a||(a=1));return a}function _86(){return Date.today().toString("dd/MM/yyyy")}
function _82(a,b){var d=a.getItemValue(b,!0).toString("dd/MM/yyyy");return"30/12/1899"==d?"":d}function _5(a){return 0==a.length?"&nbsp;":a}function _53(a,b){return null==a?!0:a.match(/^\d+$/)?!0:b&&a.match(/^\d+\.\d+$/)?!0:b&&a.match(/^\d+\,\d+$/)?!0:!1}function _42(a,b,d){b=b.keyCode;var c=String.fromCharCode(b);if(null==b||0==b||8==b||9==b||13==b||27==b||-1<"0123456789".indexOf(c))return!0;d&&"."==c&&a.form.elements[d].focus();return!1}
function _84(a,b){for(var d=b.split(String.fromCharCode(201)),c=0;c<d.length;c++){var f=d[c].split(String.fromCharCode(200));a.put(f[0],f[1])}}
function _33(a,b,d,c){6==a.cells(b,d[0]).getValue()?c?a.setCellExcellType(b,d[1],"ron"):(a.setCellExcellType(b,d[1],"edn"),a.setCellTextStyle(b,d[1],"color:red;border:1px solid gray;")):7==a.cells(b,d[0]).getValue()?c?a.setCellExcellType(b,d[1],"ro"):(a.setCellExcellType(b,d[1],"coro"),a.setCellTextStyle(b,d[1],"color:red;border:1px solid gray;"),c=a.getCustomCombo(b,d[1]),a=a.cells(b,d[2]).getValue(),_84(c,a)):a.setCellExcellType(b,d[1],"ron")}
function _63(a,b){try{var d=a.getElementsByTagName(b)[0].childNodes[0].nodeValue}catch(c){d=""}return d}function _98(a){a=a.split(/\D/);return new Date(Date.UTC(+a[0],--a[1],+a[2],+a[3],+a[4],+a[5],0))}function _97(a,b){b=b.replace("DD",(10>a.getDate()?"0":"")+a.getDate());b=b.replace("MM",(9>a.getMonth()?"0":"")+(a.getMonth()+1));return b=b.replace("YYYY",a.getFullYear())}function _6(a){a=_98(a);return _97(a,"DD/MM/YYYY")}
function _62(a,b){try{var d=a.getElementsByTagName(b)[0].childNodes[0].nodeValue,c=_98(d),d=1900>c.getFullYear()?"":_97(c,"DD/MM/YYYY")}catch(f){d=""}return d}function _18(a,b,d){try{a.getElementsByTagName(b)[0].childNodes[0].nodeValue=d}catch(c){alert("Erreur ==> "+c.message)}return a}
function _39(a,b,d,c,f,h,e,k,n,g,l){function r(a,c,d){m.startFastOperations();m.clearAll();_55(c)&&m.loadCSVString(c);m.stopFastOperations();_43(b,!1)}var w="",m,A=_113(null,1,h,"SELECT",k),A=_111(A,1,0,e,n+"%"),A=_111(A,1,0,"IdUser",_47._77()),A=_110(A,1,0,_47._88()),z=_1(A),A=null;_94("XMLA",z,r,null,[m],!0);_43(b,!0);m=d.attachGrid(g,320);m.startFastOperations();m.setIconsPath(_47._81());m.setImagePath(_47._76());
m.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;background-color:yellow;"]);m.attachHeader("#text_filter");m.setColTypes("ro");m.setColAlign("left");m.setColSorting("str");m.enableValidation(!0,!1);m.enableAutoWidth(!0);m.setInitWidths("300");m.enableDistributedParsing(!0,10,300);m.init();_44(m);m.csv.row=String.fromCharCode(3);m.csv.cell=String.fromCharCode(2);m.enableCSVAutoID(!1);m.clearAll();m.stopFastOperations();_43(b,!1);m.attachEvent("onHeaderClick",
function(b,e){var g=m.getSelectedRowId();g&&(a.setItemValue(c,g),a.setItemValue(f,m.cells(g,0).getValue()),d.hide(),m.clearSelection(),_55(l)&&l())});m.attachEvent("onRowDblClicked",function(b){a.setItemValue(c,b);a.setItemValue(f,m.cells(b,0).getValue());d.hide();m.clearSelection();_55(l)&&l()});m.attachEvent("onFilterEnd",function(a){if(15>=m.getRowsNum()){_43(b,!0);a=_113(null,1,h,"SELECT",k);var c=w[0].trim();a=_111(a,1,0,e,""==c?"%":"%"+c+"%");a=_111(a,1,0,
"IdUser",_47._77());a=_110(a,1,0,_47._88());a=_1(a);_94("XMLA",a,r,null,[m],!1)}});m.attachEvent("onFilterStart",function(a,b){w=b;return!0});d.show(f);m.getFilterElement(0).focus();m.getFilterElement(0).value=n;_47._13(!1)}
function _49(a,b,d){var c=_113(null,1,"FILETEST.PDF","IMPRIME",a);""!=b&&(c=_111(c,1,0,b,d));c=_111(c,1,0,"IdUser",_47._77());c=_110(c,1,0,_47._88());b=_1(c);c=null;_94("XMLA",b,function(a,b,c){_55(c)&&_55(c[0])&&(a="http://"+_47._66()+":"+_47._65()+"/DOWNLOAD?FileName="+encodeURIComponent(b),window.open(a,"_self"))},null,[a],!1)}
function _51(a,b,d,c){function f(b,c,d){e.startFastOperations();e.clearAll();_55(c)&&e.loadCSVString(c);e.stopFastOperations();_43(a,!1)}var h="",e,k="Select TOP 20 IdEtat, Libelle From dbo.WRFnPrint(IdEcran, IdUser) Where Libelle Like :Libelle Order By Libelle",k=k.replace("IdEcran",b),k=k.replace("IdUser",_47._77()),k=k.replace("Identifiant",c);b=_113(null,1,"ETATS","SELECT",k);b=_111(b,1,0,"LIBELLE","%");var n=_1(b);b=null;_94("XMLA",
n,f,null,[e],!0);_43(a,!0);var g=new dhtmlXPopup({mode:"right"});e=g.attachGrid(350,320);e.startFastOperations();e.setIconsPath(_47._81());e.setImagePath(_47._76());e.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;"]);e.attachHeader("#text_filter");e.setColTypes("ro");e.setColAlign("left");e.setColSorting("str");e.enableValidation(!0,!1);e.setInitWidths("*");e.enableDistributedParsing(!0,10,300);e.init();_44(e);e.csv.row=String.fromCharCode(3);
e.csv.cell=String.fromCharCode(2);e.enableCSVAutoID(!1);e.stopFastOperations();_43(a,!1);e.attachEvent("onHeaderClick",function(a,b){var f=e.getSelectedRowId();f&&(g.hide(),e.clearSelection(),_49(f,d,c))});e.attachEvent("onRowDblClicked",function(a){g.hide();e.clearSelection();_49(a,d,c)});e.attachEvent("onFilterEnd",function(b){if(15>=e.getRowsNum()){_43(a,!0);b=_113(null,1,"ETATS","SELECT",k);var c=h[0].trim();b=_111(b,1,0,"LIBELLE",""==c?"%":"%"+c+"%");b=_1(b);
_94("XMLA",b,f,null,[e],!1)}});e.attachEvent("onFilterStart",function(a,b){h=b;return!0});g.show(50,50,350,300);e.getFilterElement(0).focus();_47._13(!1);return g}
function _9(a,b,d){var c,f=0,h=!1,e=!1;d="Select IdObs, IdUser, Auteur, DateObs, Obs, Statut From dbo.WRFnObs(@IdUser_, '@Auteur_', '@Identifiant_') Order By IdObs desc".replace("@Identifiant_",b);d=d.replace("@IdUser_",_47._77());d=d.replace("@Auteur_",_47._87());d=_113(null,1,"OBS","SELECT",d);var k=_1(d);d=null;_94("XMLA",k,function(b,d,k){_55(d)&&(c.startFastOperations(),c.clearAll(),c.loadCSVString(d),0<c.getRowsNum()?(c.selectRow(0),
f=c.getSelectedRowId(),c.cells(f,0).getValue()):(c.addRow(c.uid(),[_47._77(),_47._87(),_86(),"",""],0),c.selectRow(0),f=c.getSelectedRowId(),e=h=!0),c.stopFastOperations(),c.forEachRow(function(a){"M"==c.cells(a,1).getValue()?c.setRowColor(a,"green"):c.setRowColor(a,"red")}),c.selectRow(0));_43(a,!1)},null,[c],!0);_43(a,!0);d=_47._75();var n=_52.dhxWins.createWindow("myWind"+d,100,100,2*a.getWidth()/3,2*a.getHeight()/3);n.centerOnScreen();
n.setModal(!0);n.denyPark();n.setText("Ecran de contr\u00f4le");c=n.attachGrid();d=n.attachToolbar();d.setIconsPath(_47._81());d.addButton("N",0,"Nouveau","new.gif");d.addButton("S",1,"Sauvegarder","save.gif");d.addButton("F",2,"Fermer","close.gif");d.attachEvent("onClick",function(d){if("F"==d&&0==e)n.close();else if("F"==d&&1==e)dhtmlx.confirm({type:"confirm-warning",title:"Nafys",cancel:"Annuler",ok:"Fermer",text:"Confirmez l'abandon de cette saisie.",callback:function(a){1==a&&
n.close()}});else if("N"==d&&0==h)f=c.uid(),c.addRow(f,[_47._77(),_47._87(),_86(),"",""],0),"M"==_47._87()?c.setRowColor(f,"green"):c.setRowColor(f,"red"),c.selectRow(0),h=e=!0;else if("S"==d&&1==e&&_55(f)){_43(a,!0);var l=1==h?"Insert into WRObs(Identifiant, IdUser, Auteur, Obs, Statut) values(:Identifiant, :IdUser,  :Auteur, :Obs, :Statut)":"Update WRObs Set Obs = :Obs, Statut = :Statut Where IdObs = :IdObs";d=c.cells(f,3).getValue();var k=
c.cells(f,4).getValue(),k="Validation"==k?"G":"Attention"==k?"Y":"Erreur"==k?"R":"Non Controle"==k?"W":"Corrige"==k?"B":"W",l=_113(null,1,"OBS","EXECUTE",l),l=_111(l,1,0,"Identifiant",b),l=_111(l,1,0,"IdUser",_47._77()),l=_111(l,1,0,"Auteur",_47._87()),l=_111(l,1,0,"Obs",d),l=_111(l,1,0,"Statut",k),l=_111(l,1,0,"IdObs",f);d=_1(l);l=null;_94("XMLA",d,null,null,null,!1);h=e=!1}});c.startFastOperations();c.setIconsPath(_47._81());
c.setImagePath(_47._76());c.setHeader(["User","Auteur","Date Obs","Observations","Statut"]);c.setColTypes("ro,ro,ro,txt,context");c.setColAlign("right,center,center,left,center");c.setColSorting("int,str,int,str,str");c.enableValidation(!0,!1);c.setInitWidthsP("0, 10, 20, 60, 10");c.enableDistributedParsing(!0,10,300);d=new dhtmlXMenuObject;d.setIconsPath(_47._81());d.addNewChild(d.topId,0,"G","Validation",!1,"green.gif");d.addNewChild(d.topId,1,"Y","Attention",!1,"yellow.gif");
d.addNewChild(d.topId,2,"R","Erreur",!1,"red.gif");d.renderAsContextMenu();c.setSubContext(d,4,0);c.enableAutoHeight(!0);c.init();_44(c);c.csv.row=String.fromCharCode(3);c.csv.cell=String.fromCharCode(2);c.enableCSVAutoID(!1);c.stopFastOperations();_43(a,!1);c.attachEvent("onEditCell",function(a,b,d,h,k){if(_55(b)&&_55(f))if(0==a){if(b!=f||_47._77()!=c.cells(f,0).getValue())return!1}else 2==a&&(e=!0);else return!1;return!0});_47._13(!1)};
