var Cession;
(function(){var a=-1,b="",c=0,d=0,e="192.168.1.167",h=8E3,f="",l=!1,m=0,k="",q=[],p={};Cession=function(){};Cession.prototype._64=function(){return a};Cession.prototype._23=function(b){a=b};Cession.prototype._67=function(){return c};Cession.prototype._26=function(a){c=a};Cession.prototype._59=function(){return b};Cession.prototype._20=function(a){b=a};Cession.prototype._62=function(){return d};Cession.prototype._22=function(a){d=a};Cession.prototype._54=function(){return e};
Cession.prototype._16=function(a){e=a};Cession.prototype._53=function(){return h};Cession.prototype._15=function(a){h=a};Cession.prototype._52=function(){return f};Cession.prototype._14=function(a){f=a};Cession.prototype._61=function(){return m};Cession.prototype._21=function(a){m=a};Cession.prototype._49=function(){return k};Cession.prototype._12=function(a){k=a};Cession.prototype._48=function(){return l};Cession.prototype._11=
function(a){l=a};Cession.prototype._74=function(){return q};Cession.prototype._29=function(a){q=a};Cession.prototype._91=function(a){q.push(a)};Cession.prototype._87=function(){q=[];q.push([0,"IdUser_",a])};Cession.prototype._79=function(a){for(var b=q.length-1,d=!0;0<=b&&d;)q[b][0]>=a?(q.pop(),b--):d=!1};Cession.prototype._57=function(){return p};Cession.prototype._19=function(a){p=a};Cession.prototype._68=function(){return"../imgs/"};Cession.prototype._63=
function(){return"../codebase/imgs/"}})();var _39=new Cession,_43;
window.onload=function(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()},!1);window.applicationCache.addEventListener("obsolete",function(a){window.applicationCache.update()},!1);dhtmlx.image_path="codebase/imgs/";_43=new dhtmlXLayoutObject({parent:document.body,pattern:"4I",skin:"dhx_skyblue"});var a=_43.cells("a");a.setText("Entete");a.setHeight("120");a.hideHeader();a.fixSize(0,1);var b=a.attachLayout("2E"),
a=b.cells("a");a.setText("Logo");a.setHeight("70");a.hideHeader();a.fixSize(0,1);a.attachHTMLString('<div id="MyCssGris" <span style="color:#F1F5F8;font-family:Segoe UI;font-size:52px;text-align:center;"><strong>Web<img src="../imgs/about.gif" />Report</strong></span></div>');var c=b.cells("b");c.hideHeader();c.fixSize(0,1);c.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:Segoe UI;font-size:15px;text-align:center;z-index:20;"></span></div>');c.setHeight("30");b=_43.cells("b");b.setText("Menu");
b.setWidth("220");b.fixSize(1,0);var d=b.attachTree();d.setSkin("dhx_skyblue");d.setImagePath("../codebase/imgs/dhxtree_skyblue/");var e=_43.cells("c");e.setText("Etat");e.hideHeader();var h=_43.cells("d");h.hideHeader();h.fixSize(0,1);h.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:Segoe UI;font-size:15px;text-align:center;z-index:20;">Copyright \u00a9 2014 by NtSoft &nbsp;&nbsp; &#0149;&nbsp;&nbsp;All Rights reserved  &nbsp;&nbsp; &#0149;&nbsp;&nbsp; <a href="#" style="color:white">mail: support@nt-soft.ma</a></span></div>');
h.setHeight("25");_43.attachEvent("onResizeFinish",function(){c.setHeight("30");h.setHeight("25")});b.collapse();b.hideArrow();d.enableHighlighting(!0);d.attachEvent("onSelect",function(a){if(a&&a.startsWith("M")&&null!=e&&0<_39._64()){for(;0<_39._62();)e.unloadView("Page"+_39._62()),_39._22(_39._62()-1);var b='<div id="MyCssColor" <span style="color:#ffffff;font-family:Segoe UI;font-size:25px;text-align:center;z-index:20;">'+d.getItemText(a)+
"</span></div>";c.attachHTMLString(b);_39._87();e.showView("def");b=a.substring(1,2);a=parseInt(a.substring(2));0<a?"A"==b||"B"==b?_8(e,b,a,1):"C"==b||"D"==b?_9(e,b,a,1):"E"==b||"F"==b?_10(e,b,a,1):"G"==b?_40(a,LibIdent,rId):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."}):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."})}});e.hideHeader();_39._19(e);_7(e,
d,a,b)};window.onunload=function(){if(null!=_39._57()){var a=_39._57().getAttachedToolbar();a&&(_39._57().detachToolbar(),a.unload())}};function _30(a,b,c){a=b.split(String.fromCharCode(199));for(b=0;b<a.length;b++){var d=a[b].split(String.fromCharCode(198));0==d[1]&&""!=d[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:d[4]});"LOGIN"==d[2]&&"PROCEDURE"==d[3]&&1<=d[5].length?(d=_6(d[5]),_39._23(_51(d,"IdUser_")),_39._20(_51(d,"LibUser_")),_39._26(_51(d,"IdEcran_"))):"MENU"==d[2]&&"SELECT"==d[3]&&10<=d[5].length&&(d=_83(d[5]),c[0].deleteChildItems(0),c[0].loadCSVString(d),
c[0].openAllItems(0))}c[1]&&c[1].hide&&(c[1].hide(),c[1].unload(),c[1]=null);if(c[2]&&c[2].showView){for(c[2].detachObject(!0);0<_39._62();)c[2].unloadView("Page"+_39._62()),_39._22(_39._62()-1);c[2].showView("def")}_39._87();c[0].selectItem("G1");c[4]&&c[4].isCollapsed&&c[4].isCollapsed()&&(c[4].expand(),c[4].showArrow());c[5]&&c[5].unload}
function _7(a,b,c,d){var e={login:"Votre login personnel",pwd:"Votre Mot de Passe Confidentiel."};_39._22(_39._62()+1);a.showView("Page"+_39._62());createDiv("MyContainer");createClass("#MyContainer","position:absolute;left: 50%;top: 50%;width: 350px; height: 280px; margin-left: -175px; margin-top: -140px;");applyClass("#MyContainer","MyContainer",!1);a.attachObject("MyContainer");var h=new dhtmlXForm("MyContainer",[{type:"settings",position:"label-top",
labelWidth:"150",inputWidth:"280"},{type:"fieldset",label:"<span style='color : white;font-size:18px '>Bienvenue</span>",width:320,offsetLeft:10,offsetTop:10,list:[{type:"block",list:[{type:"label",name:"Titre",label:"<img src='../imgs/about.gif' /><span style='color : white;font-size:18px '> NafysWeb</span>"}]},{type:"input",name:"login",label:"Login",value:"",tooltip:"Login",required:!0},{type:"password",name:"pwd",label:"Mot de Passe",value:"",required:!0},{type:"button",name:"proceed",value:"Valider",width:"120",offsetLeft:"50"}]}]);h.setFontSize("17px");var f=new dhtmlXPopup({form:h,id:["login",
"pwd"]});h.attachEvent("onFocus",function(a){f.attachHTML("<div style='margin: 5px 10px;'>"+e[a]+"</div>");f.show(a)});h.attachEvent("onBlur",function(a){f&&f.hide&&f.hide()});h.attachEvent("onButtonClick",function(e){if("proceed"==e){e=h.getItemValue("login");var m=h.getItemValue("pwd");e=_33(_39._54(),e,m,_39._53(),0);_78("XMLZ",e,_30,null,[b,f,a,c,d,h],!1)}})};function _10(a,b,c,d){function e(){_39._79(d);f&&f.forEachItem(function(a){var b="",c=f.getItemType(a);"calendar"==c?(c=f.getItemValue(a),_46(c)&&(b=c.toString("dd/MM/yyyy")),"30/12/1899"==b&&(b=""),_39._91([d,a,b])):"input"==c?(b=f.getItemValue(a),_39._91([d,a,b])):"checkbox"==c&&(b=f.getItemValue(a),_39._91([d,a,b]))})}var h,f,l=0,m=0,k="",q,p;_39._79(d);_35(a,!0);var v=_92(null,1,"GRIDEF","WRDIAG","WRPSGRIDEF"),
v=_90(v,1,0,"IdEcran_",c),v=_89(v,1,0,_39._74()),g=_1(v),v=null;_78("XMLZ",g,function(c,g,n){if(_46(n)&&0<_39._64()){c=g.split(String.fromCharCode(199));g=null;for(g=0;g<c.length;g++)if(n=c[g].split(String.fromCharCode(198)),0==n[1]&&""!=n[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:n[4]}),"GRIDEF"==n[2]&&"WRDIAG"==n[3]&&1<=n[5].length){var r=_6(n[5]);n=_51(r,"fForm_");l=parseInt(_51(r,"fWinHeight_"));m=parseInt(_51(r,
"fWinWidth_"));k=_51(r,"fDblClick_");r=null;0==m&&(m=2*a.getWidth()/3);0==l&&(l=2*a.getHeight()/3);if("E"==b)var A=r=10;else s.setDimension(m+100,l+100),s.centerOnScreen(),A=r=50;n=n.replace("NtsOffsetLeft",r);n=n.replace("NtsOffsetTop",A);var v;eval("v="+n);"E"==b?(createDiv("MyContainer"),n="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;",n=n.replace("wwpx",m+"px"),n=n.replace("hhpx",l+"px"),n=n.replace("llpx",Math.round(m/2)+"px"),
n=n.replace("ttpx",Math.round(l/2)+"px"),createClass("#MyContainer",n),applyClass("#MyContainer","MyContainer",!1),a.attachObject("MyContainer"),f=new dhtmlXForm("MyContainer"),f.setFontSize("17px")):f=s.attachForm();q.form=f;f.enableLiveValidation(!0);f.setFontSize("17px");f.loadStruct(v);n=v=null;f.forEachItem(function(a){var b="",b=null,b=f.getItemType(a),c=f.getUserData(a,"Key"),e=f.getUserData(a,"Sql");_46(c)&&_46(e)&&q.id.push(a);if("calendar"==b)f.setCalendarDateFormat(a,"%d/%m/%Y",
"%d/%m/%Y"),b=f.getInput(a),b.style.textAlign="center",b=f.getItemValue(a),_39._91([d,a,b]);else if("input"==b){b=f.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";b=f.getItemValue(a);_39._91([d,a,b])}else"checkbox"==b&&(b=f.getItemValue(a),_39._91([d,a,b]),"0"==b||"N"==b?f.uncheckItem(a):f.checkItem(a))});f.attachEvent("onKeyUp",function(b,c,d){if(9!=c.keyCode&&0<=q.id.indexOf(d)){b=f.getUserData(d,"Key");
var g=f.getUserData(d,"Sql");c=String.fromCharCode(c.keyCode);e();_31(f,a,p,b,d,b,d,g,c,350)}});p=new dhtmlXPopup(q);""!=k&&f.attachEvent("onButtonClick",function(c,f){_46(h)&&(h.unload(),h=null);if("BtOui"==c){e();var g=k.substring(0,1),l=parseInt(k.substring(1));0<l&&("F"==b&&_46(s)&&(_46(p)&&(p.unload(),q=p=null),s.close()),"A"==g||"B"==g?_8(a,g,l,d+1):"C"==g||"D"==g?_9(a,g,l,d+1):"E"==g||"F"==g?_10(a,g,l,d+1):"G"==g&&_40(l,"",""))}else"BtNon"==
c&&("E"==b?(_46(p)&&(p.unload(),q=p=null),a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),g=_39._62(),0==g?(a.showView("def"),_39._87()):(a.showView("Page"+g),_39._79(d))):"F"==b&&_46(s)&&(_46(p)&&(p.unload(),q=p=null),s.close(),_39._79(d)))})}else if(!("GRIDEF"==n[2]&&"DATA"==n[3]&&10<=n[5].length)&&"GRIDEF"==n[2]&&"TOOLS"==n[3]&&10<=n[5].length)for(n=n[5].split(String.fromCharCode(197)),
g=0;g<n.length;g++)r=n[g].split(String.fromCharCode(196)),"A"==r[2]?u.addButton("A"+g,g,r[1],r[5],r[6]):"B"==r[2]?u.addButton("B"+g,g,r[1],r[5],r[6]):"C"==r[2]?u.addText("C"+g,g,r[1]):"D"==r[2]?u.addSeparator("D"+g,g):u.addButton("E"+r[4]+r[3],g,r[1],r[5],r[6]);c=null;_35(a,!1)}},null,[a],!0);a.setText("Liste");if("E"==b){_39._22(_39._62()+1);a.showView("Page"+_39._62());var u=a.attachToolbar()}else{var v=_39._62(),s=_43.dhxWins.createWindow("myWind"+
v,100,100,400,400);s.centerOnScreen();s.setModal(!0);s.denyPark();s.setText("Web@Report");u=s.attachToolbar()}q={form:null,id:[]};u.setIconsPath(_39._68());u.attachEvent("onClick",function(f){_46(h)&&(h.unload(),h=null);var g=f.substring(0,1);"A"==g?(e(),h=_42(a,c,"","")):"B"==g&&"E"==b?(_46(p)&&(p.unload(),q=p=null),a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),f=_39._62(),0==f?(a.showView("def"),_39._87()):
(a.showView("Page"+f),_39._79(d))):"B"==g&&"F"==b?_46(s)&&(_46(p)&&(p.unload(),q=p=null),s.close(),_39._79(d)):"E"==g&&(g=f.substring(1,2),f=parseInt(f.substring(2)),0<f&&(e(),"F"==b&&_46(s)&&(_46(p)&&(p.unload(),q=p=null),s.close()),"A"==g||"B"==g?_8(a,g,f,d+1):"C"==g||"D"==g?_9(a,g,f,d+1):"E"==g||"F"==g?_10(a,g,f,d+1):"G"==g&&_40(f,"","")))});_39._11(!1)};function _9(a,b,c,d){var e,h,f=0,l=0;_39._79(d);_35(a,!0);var m=_92(null,1,"GRIDCD","WRFORM","WRPSGRIDCD"),m=_90(m,1,0,"IdEcran_",c),m=_89(m,1,0,_39._74()),k=_1(m),m=null;_78("XMLZ",k,function(c,g,e){if(_46(e)&&0<_39._64()){c=g.split(String.fromCharCode(199));g=null;for(g=0;g<c.length;g++)if(e=c[g].split(String.fromCharCode(198)),0==e[1]&&""!=e[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:e[4]}),
"GRIDCD"==e[2]&&"WRFORM"==e[3]&&1<=e[5].length){var k=_6(e[5]);e=_51(k,"fForm_");f=parseInt(_51(k,"fWinHeight_"));l=parseInt(_51(k,"fWinWidth_"));k=null;0==l&&(l=2*a.getWidth()/3);0==f&&(f=2*a.getHeight()/3);if("C"==b)var m=10,y=10;else y=m=50;e=e.replace("NtsOffsetLeft",m);e=e.replace("NtsOffsetTop",y);var n;eval("n="+e);"C"==b?(createDiv("MyContainer"),e="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;",e=e.replace("wwpx",
l+"px"),e=e.replace("hhpx",f+"px"),e=e.replace("llpx",Math.round(l/2)+"px"),e=e.replace("ttpx",Math.round(f/2)+"px"),createClass("#MyContainer",e),applyClass("#MyContainer","MyContainer",!1),a.attachObject("MyContainer"),h=new dhtmlXForm("MyContainer"),h.setFontSize("17px")):(p.detachObject(!0),h=p.attachForm(),p.setDimension(l+100,f+100),p.setText("Web@Report"),p.centerOnScreen(),p.setModal(!0),p.denyPark(),p.button("close").enable());h.enableLiveValidation(!0);h.setFontSize("17px");h.loadStruct(n);
e=n=null}else if("GRIDCD"==e[2]&&"DATA"==e[3]&&10<=e[5].length)k=_6(e[5]),h.forEachItem(function(a){var b="",b=null,b=h.getItemType(a);if("calendar"==b)h.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=h.getInput(a),b.style.textAlign="center",(b=_51(k,a))&&h.setItemValue(a,b),_39._91([d,a,b]);else if("input"==b){b=h.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";(b=_51(k,a))&&h.setItemValue(a,b);_39._91([d,
a,b])}else"checkbox"==b&&(b=_51(k,a),"0"==b||"N"==b?h.uncheckItem(a):h.checkItem(a),_39._91([d,a,b]))}),k=null;else if("GRIDCD"==e[2]&&"TOOLS"==e[3]&&10<=e[5].length)for(e=e[5].split(String.fromCharCode(197)),g=0;g<e.length;g++)m=e[g].split(String.fromCharCode(196)),"A"==m[2]?q.addButton("A"+g,g,m[1],m[5],m[6]):"B"==m[2]?q.addButton("B"+g,g,m[1],m[5],m[6]):"C"==m[2]?q.addText("C"+g,g,m[1]):"D"==m[2]?q.addSeparator("D"+g,g):q.addButton("E"+m[4]+m[3],g,m[1],m[5],m[6]);c=null;_35(a,
!1)}},null,[a],!0);a.setText("Liste");if("C"==b){_39._22(_39._62()+1);a.showView("Page"+_39._62());var q=a.attachToolbar()}else{var m=_39._62(),p=_43.dhxWins.createWindow("myWind"+m,20,30,400,280),q=p.attachToolbar();p.setText("Web@Report : En cours ... ");p.centerOnScreen();p.setModal(!0);p.denyPark();p.button("close").disable();p.attachChart({view:"pie",value:"#sales#",color:"#color#"}).parse([{sales:"10",month:"3",color:"#ee9e36"},{sales:"10",
month:"4",color:"#eeea36"},{sales:"10",month:"5",color:"#a9ee36"},{sales:"10",month:"6",color:"#36d3ee"},{sales:"10",month:"7",color:"#367fee"},{sales:"10",month:"8",color:"#9b36ee"}],"json")}q.setIconsPath(_39._68());q.attachEvent("onClick",function(f){_46(e)&&(e.unload(),e=null);var g=f.substring(0,1);"A"==g?e=_42(a,c,"",""):"B"==g&&"C"==b?(a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),f=_39._62(),0==f?(a.showView("def"),
_39._87()):(a.showView("Page"+f),_39._79(d))):"B"==g&&"D"==b?_46(p)&&(p.close(),_39._79(d)):"E"==g&&(g=f.substring(1,2),f=parseInt(f.substring(2)),0<f&&("D"==b&&_46(p)&&p.close(),"A"==g||"B"==g?_8(a,g,f,d+1):"C"==g||"D"==g?_9(a,g,f,d+1):"E"==g||"F"==g?_10(a,g,f,d+1):"G"==g&&_40(f,"","")))});_39._11(!1)};function _8(a,b,c,d){function e(b,c,d){k.startFastOperations();k.clearAll();_46(c)&&k.loadCSVString(c);k.stopFastOperations();_35(a,!1)}var h=[],f=[],l=[],m,k,q=null,p="",v="",g=0,u=0;_35(a,!0);var s=_92(null,1,"GRIDAB","WRGRID","WRPSGRIDAB"),s=_90(s,1,0,"IdEcran_",c),s=_89(s,1,0,_39._74()),z=_1(s),s=null;_78("XMLZ",z,function(r,s,z){if(_46(z)&&0<_39._64()){z=s.split(String.fromCharCode(199));s=null;
for(r=0;r<z.length;r++){var t=z[r].split(String.fromCharCode(198));0==t[1]&&""!=t[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:t[4]});if("GRIDAB"==t[2]&&"WRGRID"==t[3]&&1<=t[5].length){var t=_6(t[5]),x=_51(t,"gHeader_"),w=_51(t,"gFilter_"),D=_51(t,"gTypes_"),E=_51(t,"gColAlig_"),F=_51(t,"gColSort_"),B=_51(t,"gColType_"),G=_51(t,"gColWidth_");q=_51(t,"gCmdeSQL_");var H=_51(t,"gColVars_");p=_51(t,"gLibIdent_");v=_51(t,"gDblClick_");g=parseInt(_51(t,
"gWinHeight"));u=parseInt(_51(t,"gWinWidth"));var C="O"==_51(t,"gRecSrv_");f=B.split(",");l=C?H.split(","):[];B=t=null;k.startFastOperations();k.setHeader(x.split(","));""!=w&&k.attachHeader(w);k.setColTypes(D);k.setColAlign(E);k.setColSorting(F);k.enableValidation(!0,!1);k.setInitWidths(G);k.init();k.csv.row=String.fromCharCode(197);k.csv.cell=String.fromCharCode(196);k.enableCSVAutoID(!1);k.clearAll();k.stopFastOperations()}else if("GRIDAB"==t[2]&&"DATA"==t[3]&&10<=t[5].length)s=t[5];else if("GRIDAB"==
t[2]&&"TOOLS"==t[3]&&10<=t[5].length)for(t=t[5].split(String.fromCharCode(197)),x=0;x<t.length;x++)w=t[x].split(String.fromCharCode(196)),"A"==w[2]?y.addButton("A"+x,x,w[1],w[5],w[6]):"B"==w[2]?y.addButton("B"+x,x,w[1],w[5],w[6]):"C"==w[2]?y.addText("C"+x,x,w[1]):"D"==w[2]?y.addSeparator("D"+x,x):y.addButton("E"+w[4]+w[3],x,w[1],w[5],w[6])}z=t=null;for(r=0;r<f.length;r++)z=parseInt(f[r].substring(1)),2==z?k.setNumberFormat("0,000.00",r,"."," "):3==z&&k.setNumberFormat("0,000.00%",r,"."," ");k.startFastOperations();
k.loadCSVString(s);k.stopFastOperations();s=null;"B"==b&&_46(n)&&(0==u&&(u=2*a.getWidth()/3),0==g&&(g=2*a.getHeight()/3),n.setDimension(u,g),n.centerOnScreen());""!=v&&k.attachEvent("onRowDblClicked",function(c,f){_46(m)&&(m.unload(),m=null);if(null!=c){_39._79(d);_39._91([d,p,c]);for(var e=0;e<l.length;e++){var g=l[e],h=k.cells(c,e).getValue();_39._91([d,g,h])}}e=v.substring(0,1);g=parseInt(v.substring(1));0<g&&("B"==b&&_46(n)&&n.close(),
"A"==e||"B"==e?_8(a,e,g,d+1):"C"==e||"D"==e?_9(a,e,g,d+1):"E"==e||"F"==e?_10(a,e,g,d+1):"G"==e&&_40(g,p,c))});C&&(k.attachEvent("onFilterEnd",function(b){_46(m)&&(m.unload(),m=null);if(25>k.getRowsNum()){_35(a,!0);_39._79(d);for(var g=_92(null,1,"SQL","SELECT",q),g=_90(g,1,0,"IdEcran_",c),p=!0,n=0;n<b.length;n++){var r=b[n][1],t=parseInt(f[r].substring(1));if(4==t||5==t)p=p&&(""==h[n]||_45(h[n]));g=_90(g,1,0,l[r],h[n])}p&&(g=
_89(g,1,0,_39._74()),b=_1(g),_78("XMLA",b,e,null,[a],!1))}}),k.attachEvent("onFilterStart",function(a,b){h=b;for(var c=!0,d=0;d<a.length;d++){var e=parseInt(f[a[d]].substring(1));if(4==e||5==e)c=c&&(""==h[d]||_45(h[d]))}return c}));_35(a,!1)}},null,[a],!0);a.setText("Liste");if("A"==b){_39._22(_39._62()+1);a.showView("Page"+_39._62());var y=a.attachToolbar();k=a.attachGrid()}else{var s=_39._62(),n=_43.dhxWins.createWindow("myWind"+
s,100,100,2*a.getWidth()/3,2*a.getHeight()/3);n.centerOnScreen();n.setModal(!0);n.denyPark();n.setText("Web@Report");k=n.attachGrid();y=n.attachToolbar()}y.setIconsPath(_39._68());y.attachEvent("onClick",function(f){_46(m)&&(m.unload(),m=null);var e=f.substring(0,1);if("A"==e){if(_39._79(d),f=k.getSelectedRowId(),null!=f){_39._91([d,p,f]);for(var g=0;g<l.length;g++){var h=l[g],q=k.cells(f,g).getValue();_39._91([d,h,q])}m=_42(a,c,p,
f)}}else if("B"==e&&"A"==b)a.unloadView("Page"+_39._62()),_39._22(_39._62()-1),e=_39._62(),0==e?(a.showView("def"),_39._87()):(a.showView("Page"+e),_39._79(d));else if("B"==e&&"B"==b)_46(n)&&(n.close(),_39._79(d));else if("E"==e){var e=f.substring(1,2),s=parseInt(f.substring(2));_39._79(d);f=k.getSelectedRowId();if(null!=f)for(_39._91([d,p,f]),g=0;g<l.length;g++)h=l[g],q=k.cells(f,
g).getValue(),_39._91([d,h,q]);0<s&&("B"==b&&_46(n)&&n.close(),"A"==e||"B"==e?_8(a,e,s,d+1):"C"==e||"D"==e?_9(a,e,s,d+1):"E"==e||"F"==e?_10(a,e,s,d+1):"G"==e&&_40(s,p,rId))}});k.startFastOperations();k.setIconsPath(_39._68());k.setImagePath(_39._63());k.enableValidation(!0,!1);k.enableDistributedParsing(!0,10,300);k.setDateFormat("%d/m/Y");k.i18n.decimal_separator=".";k.i18n.group_separator=" ";k.enableCSVAutoID(!1);k.stopFastOperations();
_39._11(!1);k.attachEvent("onRowSelect",function(a,b){_46(m)&&(m.unload(),m=null)})};"undefined"===typeof Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});function createDiv(a){var b=document.getElementById(a);b?(b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)"):(b=document.createElement("div"),b.id=a,b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)",document.body.appendChild(b))}
function createClass(a,b){var c=document.createElement("style");c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);(c.sheet||{}).insertRule?c.sheet.insertRule(a+"{"+b+"}",0):(c.styleSheet||c.sheet).addRule(a,b)}function applyClass(a,b,c){"string"==typeof b.valueOf()&&(b=document.getElementById(b));b&&(b.className=c?b.className.replace(new RegExp("\\b"+a+"\\b","g"),""):b.className+" "+a)}
function _38(a){function b(a,b,c){if(_46(c)&&0<_39._64()){var d=a=_39._66();b=b.split(String.fromCharCode(199));for(var m=0;m<b.length;m++){var k=b[m].split(String.fromCharCode(198));0==k[1]&&""!=k[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:k[4]});"PUBIDT"==k[2]&&"PROCEDURE"==k[3]&&1<=k[5].length?(d=_6(k[5]),d=_51(d,"IdPub_"),d=parseInt(d),0<d&&_39._25(d)):"PUBDET"==k[2]&&"BLOB"==k[3]&&10<=k[5].length&&a!=d&&c[0].attachHTMLString(k[5])}}else _37()}
if(0>=_39._64()||!_46(a))_37();else{var c=_92(null,1,"PUBIDT","PROCEDURE","WRPsPub"),c=_90(c,1,0,"IdUser_",_39._64()),c=_90(c,1,0,"IdPub_",_39._66()),c=_92(c,2,"PUBDET","BLOB","Select * From WRfnPub(:IdPub_)"),c=_90(c,2,1,"IdPub_",0),d=_1(c),c=null;_78("XMLZ",d,b,null,[a],!1)}}function _37(){var a=_39._56();_46(a)&&clearInterval(_39._56());_39._18(null)}var DEBUG=!1;
if(!DEBUG){window.console||(window.console={});for(var methods="log debug warn info dir dirxml trace profile".split(" "),i=0;i<methods.length;i++)console[methods[i]]=function(){}}function _2(a,b,c,d,e,h){a()?window.setTimeout(_2,h,a,b,c,d,e,h):b(c,d,e)}function _36(a){(window.dhx4.isIPad||window.dhx4.isChrome||window.dhx4.isOpera||window.dhx4.isKHTML||window.dhx4.isFF)&&a.enableEditEvents(!0,!1,!1)}
function _75(a){return 1==a?"doc":2==a?"xls":3==a?"rtf":4==a?"xls":5==a?"pdf":6==a||7==a?"jpg":8==a?"zip":9==a?"rar":"pdf"}function _76(a){return"doc"==a?1:"xls"==a?2:"rtf"==a?3:"pdf"==a?5:"jpg"==a?6:"zip"==a?8:"rar"==a?9:"txt"==a?3:5}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});String.prototype.formatedfloat||(String.prototype.formatedfloat=function(){return parseFloat(this.replace(",",".").replace(" ",""))});
"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return this.slice(0,a.length)==a});"function"!=typeof Number.prototype.toMoney&&(Number.prototype.toMoney=function(a,b,c){var d=this;a=isNaN(a)?2:Math.abs(a);b=b||".";c="undefined"===typeof c?" ":c;var e=0>d?"-":"",h=parseInt(d=Math.abs(d).toFixed(a))+"",f=3<(f=h.length)?f%3:0;return e+(f?h.substr(0,f)+c:"")+h.substr(f).replace(/(\d{3})(?=\d)/g,"$1"+c)+(a?b+Math.abs(d-h).toFixed(a).slice(2):"")});
function _46(a){return"undefined"!=typeof a&&null!=a&&""!=a}function _70(a){return a.substr((~-a.lastIndexOf(".")>>>0)+2)}function _82(a,b){var c=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()),d=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate());return Math.floor((d-c)/864E5)}
function _84(a){var b=String.fromCharCode(197),c=String.fromCharCode(196);a=a.split(b);for(var b=[],d=[],e=-1,h=-1,f=[],l={},m=0;m<a.length;m++){var k=a[m].split(c),l={},h=parseInt(k[3]);e!=h&&(-1!=e&&(l.id=f[0]+"_"+f[3],l.text=f[4],l.item=d,b.push(l),l={},d=[]),e=h,f=k);l.id=k[0];l.text=k[2];d.push(l)}l={};l.id=f[0]+"_"+f[3];l.text=f[4];l.item=d;b.push(l);return"{id:0,  item:"+JSON.stringify(b)+"}"}
function _83(a){var b=String.fromCharCode(197),c=String.fromCharCode(196);a=a.split(b);for(var d=b=-1,e="",h="",f=0;f<a.length;f++){var l=a[f].split(c),d=parseInt(l[4]);b!=d&&(b=d,e="G"+(f+1),h=h+"\n"+e+",0,"+l[5]);h=h+"\nM"+l[1]+l[0]+","+e+","+l[3]}return h}
function _85(a){var b=String.fromCharCode(197),c=String.fromCharCode(196);a=a.split(b);var b=[],d=a[0].split(c);d[0]="value";d[1]="text";for(var e=0;e<a.length;e++){var h={},f=a[e].split(c);h[d[0]]=f[0];h[d[1]]=f[1];b.push(h)}return"{options:"+JSON.stringify(b)+"}"}
var _58=function(){var a;if("undefined"!=typeof window.ActiveXObject)for(var b="Msxml2.DOMDocument.6.0 Msxml2.DOMDocument.5.0 Msxml2.DOMDocument.4.0 Msxml2.DOMDocument.3.0 MSXML2.DOMDocument MSXML.DOMDocument Microsoft.XMLDOM".split(" "),c=0;c<b.length;c++)try{a=new ActiveXObject(b[c]);_58=function(){return new ActiveXObject(b[c])};break}catch(d){}return a};
function _6(a){var b=null;if(window.DOMParser&&!window.ActiveXObject){var c=new DOMParser;try{b=c.parseFromString(a,"text/xml")}catch(d){try{b=_58(),b.async=!1,b.loadXML(a)}catch(e){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}}}else try{b=_58(),b.async=!1,b.loadXML(a)}catch(h){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}return b}
function _1(a){return window.ActiveXObject?a.xml:(new XMLSerializer).serializeToString(a)}function _35(a,b){}
function _92(a,b,c,d,e){_46(a)||(a=_6("<?xml version='1.0' encoding='UTF-16'?><Actions></Actions>"));var h=a.getElementsByTagName("Actions"),f=a.createElement("Action"),l=a.createElement("Type"),m=a.createElement("SQL");d=a.createTextNode(d);e=a.createTextNode(e);m.appendChild(e);l.appendChild(d);f.setAttribute("ID",b);f.setAttribute("Name",c);f.appendChild(l);f.appendChild(m);h[0].appendChild(f);return a}
function _89(a,b,c,d){for(var e=d.length-1,h="",f=0,l=0;l<=e;l++)f=h.search(d[e-l][1]),0>f&&(h=h+";"+d[e-l][1],a=_90(a,b,c,d[e-l][1],d[e-l][2]));return a}function _90(a,b,c,d,e){var h=a.getElementsByTagName("Action"),f=a.createElement("Param"),l=a.createElement("Value");null==e&&(e="");e=a.createTextNode(e);l.appendChild(e);f.setAttribute("Source",c);f.setAttribute("Name",d);f.appendChild(l);for(c=0;c<h.length;c++)h[c].getAttribute("ID")==b&&h[c].appendChild(f);return a}
function _60(a){var b=a.match(/[^\x00-\xff]/g);return a.length+(b?b.length:0)}function _86(a,b){var c=new XMLHttpRequest;"withCredentials"in c?c.open(a,b,!0):"undefined"!=typeof XDomainRequest?(c=new XDomainRequest,c.open(a,b)):c=null;return c}
var _47=function(){var a;try{a=new XMLHttpRequest,_47=function(){return new XMLHttpRequest}}catch(b){for(var c=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,e=c.length;d<e;++d)try{a=new ActiveXObject(c[d]);_47=function(){return new ActiveXObject(c[d])};break}catch(h){}}return a};
function _88(a){var b=a.byteLength;a=new Uint8Array(a);if(8192>b)return String.fromCharCode.apply(null,a);for(var c=0,d="";c<b;)d+=String.fromCharCode.apply(null,a.subarray(c,c+8192)),c+=8192;return d}var _32=function(a,b){try{return a.readAsBinaryString(b),_32=function(a,b){a.readAsBinaryString(b);return 1},1}catch(c){return a.readAsArrayBuffer(b),_32=function(a,b){a.readAsArrayBuffer(b);return 2},2}};
function _78(a,b,c,d,e,h){function f(a,b,c){dhtmlx.alert({title:a,type:b,text:c});d&&d(e)}var l=!1,m=null;h&&_39._11(!0);var k="http://"+_39._54()+":"+_39._53()+"/"+a;if(500<b.length){var q=new JSZip;q.file("Z.ZIP",b,{base64:!1,binary:!0,compression:"DEFLATE"});b=q.generate({type:"blob"})}else b=new Blob([b],{type:"image/png"});m=_47();_46(m)&&(m.ontimeout=function(){f("Nafys","alert-error","Erreur Systeme : TimeOut")},m.onload=function(b){if(4===
m.readyState)if(200===m.status){try{var d=new Uint8Array(this.response,0,4);if(4==d.byteLength&&80==d[0]&&75==d[1]&&3==d[2]&&4==d[3])try{var g=(new JSZip(this.response,{base64:!1})).file("Z.ZIP").asBinary()}catch(k){f("Nafys","alert-error","Erreur : "+k);return}else g=_88(this.response)}catch(q){g=_88(this.response)}"XMLA"==a?(b=g.split(String.fromCharCode(198)),3!=b.length?f("Nafys","alert-error","Donn\u00e9es non lues du serveur"):(l=b[0],_39._14(b[2]),
0!=l&&3>b[1].length?_46(c)&&(h?_2(_39._48,c,this,b[2],e,100):c(this,b[2],e)):0!=l&&3<b[1].length?(_46(c)&&(h?_2(_39._48,c,this,b[2],e,100):c(this,b[2],e)),f("Nafys","alert-warning",b[1])):3<b[1].length?f("Nafys","alert-warning",b[1]):f("Nafys","alert-error","Erreur Systeme"))):(_39._14(g),_46(c)&&(h?_2(_39._48,c,this,g,e,100):c(this,g,e)))}else f("Nafys","alert-error","Donn\u00e9es non lues du serveur")},m.open("POST",
k,!0),m.timeout=3E4,m.responseType="arraybuffer",m.send(b))}
function _77(a,b,c){var d="http://"+_39.getsAdrGed()+":"+_39._53Ged()+"/DOWNLOAD?FileName="+encodeURIComponent(a),e=null,e=_47();_46(e)&&(e.ontimeout=function(){dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Erreur Systeme : TimeOut"})},e.onload=function(d){if(4===e.readyState&&200===e.status){d=new Blob([this.response],{type:"image/png"});var f=new FileReader;f.addEventListener("loadend",function(){var d=(new JSZip(f.result,{base64:!1})).file("Z.ZIP").asBinary();
_46(b)&&b(this,a,d,c)});f.readAsArrayBuffer(d)}},e.open("POST",d,!0),e.timeout=3E4,e.responseType="blob",e.send(null))}function _33(a,b,c,d,e){a=(new Fingerprint({canvas:!0,ie_activex:!0,screen_resolution:!0})).get();d=_92(null,1,"LOGIN","PROCEDURE","WRpsLogin");d=_90(d,1,0,"Login_",b);d=_90(d,1,0,"PassWord_",c);d=_90(d,1,0,"MachineId_",a);d=_92(d,2,"MENU","SELECT","Select * From WRfnListeMenus(:IdUser_)");d=_90(d,2,1,"IdUser_",0);return _1(d)}
function _45(a){var b=/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(a);if(b){a=a.split("/");var c=new Date(+a[2],a[1]-1,+a[0]);"[object Date]"===Object.prototype.toString.call(c)&&(b=!isNaN(c.getTime())&&c.getDate()==a[0]&&c.getMonth()==a[1]-1)}return b}function _3(a,b){"D"==b?a||(a="NULL"):"N"==b?a||(a=0):"S"==b?a||(a=""):"M"==b&&(a||(a=1));return a}function _73(){return Date.today().toString("dd/MM/yyyy")}
function _69(a,b){var c=a.getItemValue(b,!0).toString("dd/MM/yyyy");return"30/12/1899"==c?"":c}function _4(a){return 0==a.length?"&nbsp;":a}function _44(a,b){return null==a?!0:a.match(/^\d+$/)?!0:b&&a.match(/^\d+\.\d+$/)?!0:b&&a.match(/^\d+\,\d+$/)?!0:!1}function _34(a,b,c){b=b.keyCode;var d=String.fromCharCode(b);if(null==b||0==b||8==b||9==b||13==b||27==b||-1<"0123456789".indexOf(d))return!0;c&&"."==d&&a.form.elements[c].focus();return!1}
function _71(a,b){for(var c=b.split(String.fromCharCode(201)),d=0;d<c.length;d++){var e=c[d].split(String.fromCharCode(200));a.put(e[0],e[1])}}
function _27(a,b,c,d){6==a.cells(b,c[0]).getValue()?d?a.setCellExcellType(b,c[1],"ron"):(a.setCellExcellType(b,c[1],"edn"),a.setCellTextStyle(b,c[1],"color:red;border:1px solid gray;")):7==a.cells(b,c[0]).getValue()?d?a.setCellExcellType(b,c[1],"ro"):(a.setCellExcellType(b,c[1],"coro"),a.setCellTextStyle(b,c[1],"color:red;border:1px solid gray;"),d=a.getCustomCombo(b,c[1]),a=a.cells(b,c[2]).getValue(),_71(d,a)):a.setCellExcellType(b,c[1],"ron")}
function _51(a,b){try{var c=a.getElementsByTagName(b)[0].childNodes[0].nodeValue}catch(d){c=""}return c}function _81(a){a=a.split(/\D/);return new Date(Date.UTC(+a[0],--a[1],+a[2],+a[3],+a[4],+a[5],0))}function _80(a,b){b=b.replace("DD",(10>a.getDate()?"0":"")+a.getDate());b=b.replace("MM",(9>a.getMonth()?"0":"")+(a.getMonth()+1));return b=b.replace("YYYY",a.getFullYear())}function _5(a){a=_81(a);return _80(a,"DD/MM/YYYY")}
function _50(a,b){try{var c=a.getElementsByTagName(b)[0].childNodes[0].nodeValue,d=_81(c),c=1900>d.getFullYear()?"":_80(d,"DD/MM/YYYY")}catch(e){c=""}return c}function _13(a,b,c){try{a.getElementsByTagName(b)[0].childNodes[0].nodeValue=c}catch(d){alert("Erreur ==> "+d.message)}return a}
function _31(a,b,c,d,e,h,f,l,m,k,q){function p(a,c,d){g.startFastOperations();g.clearAll();_46(c)&&g.loadCSVString(c);g.stopFastOperations();_35(b,!1)}var v="",g,u=_92(null,1,h,"SELECT",l),u=_90(u,1,0,f,m+"%"),u=_90(u,1,0,"IdUser",_39._64()),u=_89(u,1,0,_39._74()),s=_1(u),u=null;_78("XMLA",s,p,null,[g],!0);_35(b,!0);g=c.attachGrid(k,320);g.startFastOperations();g.setIconsPath(_39._68());g.setImagePath(_39._63());
g.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;background-color:yellow;"]);g.attachHeader("#text_filter");g.setColTypes("ro");g.setColAlign("left");g.setColSorting("str");g.enableValidation(!0,!1);g.enableAutoWidth(!0);g.setInitWidths("300");g.enableDistributedParsing(!0,10,300);g.init();_36(g);g.csv.row=String.fromCharCode(197);g.csv.cell=String.fromCharCode(196);g.enableCSVAutoID(!1);g.clearAll();g.stopFastOperations();_35(b,!1);g.attachEvent("onHeaderClick",
function(b,f){var h=g.getSelectedRowId();h&&(a.setItemValue(d,h),a.setItemValue(e,g.cells(h,0).getValue()),c.hide(),g.clearSelection(),_46(q)&&q())});g.attachEvent("onRowDblClicked",function(b){a.setItemValue(d,b);a.setItemValue(e,g.cells(b,0).getValue());c.hide();g.clearSelection();_46(q)&&q()});g.attachEvent("onFilterEnd",function(a){if(15>=g.getRowsNum()){_35(b,!0);a=_92(null,1,h,"SELECT",l);var c=v[0].trim();a=_90(a,1,0,f,""==c?"%":"%"+c+"%");a=_90(a,1,0,
"IdUser",_39._64());a=_89(a,1,0,_39._74());a=_1(a);_78("XMLA",a,p,null,[g],!1)}});g.attachEvent("onFilterStart",function(a,b){v=b;return!0});c.show(e);g.getFilterElement(0).focus();g.getFilterElement(0).value=m;_39._11(!1)}
function _40(a,b,c){var d=_92(null,1,"FILETEST.PDF","IMPRIME",a);""!=b&&(d=_90(d,1,0,b,c));d=_90(d,1,0,"IdUser",_39._64());d=_89(d,1,0,_39._74());b=_1(d);d=null;_78("XMLA",b,function(a,b,c){_46(c)&&_46(c[0])&&(a="http://"+_39._54()+":"+_39._53()+"/DOWNLOAD?FileName="+encodeURIComponent(b),window.open(a,"_self"))},null,[a],!1)}
function _42(a,b,c,d){function e(b,c,d){f.startFastOperations();f.clearAll();_46(c)&&f.loadCSVString(c);f.stopFastOperations();_35(a,!1)}var h="",f,l="Select TOP 20 IdEtat, Libelle From dbo.WRFnPrint(IdEcran, IdUser) Where Libelle Like :Libelle Order By Libelle",l=l.replace("IdEcran",b),l=l.replace("IdUser",_39._64()),l=l.replace("Identifiant",d);b=_92(null,1,"ETATS","SELECT",l);b=_90(b,1,0,"LIBELLE","%");var m=_1(b);b=null;_78("XMLA",
m,e,null,[f],!0);_35(a,!0);var k=new dhtmlXPopup({mode:"right"});f=k.attachGrid(350,320);f.startFastOperations();f.setIconsPath(_39._68());f.setImagePath(_39._63());f.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;"]);f.attachHeader("#text_filter");f.setColTypes("ro");f.setColAlign("left");f.setColSorting("str");f.enableValidation(!0,!1);f.setInitWidths("*");f.enableDistributedParsing(!0,10,300);f.init();_36(f);f.csv.row=String.fromCharCode(197);
f.csv.cell=String.fromCharCode(196);f.enableCSVAutoID(!1);f.stopFastOperations();_35(a,!1);f.attachEvent("onHeaderClick",function(a,b){var e=f.getSelectedRowId();e&&(k.hide(),f.clearSelection(),_40(e,c,d))});f.attachEvent("onRowDblClicked",function(a){k.hide();f.clearSelection();_40(a,c,d)});f.attachEvent("onFilterEnd",function(b){if(15>=f.getRowsNum()){_35(a,!0);b=_92(null,1,"ETATS","SELECT",l);var c=h[0].trim();b=_90(b,1,0,"LIBELLE",""==c?"%":"%"+c+"%");b=_1(b);
_78("XMLA",b,e,null,[f],!1)}});f.attachEvent("onFilterStart",function(a,b){h=b;return!0});k.show(50,50,350,300);f.getFilterElement(0).focus();_39._11(!1);return k};
