var Cession;
(function(){var a=-1,b="",d=0,c=0,g="41.137.253.198",k=8081,e="",l=!1,m=0,f="http://dhtmlxgrid.appspot.com/export/pdf",u="http://dhtmlxgrid.appspot.com/export/excel",n="E",r="",h=[],B={};Cession=function(){};Cession.prototype._72=function(){return a};Cession.prototype._26=function(c){a=c};Cession.prototype._75=function(){return d};Cession.prototype._29=function(a){d=a};Cession.prototype._67=function(){return b};Cession.prototype._23=function(a){b=a};Cession.prototype._70=
function(){return c};Cession.prototype._25=function(a){c=a};Cession.prototype._62=function(){return g};Cession.prototype._19=function(a){g=a};Cession.prototype._61=function(){return k};Cession.prototype._18=function(a){k=a};Cession.prototype._60=function(){return e};Cession.prototype._17=function(a){e=a};Cession.prototype._69=function(){return m};Cession.prototype._24=function(a){m=a};Cession.prototype._57=function(){return r};
Cession.prototype._15=function(a){r=a};Cession.prototype._54=function(){return l};Cession.prototype._12=function(a){l=a};Cession.prototype._55=function(){return f};Cession.prototype._13=function(a){f=a};Cession.prototype._56=function(){return u};Cession.prototype._14=function(a){u=a};Cession.prototype._82=function(){return n};Cession.prototype._32=function(a){n=a};Cession.prototype._83=function(){return h};Cession.prototype._33=
function(a){h=a};Cession.prototype._107=function(a){h.push(a)};Cession.prototype._101=function(){h=[];h.push([0,"IdUser_",a])};Cession.prototype._91=function(a){for(var c=h.length-1,b=!0;0<=c&&b;)h[c][0]>=a?(h.pop(),c--):b=!1};Cession.prototype._65=function(){return B};Cession.prototype._22=function(a){B=a};Cession.prototype._76=function(){return"../imgs/"};Cession.prototype._71=function(){return"../codebase/imgs/"}})();
var _44=new Cession,_49,_102;
window.onload=function(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()},!1);window.applicationCache.addEventListener("obsolete",function(a){window.applicationCache.update()},!1);dhtmlx.image_path="codebase/imgs/";_49=new dhtmlXLayoutObject({parent:document.body,pattern:"4I",skin:"dhx_skyblue"});var a=_49.cells("a");a.setText("Entete");a.setHeight("120");a.hideHeader();a.fixSize(0,1);var b=a.attachLayout("2E"),
a=b.cells("a");a.setText("Logo");a.setHeight("70");a.hideHeader();a.fixSize(0,1);a.attachHTMLString('<div id="MyCssGris" <span style="color:#F1F5F8;font-family:tahoma;font-size:58px;text-align:center;"><strong>Web@Report</strong></span></div>');_102=b.cells("b");_102.hideHeader();_102.fixSize(0,1);_102.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">Titre Etat</span></div>');_102.setHeight("30");
b=_49.cells("b");b.setText("Menu");b.setWidth("220");b.fixSize(1,0);var d=b.attachTree();d.setSkin("dhx_skyblue");d.setImagePath("../codebase/imgs/dhxtree_skyblue/");var c=_49.cells("c");c.setText("Etat");c.hideHeader();var g=_49.cells("d");g.hideHeader();g.fixSize(0,1);g.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:17px;text-align:center;z-index:20;">Copyright \u00a9 2014 by NtSoft &nbsp;&nbsp; &#0149;&nbsp;&nbsp;All Rights reserved  &nbsp;&nbsp; &#0149;&nbsp;&nbsp; E-Mail: support@nt-soft.ma</span></div>');
g.setHeight("25");_49.attachEvent("onResizeFinish",function(){_102.setHeight("30");g.setHeight("25")});b.collapse();b.hideArrow();d.enableHighlighting(!0);d.attachEvent("onSelect",function(a){if(a&&a.startsWith("M")&&null!=c&&0<_44._72()){for(;0<_44._70();)c.unloadView("Page"+_44._70()),_44._25(_44._70()-1);var b='<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">'+_44._67()+
"  :  "+d.getItemText(a)+"</span></div>";_102.attachHTMLString(b);_44._101();c.showView("def");b=a.substring(1,2);a=parseInt(a.substring(2));0<a?"A"==b||"B"==b?_9(c,b,a,1):"C"==b||"D"==b?_10(c,b,a,1):"E"==b||"F"==b?_11(c,b,a,1):"G"==b?_46(a,LibIdent,rId):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."}):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."})}});c.hideHeader();
_44._22(c);_7(c,d,a,b)};window.onunload=function(){if(null!=_44._65()){var a=_44._65().getAttachedToolbar();a&&(_44._65().detachToolbar(),a.unload())}};function _34(a,b,d){a=b.split(String.fromCharCode(5));for(b=0;b<a.length;b++){var c=a[b].split(String.fromCharCode(4));0==c[1]&&""!=c[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:c[4]});"LOGIN"==c[2]&&"PROCEDURE"==c[3]&&1<=c[5].length?(c=_6(c[5]),_44._26(_59(c,"IdUser_")),_44._23(_59(c,"LibUser_")),_44._29(_59(c,"IdEcran_")),_44._13(_59(c,"UrlPdf_")),_44._14(_59(c,"UrlExcel_")),_44._32(_59(c,
"Auteur_")),c='<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">'+_44._67()+"</span></div>",_102.attachHTMLString(c)):"MENU"==c[2]&&"SELECT"==c[3]&&10<=c[5].length&&(c=_95(c[5]),d[0].deleteChildItems(0),d[0].loadCSVString(c),d[0].openAllItems(0))}d[1]&&d[1].hide&&(d[1].hide(),d[1].unload(),d[1]=null);if(d[2]&&d[2].showView){for(d[2].detachObject(!0);0<_44._70();)d[2].unloadView("Page"+_44._70()),
_44._25(_44._70()-1);d[2].showView("def")}_44._101();d[0].selectItem("G1");d[4]&&d[4].isCollapsed&&d[4].isCollapsed()&&(d[4].expand(),d[4].showArrow());d[5]&&d[5].unload}
function _7(a,b,d,c){var g={login:"Votre login personnel",pwd:"Votre Mot de Passe Confidentiel."};_44._25(_44._70()+1);a.showView("Page"+_44._70());_98("MyContainer");_100("#MyContainer","position:absolute;left: 50%;top: 50%;width: 350px; height: 280px; margin-left: -175px; margin-top: -140px;");_104("#MyContainer","MyContainer",!1);a.attachObject("MyContainer");var k=new dhtmlXForm("MyContainer",[{type:"settings",position:"label-top",
labelWidth:"150",inputWidth:"280"},{type:"fieldset",label:"Bienvenue",width:320,offsetLeft:10,offsetTop:10,list:[{type:"block",list:[{type:"label",name:"Titre",label:"<img src='../imgs/about.gif' />   NafysWeb"}]},{type:"input",name:"login",label:"Login",value:"",tooltip:"Login",required:!0},{type:"password",name:"pwd",label:"Mot de Passe",value:"",required:!0},{type:"button",name:"proceed",value:"Valider",width:"120",offsetLeft:"50"}]}]);k.setFontSize("17px");var e=new dhtmlXPopup({form:k,id:["login",
"pwd"]});k.attachEvent("onFocus",function(a){e.attachHTML("<div style='margin: 5px 10px;'>"+g[a]+"</div>");e.show(a)});k.attachEvent("onBlur",function(a){e&&e.hide&&e.hide()});k.attachEvent("onButtonClick",function(g){if("proceed"==g){g=k.getItemValue("login");var m=k.getItemValue("pwd");g=_38(_44._62(),g,m,_44._61(),0);_89("XMLZ",g,_34,null,[b,e,a,d,c,k],!1)}})};var jsonify=function(a){return function(b){a.setAttribute("onclick","this.__json__ = "+b);a.click();return a.__json__}}(document.createElement("div"));
function _11(a,b,d,c){function g(){_44._91(c);e&&e.forEachItem(function(a){var b="",d=e.getItemType(a);"calendar"==d?(d=e.getItemValue(a),_52(d)&&(b=d.toString("dd/MM/yyyy")),"30/12/1899"==b&&(b=""),_44._107([c,a,b])):"input"==d?(b=e.getItemValue(a),_44._107([c,a,b])):"checkbox"==d&&(b=e.getItemValue(a),_44._107([c,a,b]))})}var k,e,l=0,m=0,f="",u,n,r="MyContainer"+b+"_"+d+"_"+c;_44._91(c);_40(a,!0);var h=_108(null,
1,"GRIDEF","WRDIAG","WRPSGRIDEF"),h=_106(h,1,0,"IdEcran_",d),h=_105(h,1,0,_44._83()),B=_1(h),h=null;_89("XMLZ",B,function(d,h,x){if(_52(x)&&0<_44._72()){d=h.split(String.fromCharCode(5));h=null;for(h=0;h<d.length;h++)if(x=d[h].split(String.fromCharCode(4)),0==x[1]&&""!=x[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:x[4]}),"GRIDEF"==x[2]&&"WRDIAG"==x[3]&&1<=x[5].length){var s=_6(x[5]);x=_59(s,"fForm_");l=parseInt(_59(s,
"fWinHeight_"));m=parseInt(_59(s,"fWinWidth_"));f=_59(s,"fDblClick_");s=null;0==m&&(m=2*a.getWidth()/3);0==l&&(l=2*a.getHeight()/3);if("E"==b)var v=s=10;else s=20,v=10;x=x.replace("NtsOffsetLeft",s);x=x.replace("NtsOffsetTop",v);x=eval(x);_98(r);s="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;overflow:auto;";s=s.replace("wwpx",m+"px");s=s.replace("hhpx",l+"px");s=s.replace("llpx",Math.round(m/2)+"px");s=s.replace("ttpx",Math.round(l/
2)+"px");_100("#"+r,s);_104("#"+r,r,!1);"E"==b?a.attachObject(r):(z.detachObject(!0),z.setDimension(m+100,l+100),z.centerOnScreen(),z.attachObject(r),z.attachEvent("onClose",function(a){_90(r);_90("#"+r);return!0}));e=new dhtmlXForm(r);u.form=e;e.enableLiveValidation(!0);e.setFontSize("17px");e.loadStruct(x);x=null;e.forEachItem(function(a){var b="",b=null,b=e.getItemType(a),d=e.getUserData(a,"Key"),g=e.getUserData(a,"Sql");_52(d)&&_52(g)&&u.id.push(a);if("calendar"==
b)e.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=e.getInput(a),b.style.textAlign="center",b=e.getItemValue(a),_44._107([c,a,b]);else if("input"==b){b=e.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";b=e.getItemValue(a);_44._107([c,a,b])}else"checkbox"==b&&(b=e.getItemValue(a),_44._107([c,a,b]),"0"==b||"N"==b?e.uncheckItem(a):e.checkItem(a))});e.attachEvent("onKeyUp",function(b,c,d){if(9!=c.keyCode&&0<=
u.id.indexOf(d)){b=e.getUserData(d,"Key");var f=e.getUserData(d,"Sql");c=String.fromCharCode(c.keyCode);g();_36(e,a,n,b,d,b,d,f,c,350)}});n=new dhtmlXPopup(u);""!=f&&e.attachEvent("onButtonClick",function(d,e){_52(k)&&(k.unload(),k=null);if("BtOui"==d){g();var h=f.substring(0,1),s=parseInt(f.substring(1));0<s&&("A"==h||"B"==h?("F"==b&&"A"==h&&_52(z)&&(_52(n)&&(n.unload(),u=n=null),z.close()),_9(a,h,s,c+1)):"C"==h||"D"==h?("F"==b&&"C"==h&&_52(z)&&(_52(n)&&
(n.unload(),u=n=null),z.close()),_10(a,h,s,c+1)):"E"==h||"F"==h?("F"==b&&"E"==h&&_52(z)&&(_52(n)&&(n.unload(),u=n=null),z.close()),_11(a,h,s,c+1)):"G"==h&&_46(s,"",""))}else"BtNon"==d&&("E"==b?(_52(n)&&(n.unload(),u=n=null),_90(r),_90("#"+r),a.unloadView("Page"+_44._70()),_44._25(_44._70()-1),h=_44._70(),0==h?(a.showView("def"),_44._101()):(a.showView("Page"+h),_44._91(c))):
"F"==b&&_52(z)&&(_52(n)&&(n.unload(),u=n=null),_44._91(c),z.close()))})}else if(!("GRIDEF"==x[2]&&"DATA"==x[3]&&10<=x[5].length)&&"GRIDEF"==x[2]&&"TOOLS"==x[3]&&10<=x[5].length)for(x=x[5].split(String.fromCharCode(3)),s=0;s<x.length;s++)v=x[s].split(String.fromCharCode(2)),"A"==v[2]?A.addButton("A"+s,s,v[1],v[5],v[6]):"B"==v[2]?A.addButton("B"+s,s,v[1],v[5],v[6]):"C"==v[2]?A.addText("C"+s,s,v[1]):"D"==v[2]?A.addSeparator("D"+s,s):"E"==v[2]?A.addButton("E"+v[4]+v[3],s,v[1],
v[5],v[6]):"F"==v[2]?A.addButton("F"+v[7],s,v[1],v[5],v[6]):"G"==v[2]?A.addButton("G"+v[7],s,v[1],v[5],v[6]):A.addButton("E"+v[4]+v[3],s,v[1],v[5],v[6]);d=null;_40(a,!1)}},null,[a],!0);a.setText("Liste");if("E"==b){_44._25(_44._70()+1);a.showView("Page"+_44._70());var A=a.attachToolbar()}else{var h=_44._70(),z=_49.dhxWins.createWindow("myWind"+h,100,100,400,400);z.centerOnScreen();z.setModal(!0);z.denyPark();z.setText("Web@Report");A=z.attachToolbar()}u=
{form:null,id:[]};A.setIconsPath(_44._76());A.attachEvent("onClick",function(e){_52(k)&&(k.unload(),k=null);var h=e.substring(0,1);"A"==h?(g(),k=_48(a,d,"","")):"B"==h&&"E"==b?(_52(n)&&(n.unload(),u=n=null),_90(r),_90("#"+r),a.unloadView("Page"+_44._70()),_44._25(_44._70()-1),e=_44._70(),0==e?(a.showView("def"),_44._101()):(a.showView("Page"+e),_44._91(c))):"B"==h&&"F"==b?_52(z)&&
(_52(n)&&(n.unload(),u=n=null),_44._91(c),z.close()):"F"==h&&"E"==b?(e=e.substring(1),window.open(e,"_top")):"F"==h&&"F"==b?(e=e.substring(1),z.attachURL(e)):"G"==h?(e=e.substring(1),window.open(e,"_blank")):"E"==h&&(h=e.substring(1,2),e=parseInt(e.substring(2)),0<e&&(g(),"A"==h||"B"==h?("F"==b&&"A"==h&&_52(z)&&(_52(n)&&(n.unload(),u=n=null),z.close()),_9(a,h,e,c+1)):"C"==h||"D"==h?("F"==b&&"C"==h&&_52(z)&&(_52(n)&&(n.unload(),u=n=null),z.close()),
_10(a,h,e,c+1)):"E"==h||"F"==h?("F"==b&&"E"==h&&_52(z)&&(_52(n)&&(n.unload(),u=n=null),z.close()),_11(a,h,e,c+1)):"G"==h&&_46(e,"","")))});_44._12(!1)};function _10(a,b,d,c){var g,k,e=0,l=0,m="MyContainer"+b+"_"+d+"_"+c;_44._91(c);_40(a,!0);var f=_108(null,1,"GRIDCD","WRFORM","WRPSGRIDCD"),f=_106(f,1,0,"IdEcran_",d),f=_105(f,1,0,_44._83()),u=_1(f),f=null;_89("XMLZ",u,function(d,g,f){if(_52(f)&&0<_44._72()){d=g.split(String.fromCharCode(5));g=null;for(g=0;g<d.length;g++)if(f=d[g].split(String.fromCharCode(4)),0==f[1]&&""!=f[4]&&dhtmlx.alert({title:"Web@Report",
type:"alert-error",text:f[4]}),"GRIDCD"==f[2]&&"WRFORM"==f[3]&&1<=f[5].length){var u=_6(f[5]);f=_59(u,"fForm_");e=parseInt(_59(u,"fWinHeight_"));l=parseInt(_59(u,"fWinWidth_"));u=null;0==l&&(l=2*a.getWidth()/3);0==e&&(e=2*a.getHeight()/3);if("C"==b)var w=10,t=10;else w=20,t=10;f=f.replace("NtsOffsetLeft",w);f=f.replace("NtsOffsetTop",t);f=eval(f);_98(m);w="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;overflow:auto;";w=
w.replace("wwpx",l+"px");w=w.replace("hhpx",e+"px");w=w.replace("llpx",Math.round(l/2)+"px");w=w.replace("ttpx",Math.round(e/2)+"px");_100("#"+m,w);_104("#"+m,m,!1);"C"==b?a.attachObject(m):(r.detachObject(!0),r.setDimension(l+100,e+100),r.centerOnScreen(),r.attachObject(m),r.setText("Web@Report"),r.setModal(!0),r.denyPark(),r.button("close").enable(),r.attachEvent("onClose",function(a){_90(m);_90("#"+m);return!0}));k=new dhtmlXForm(m);k.enableLiveValidation(!0);k.setFontSize("17px");
k.loadStruct(f);f=null}else if("GRIDCD"==f[2]&&"DATA"==f[3]&&10<=f[5].length)u=_6(f[5]),k.forEachItem(function(a){var b="",b=null,b=k.getItemType(a);if("calendar"==b)k.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=k.getInput(a),b.style.textAlign="center",(b=_59(u,a))&&k.setItemValue(a,b),_44._107([c,a,b]);else if("input"==b){b=k.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";(b=_59(u,a))&&k.setItemValue(a,b);_44._107([c,
a,b])}else"checkbox"==b&&(b=_59(u,a),"0"==b||"N"==b?k.uncheckItem(a):k.checkItem(a),_44._107([c,a,b]))}),u=null;else if("GRIDCD"==f[2]&&"TOOLS"==f[3]&&10<=f[5].length)for(f=f[5].split(String.fromCharCode(3)),w=0;w<f.length;w++)t=f[w].split(String.fromCharCode(2)),"A"==t[2]?n.addButton("A"+w,w,t[1],t[5],t[6]):"B"==t[2]?n.addButton("B"+w,w,t[1],t[5],t[6]):"C"==t[2]?n.addText("C"+w,w,t[1]):"D"==t[2]?n.addSeparator("D"+w,w):"E"==t[2]?n.addButton("E"+t[4]+t[3],w,t[1],t[5],t[6]):"F"==t[2]?
n.addButton("F"+t[7],w,t[1],t[5],t[6]):"G"==t[2]?n.addButton("G"+t[7],w,t[1],t[5],t[6]):n.addButton("E"+t[4]+t[3],w,t[1],t[5],t[6]);d=null;_40(a,!1)}},null,[a],!0);a.setText("Liste");if("C"==b){_44._25(_44._70()+1);a.showView("Page"+_44._70());var n=a.attachToolbar()}else{var f=_44._70(),r=_49.dhxWins.createWindow("myWind"+f,20,30,50,50),n=r.attachToolbar();r.setText("Web@Report : En cours ... ");r.centerOnScreen();r.denyPark();r.button("close").disable()}n.setIconsPath(_44._76());
n.attachEvent("onClick",function(e){_52(g)&&(g.unload(),g=null);var f=e.substring(0,1);"A"==f?g=_48(a,d,"",""):"B"==f&&"C"==b?(_90(m),_90("#"+m),a.unloadView("Page"+_44._70()),_44._25(_44._70()-1),e=_44._70(),0==e?(a.showView("def"),_44._101()):(a.showView("Page"+e),_44._91(c))):"B"==f&&"D"==b?_52(r)&&(_44._91(c),r.close()):"F"==f&&"C"==b?(e=e.substring(1),window.open(e,"_top")):"F"==
f&&"D"==b?(e=e.substring(1),r.attachURL(e)):"G"==f?(e=e.substring(1),window.open(e,"_blank")):"E"==f&&(f=e.substring(1,2),e=parseInt(e.substring(2)),0<e&&("A"==f||"B"==f?("F"==b&&"A"==f&&_52(r)&&r.close(),_9(a,f,e,c+1)):"C"==f||"D"==f?("F"==b&&"C"==f&&_52(r)&&r.close(),_10(a,f,e,c+1)):"E"==f||"F"==f?("F"==b&&"E"==f&&_52(r)&&r.close(),_11(a,f,e,c+1)):"G"==f&&_46(e,"","")))});_44._12(!1)};function _9(a,b,d,c){function g(b,c,d){f.startFastOperations();f.clearAll();_52(c)&&f.loadCSVString(c);f.stopFastOperations();_40(a,!1)}var k=[],e=[],l=[],m,f,u=null,n="",r="",h=0,B=0;_40(a,!0);var A=_108(null,1,"GRIDAB","WRGRID","WRPSGRIDAB"),A=_106(A,1,0,"IdEcran_",d),A=_105(A,1,0,_44._83()),z=_1(A),A=null;_89("XMLZ",z,function(x,s,v){if(_52(v)&&0<_44._72()){var z=v="",A=s.split(String.fromCharCode(5));
s=null;for(x=0;x<A.length;x++){var p=A[x].split(String.fromCharCode(4));0==p[1]&&""!=p[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:p[4]});if("GRIDAB"==p[2]&&"WRGRID"==p[3]&&1<=p[5].length){var y=_6(p[5]),p=_59(y,"gHeader_"),E=_59(y,"gFilter_"),C=_59(y,"gTypes_"),D=_59(y,"gColAlig_"),H=_59(y,"gColSort_"),F=_59(y,"gColType_"),q=_59(y,"gColWidth_");u=_59(y,"gCmdeSQL_");v=_59(y,"gTotaux_");var z=_59(y,"gFooter_"),I=_59(y,"gColVars_");n=_59(y,
"gLibIdent_");r=_59(y,"gDblClick_");h=parseInt(_59(y,"gWinHeight"));B=parseInt(_59(y,"gWinWidth"));var G="O"==_59(y,"gRecSrv_");e=F.split(",");l=G?I.split(","):[];F=y=null;f.startFastOperations();f.setHeader(p.split(","));""!=E&&f.attachHeader(E);if(0<C.indexOf("imgrw")){y=C.split(",");for(p=0;p<y.length;p++)f.setColumnId(p,y[p]+"_"+p);y=null;C=C.replace("imgro","img");C=C.replace("imgrw","img");f.attachEvent("onRowSelect",function(b,c){_52(m)&&(m.unload(),m=null);if(_52(b)&&
_52(c)&&"img"==f.getColType(c)&&f.getColumnId(c).startsWith("imgrw")){var d=f.cells(b,c).getValue(),d=d.substring(d.lastIndexOf("/")+1,d.lastIndexOf("."));_8(a,b,d)}})}else 0<C.indexOf("imgro")&&(C=C.replace("imgro","img"));f.setColTypes(C);f.setColAlign(D);f.setColSorting(H);f.enableValidation(!0,!1);if(0<q.indexOf("*"))f.setInitWidths(q);else{y=q.split(",");for(p=C=0;p<y.length;p++)C+=parseFloat(y[p]);y=null;99<C&&101>C?f.setInitWidthsP(q):f.setInitWidths(q)}if("O"==v){y=z.split(String.fromCharCode(10));
for(p=0;p<y.length;p++)q=y[p].trim(),5<q.length&&(q=q.split("&&"),f.attachFooter(q[0],q[1]),q=q=null);y=null}f.init();f.csv.row=String.fromCharCode(3);f.csv.cell=String.fromCharCode(2);f.enableCSVAutoID(!1);f.clearAll();f.stopFastOperations()}else if("GRIDAB"==p[2]&&"DATA"==p[3]&&10<=p[5].length)s=p[5];else if("GRIDAB"==p[2]&&"FOOTER"==p[3]&&10<=p[5].length&&"O"==v){y=_6(p[5]);q=_86(z);for(p=0;p<q.length;p++)if(C=document.getElementById(q[p]))if(D=_59(y,q[p]))D=parseFloat(D),C.innerHTML=
D.toMoney();y=q=null}else if("GRIDAB"==p[2]&&"TOOLS"==p[3]&&10<=p[5].length)for(y=p[5].split(String.fromCharCode(3)),p=0;p<y.length;p++)q=y[p].split(String.fromCharCode(2)),"A"==q[2]?w.addButton("A"+p,p,q[1],q[5],q[6]):"B"==q[2]?w.addButton("B"+p,p,q[1],q[5],q[6]):"C"==q[2]?w.addText("C"+p,p,q[1]):"D"==q[2]?w.addSeparator("D"+p,p):"E"==q[2]?w.addButton("E"+q[4]+q[3],p,q[1],q[5],q[6]):"F"==q[2]?w.addButton("F"+q[7],p,q[1],q[5],q[6]):"G"==q[2]?w.addButton("G"+q[7],p,q[1],q[5],q[6]):"P"==q[2]?w.addButton("P"+
p,p,q[1],q[5],q[6]):"X"==q[2]?w.addButton("X"+p,p,q[1],q[5],q[6]):w.addButton("E"+q[4]+q[3],p,q[1],q[5],q[6])}A=p=null;for(x=0;x<e.length;x++)v=parseInt(e[x].substring(1)),2==v?f.setNumberFormat("0,000.00",x,"."," "):3==v&&f.setNumberFormat("0,000.00%",x,"."," ");f.startFastOperations();_52(s)&&f.loadCSVString(s);f.stopFastOperations();s=null;"B"==b&&_52(t)&&(0==B&&(B=2*a.getWidth()/3),0==h&&(h=2*a.getHeight()/3),t.setDimension(B,h),t.centerOnScreen());""!=r&&f.attachEvent("onRowDblClicked",
function(b,d){_52(m)&&(m.unload(),m=null);if(null!=b){_44._91(c);_44._107([c,n,b]);for(var e=0;e<l.length;e++){var g=l[e],h=f.cells(b,e).getValue();_44._107([c,g,h])}}e=r.substring(0,1);g=parseInt(r.substring(1));0<g&&("A"==e||"B"==e?_9(a,e,g,c+1):"C"==e||"D"==e?_10(a,e,g,c+1):"E"==e||"F"==e?_11(a,e,g,c+1):"G"==e&&_46(g,n,b))});G&&(f.attachEvent("onFilterEnd",function(b){_52(m)&&(m.unload(),m=null);if(25>f.getRowsNum()){_40(a,
!0);_44._91(c);for(var h=_108(null,1,"SQL","SELECT",u),h=_106(h,1,0,"IdEcran_",d),n=!0,s=0;s<b.length;s++){var r=b[s][1],p=parseInt(e[r].substring(1));if(4==p||5==p)n=n&&(""==k[s]||_51(k[s]));h=_106(h,1,0,l[r],k[s])}n&&(h=_105(h,1,0,_44._83()),b=_1(h),_89("XMLA",b,g,null,[a],!1))}}),f.attachEvent("onFilterStart",function(a,b){k=b;for(var c=!0,d=0;d<a.length;d++){var f=parseInt(e[a[d]].substring(1));if(4==f||5==f)c=c&&(""==k[d]||_51(k[d]))}return c}));
_40(a,!1)}},null,[a],!0);a.setText("Liste");if("A"==b){_44._25(_44._70()+1);a.showView("Page"+_44._70());var w=a.attachToolbar();f=a.attachGrid()}else{var A=_44._70(),t=_49.dhxWins.createWindow("myWind"+A,100,100,2*a.getWidth()/3,2*a.getHeight()/3);t.centerOnScreen();t.setModal(!0);t.denyPark();t.setText("Web@Report");f=t.attachGrid();w=t.attachToolbar()}w.setIconsPath(_44._76());w.attachEvent("onClick",function(e){_52(m)&&
(m.unload(),m=null);var g=e.substring(0,1);if("A"==g){if(_44._91(c),e=f.getSelectedRowId(),null!=e){_44._107([c,n,e]);for(var h=0;h<l.length;h++){var k=l[h],u=f.cells(e,h).getValue();_44._107([c,k,u])}m=_48(a,d,n,e)}}else if("B"==g&&"A"==b)a.unloadView("Page"+_44._70()),_44._25(_44._70()-1),g=_44._70(),0==g?(a.showView("def"),_44._101()):(a.showView("Page"+g),_44._91(c));else if("B"==g&&
"B"==b)_52(t)&&(_44._91(c),t.close());else if("P"==g)f.toPDF(_44._55());else if("X"==g)f.toPDF(_44._56());else if("F"==g&&"A"==b)g=e.substring(1),window.open(g,"_top");else if("F"==g&&"B"==b)g=e.substring(1),t.attachURL(g);else if("G"==g)g=e.substring(1),window.open(g,"_blank");else if("E"==g){var g=e.substring(1,2),r=parseInt(e.substring(2));_44._91(c);e=f.getSelectedRowId();if(null!=e)for(_44._107([c,n,e]),h=0;h<l.length;h++)k=
l[h],u=f.cells(e,h).getValue(),_44._107([c,k,u]);0<r&&("A"==g||"B"==g?_9(a,g,r,c+1):"C"==g||"D"==g?_10(a,g,r,c+1):"E"==g||"F"==g?_11(a,g,r,c+1):"G"==g&&_46(r,n,e))}});f.startFastOperations();f.setIconsPath(_44._76());f.setImagePath(_44._71());f.enableValidation(!0,!1);f.enableDistributedParsing(!0,10,300);f.setDateFormat("%d/m/Y");f.i18n.decimal_separator=".";f.i18n.group_separator=" ";f.enableCSVAutoID(!1);f.stopFastOperations();
f.attachEvent("onRowSelect",function(a,b){_52(m)&&(m.unload(),m=null)});f.attachEvent("onEditCell",function(a,b,c,d,e){_52(m)&&(m.unload(),m=null);return!1});_44._12(!1)};"undefined"===typeof Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});function _86(a){for(var b=[],d=_87(a,' id="','"');0<d.length;)b.push(d),a=_35(a,d),d=_87(a,' id="','"');return b}function _87(a,b,d){return(a=a.match(b+"(.*?)"+d))&&0<a.length?a[1]:""}function _35(a,b){var d=a.indexOf(b);return-1!=d?a.substr(d+b.length):a}
function _45(a,b){var d=[a];for("string"==typeof b&&(b=[b]);0<b.length;){for(var c=0;c<d.length;c++)var g=d[c].split(b[0]),d=d.slice(0,c).concat(g).concat(d.slice(c+1));b.shift()}return d}function _90(a){(a=document.getElementById(a))&&a.parentNode.removeChild(a)}
function _98(a){var b=document.getElementById(a);b?(b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)"):(b=document.createElement("div"),b.id=a,b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)",document.body.appendChild(b))}function _100(a,b){var d=document.createElement("style");d.type="text/css";document.getElementsByTagName("head")[0].appendChild(d);(d.sheet||{}).insertRule?d.sheet.insertRule(a+"{"+b+"}",0):(d.styleSheet||d.sheet).addRule(a,b)}
function _104(a,b,d){"string"==typeof b.valueOf()&&(b=document.getElementById(b));b&&(b.className=d?b.className.replace(new RegExp("\\b"+a+"\\b","g"),""):b.className+" "+a)}
function _43(a){function b(a,b,c){if(_52(c)&&0<_44._72()){var d=a=_44._74();b=b.split(String.fromCharCode(5));for(var m=0;m<b.length;m++){var f=b[m].split(String.fromCharCode(4));0==f[1]&&""!=f[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:f[4]});"PUBIDT"==f[2]&&"PROCEDURE"==f[3]&&1<=f[5].length?(d=_6(f[5]),d=_59(d,"IdPub_"),d=parseInt(d),0<d&&_44._28(d)):"PUBDET"==f[2]&&"BLOB"==f[3]&&10<=f[5].length&&a!=d&&c[0].attachHTMLString(f[5])}}else _42()}
if(0>=_44._72()||!_52(a))_42();else{var d=_108(null,1,"PUBIDT","PROCEDURE","WRPsPub"),d=_106(d,1,0,"IdUser_",_44._72()),d=_106(d,1,0,"IdPub_",_44._74()),d=_108(d,2,"PUBDET","BLOB","Select * From WRfnPub(:IdPub_)"),d=_106(d,2,1,"IdPub_",0),c=_1(d),d=null;_89("XMLZ",c,b,null,[a],!1)}}function _42(){var a=_44._64();_52(a)&&clearInterval(_44._64());_44._21(null)}var DEBUG=!1;
if(!DEBUG){window.console||(window.console={});for(var methods="log debug warn info dir dirxml trace profile".split(" "),i=0;i<methods.length;i++)console[methods[i]]=function(){}}function _2(a,b,d,c,g,k){a()?window.setTimeout(_2,k,a,b,d,c,g,k):b(d,c,g)}function _41(a){(window.dhx4.isIPad||window.dhx4.isChrome||window.dhx4.isOpera||window.dhx4.isKHTML||window.dhx4.isFF)&&a.enableEditEvents(!0,!1,!1)}
function _84(a){return 1==a?"doc":2==a?"xls":3==a?"rtf":4==a?"xls":5==a?"pdf":6==a||7==a?"jpg":8==a?"zip":9==a?"rar":"pdf"}function _85(a){return"doc"==a?1:"xls"==a?2:"rtf"==a?3:"pdf"==a?5:"jpg"==a?6:"zip"==a?8:"rar"==a?9:"txt"==a?3:5}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});String.prototype.formatedfloat||(String.prototype.formatedfloat=function(){return parseFloat(this.replace(",",".").replace(" ",""))});
"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return this.slice(0,a.length)==a});"function"!=typeof Number.prototype.toMoney&&(Number.prototype.toMoney=function(a,b,d){var c=this;a=isNaN(a)?2:Math.abs(a);b=b||".";d="undefined"===typeof d?" ":d;var g=0>c?"-":"",k=parseInt(c=Math.abs(c).toFixed(a))+"",e=3<(e=k.length)?e%3:0;return g+(e?k.substr(0,e)+d:"")+k.substr(e).replace(/(\d{3})(?=\d)/g,"$1"+d)+(a?b+Math.abs(c-k).toFixed(a).slice(2):"")});
function _52(a){return"undefined"!=typeof a&&null!=a&&""!=a}function _78(a){return a.substr((~-a.lastIndexOf(".")>>>0)+2)}function _94(a,b){var d=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()),c=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate());return Math.floor((c-d)/864E5)}
function _96(a){var b=String.fromCharCode(3),d=String.fromCharCode(2);a=a.split(b);for(var b=[],c=[],g=-1,k=-1,e=[],l={},m=0;m<a.length;m++){var f=a[m].split(d),l={},k=parseInt(f[3]);g!=k&&(-1!=g&&(l.id=e[0]+"_"+e[3],l.text=e[4],l.item=c,b.push(l),l={},c=[]),g=k,e=f);l.id=f[0];l.text=f[2];c.push(l)}l={};l.id=e[0]+"_"+e[3];l.text=e[4];l.item=c;b.push(l);return"{id:0,  item:"+JSON.stringify(b)+"}"}
function _95(a){var b=String.fromCharCode(3),d=String.fromCharCode(2);a=a.split(b);for(var c=b=-1,g="",k="",e=0;e<a.length;e++){var l=a[e].split(d),c=parseInt(l[4]);b!=c&&(b=c,g="G"+(e+1),k=k+"\n"+g+",0,"+l[5]);k=k+"\nM"+l[1]+l[0]+","+g+","+l[3]}return k}
function _97(a){var b=String.fromCharCode(3),d=String.fromCharCode(2);a=a.split(b);var b=[],c=a[0].split(d);c[0]="value";c[1]="text";for(var g=0;g<a.length;g++){var k={},e=a[g].split(d);k[c[0]]=e[0];k[c[1]]=e[1];b.push(k)}return"{options:"+JSON.stringify(b)+"}"}
var _66=function(){var a;if("undefined"!=typeof window.ActiveXObject)for(var b="Msxml2.DOMDocument.6.0 Msxml2.DOMDocument.5.0 Msxml2.DOMDocument.4.0 Msxml2.DOMDocument.3.0 MSXML2.DOMDocument MSXML.DOMDocument Microsoft.XMLDOM".split(" "),d=0;d<b.length;d++)try{a=new ActiveXObject(b[d]);_66=function(){return new ActiveXObject(b[d])};break}catch(c){}return a};
function _6(a){var b=null;if(window.DOMParser&&!window.ActiveXObject){var d=new DOMParser;try{b=d.parseFromString(a,"text/xml")}catch(c){try{b=_66(),b.async=!1,b.loadXML(a)}catch(g){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}}}else try{b=_66(),b.async=!1,b.loadXML(a)}catch(k){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}return b}
function _1(a){return window.ActiveXObject?a.xml:(new XMLSerializer).serializeToString(a)}function _40(a,b){}
function _108(a,b,d,c,g){_52(a)||(a=_6("<?xml version='1.0' encoding='UTF-16'?><Actions></Actions>"));var k=a.getElementsByTagName("Actions"),e=a.createElement("Action"),l=a.createElement("Type"),m=a.createElement("SQL");c=a.createTextNode(c);g=a.createTextNode(g);m.appendChild(g);l.appendChild(c);e.setAttribute("ID",b);e.setAttribute("Name",d);e.appendChild(l);e.appendChild(m);k[0].appendChild(e);return a}
function _105(a,b,d,c){for(var g=c.length-1,k="",e=0,l=0;l<=g;l++)e=k.search(c[g-l][1]),0>e&&(k=k+";"+c[g-l][1],a=_106(a,b,d,c[g-l][1],c[g-l][2]));return a}function _106(a,b,d,c,g){var k=a.getElementsByTagName("Action"),e=a.createElement("Param"),l=a.createElement("Value");null==g&&(g="");g=a.createTextNode(g);l.appendChild(g);e.setAttribute("Source",d);e.setAttribute("Name",c);e.appendChild(l);for(d=0;d<k.length;d++)k[d].getAttribute("ID")==b&&k[d].appendChild(e);return a}
function _68(a){var b=a.match(/[^\x00-\xff]/g);return a.length+(b?b.length:0)}function _99(a,b){var d=new XMLHttpRequest;"withCredentials"in d?d.open(a,b,!0):"undefined"!=typeof XDomainRequest?(d=new XDomainRequest,d.open(a,b)):d=null;return d}
var _53=function(){var a;try{a=new XMLHttpRequest,_53=function(){return new XMLHttpRequest}}catch(b){for(var d=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0,g=d.length;c<g;++c)try{a=new ActiveXObject(d[c]);_53=function(){return new ActiveXObject(d[c])};break}catch(k){}}return a};
function _103(a){var b=a.byteLength;a=new Uint8Array(a);if(8192>b)return String.fromCharCode.apply(null,a);for(var d=0,c="";d<b;)c+=String.fromCharCode.apply(null,a.subarray(d,d+8192)),d+=8192;return c}var _37=function(a,b){try{return a.readAsBinaryString(b),_37=function(a,b){a.readAsBinaryString(b);return 1},1}catch(d){return a.readAsArrayBuffer(b),_37=function(a,b){a.readAsArrayBuffer(b);return 2},2}};
function _89(a,b,d,c,g,k){function e(a,b,d){dhtmlx.alert({title:a,type:b,text:d});c&&c(g)}var l=!1,m=null;k&&_44._12(!0);var f="http://"+_44._62()+":"+_44._61()+"/"+a;if(500<b.length){var u=new JSZip;u.file("Z.ZIP",b,{base64:!1,binary:!0,compression:"DEFLATE"});b=u.generate({type:"blob"})}else b=new Blob([b],{type:"image/png"});m=_53();_52(m)&&(m.ontimeout=function(){e("Nafys","alert-error","Erreur Systeme : TimeOut")},m.onload=function(b){if(4===
m.readyState)if(200===m.status){try{var c=new Uint8Array(this.response,0,4);if(4==c.byteLength&&80==c[0]&&75==c[1]&&3==c[2]&&4==c[3])try{var f=(new JSZip(this.response,{base64:!1})).file("Z.ZIP").asBinary()}catch(u){e("Nafys","alert-error","Erreur : "+u);return}else f=_103(this.response)}catch(A){f=_103(this.response)}"XMLA"==a?(b=f.split(String.fromCharCode(4)),3!=b.length?e("Nafys","alert-error","Donn\u00e9es non lues du serveur"):(l=b[0],_44._17(b[2]),
0!=l&&3>b[1].length?_52(d)&&(k?_2(_44._54,d,this,b[2],g,100):d(this,b[2],g)):0!=l&&3<b[1].length?(_52(d)&&(k?_2(_44._54,d,this,b[2],g,100):d(this,b[2],g)),e("Nafys","alert-warning",b[1])):3<b[1].length?e("Nafys","alert-warning",b[1]):e("Nafys","alert-error","Erreur Systeme"))):(_44._17(f),_52(d)&&(k?_2(_44._54,d,this,f,g,100):d(this,f,g)))}else e("Nafys","alert-error","Donn\u00e9es non lues du serveur")},m.open("POST",
f,!0),m.timeout=3E4,m.responseType="arraybuffer",m.send(b))}
function _88(a,b,d){var c="http://"+_44.getsAdrGed()+":"+_44._61Ged()+"/DOWNLOAD?FileName="+encodeURIComponent(a),g=null,g=_53();_52(g)&&(g.ontimeout=function(){dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Erreur Systeme : TimeOut"})},g.onload=function(c){if(4===g.readyState&&200===g.status){c=new Blob([this.response],{type:"image/png"});var e=new FileReader;e.addEventListener("loadend",function(){var c=(new JSZip(e.result,{base64:!1})).file("Z.ZIP").asBinary();
_52(b)&&b(this,a,c,d)});e.readAsArrayBuffer(c)}},g.open("POST",c,!0),g.timeout=3E4,g.responseType="blob",g.send(null))}function _38(a,b,d,c,g){a=(new Fingerprint({canvas:!0,ie_activex:!0,screen_resolution:!0})).get();c=_108(null,1,"LOGIN","PROCEDURE","WRpsLogin");c=_106(c,1,0,"Login_",b);c=_106(c,1,0,"PassWord_",d);c=_106(c,1,0,"MachineId_",a);c=_108(c,2,"MENU","SELECT","Select * From WRfnListeMenus(:IdUser_)");c=_106(c,2,1,"IdUser_",0);return _1(c)}
function _51(a){var b=/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(a);if(b){a=a.split("/");var d=new Date(+a[2],a[1]-1,+a[0]);"[object Date]"===Object.prototype.toString.call(d)&&(b=!isNaN(d.getTime())&&d.getDate()==a[0]&&d.getMonth()==a[1]-1)}return b}function _3(a,b){"D"==b?a||(a="NULL"):"N"==b?a||(a=0):"S"==b?a||(a=""):"M"==b&&(a||(a=1));return a}function _81(){return Date.today().toString("dd/MM/yyyy")}
function _77(a,b){var d=a.getItemValue(b,!0).toString("dd/MM/yyyy");return"30/12/1899"==d?"":d}function _4(a){return 0==a.length?"&nbsp;":a}function _50(a,b){return null==a?!0:a.match(/^\d+$/)?!0:b&&a.match(/^\d+\.\d+$/)?!0:b&&a.match(/^\d+\,\d+$/)?!0:!1}function _39(a,b,d){b=b.keyCode;var c=String.fromCharCode(b);if(null==b||0==b||8==b||9==b||13==b||27==b||-1<"0123456789".indexOf(c))return!0;d&&"."==c&&a.form.elements[d].focus();return!1}
function _79(a,b){for(var d=b.split(String.fromCharCode(201)),c=0;c<d.length;c++){var g=d[c].split(String.fromCharCode(200));a.put(g[0],g[1])}}
function _30(a,b,d,c){6==a.cells(b,d[0]).getValue()?c?a.setCellExcellType(b,d[1],"ron"):(a.setCellExcellType(b,d[1],"edn"),a.setCellTextStyle(b,d[1],"color:red;border:1px solid gray;")):7==a.cells(b,d[0]).getValue()?c?a.setCellExcellType(b,d[1],"ro"):(a.setCellExcellType(b,d[1],"coro"),a.setCellTextStyle(b,d[1],"color:red;border:1px solid gray;"),c=a.getCustomCombo(b,d[1]),a=a.cells(b,d[2]).getValue(),_79(c,a)):a.setCellExcellType(b,d[1],"ron")}
function _59(a,b){try{var d=a.getElementsByTagName(b)[0].childNodes[0].nodeValue}catch(c){d=""}return d}function _93(a){a=a.split(/\D/);return new Date(Date.UTC(+a[0],--a[1],+a[2],+a[3],+a[4],+a[5],0))}function _92(a,b){b=b.replace("DD",(10>a.getDate()?"0":"")+a.getDate());b=b.replace("MM",(9>a.getMonth()?"0":"")+(a.getMonth()+1));return b=b.replace("YYYY",a.getFullYear())}function _5(a){a=_93(a);return _92(a,"DD/MM/YYYY")}
function _58(a,b){try{var d=a.getElementsByTagName(b)[0].childNodes[0].nodeValue,c=_93(d),d=1900>c.getFullYear()?"":_92(c,"DD/MM/YYYY")}catch(g){d=""}return d}function _16(a,b,d){try{a.getElementsByTagName(b)[0].childNodes[0].nodeValue=d}catch(c){alert("Erreur ==> "+c.message)}return a}
function _36(a,b,d,c,g,k,e,l,m,f,u){function n(a,c,d){h.startFastOperations();h.clearAll();_52(c)&&h.loadCSVString(c);h.stopFastOperations();_40(b,!1)}var r="",h,B=_108(null,1,k,"SELECT",l),B=_106(B,1,0,e,m+"%"),B=_106(B,1,0,"IdUser",_44._72()),B=_105(B,1,0,_44._83()),A=_1(B),B=null;_89("XMLA",A,n,null,[h],!0);_40(b,!0);h=d.attachGrid(f,320);h.startFastOperations();h.setIconsPath(_44._76());h.setImagePath(_44._71());
h.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;background-color:yellow;"]);h.attachHeader("#text_filter");h.setColTypes("ro");h.setColAlign("left");h.setColSorting("str");h.enableValidation(!0,!1);h.enableAutoWidth(!0);h.setInitWidths("300");h.enableDistributedParsing(!0,10,300);h.init();_41(h);h.csv.row=String.fromCharCode(3);h.csv.cell=String.fromCharCode(2);h.enableCSVAutoID(!1);h.clearAll();h.stopFastOperations();_40(b,!1);h.attachEvent("onHeaderClick",
function(b,e){var f=h.getSelectedRowId();f&&(a.setItemValue(c,f),a.setItemValue(g,h.cells(f,0).getValue()),d.hide(),h.clearSelection(),_52(u)&&u())});h.attachEvent("onRowDblClicked",function(b){a.setItemValue(c,b);a.setItemValue(g,h.cells(b,0).getValue());d.hide();h.clearSelection();_52(u)&&u()});h.attachEvent("onFilterEnd",function(a){if(15>=h.getRowsNum()){_40(b,!0);a=_108(null,1,k,"SELECT",l);var c=r[0].trim();a=_106(a,1,0,e,""==c?"%":"%"+c+"%");a=_106(a,1,0,
"IdUser",_44._72());a=_105(a,1,0,_44._83());a=_1(a);_89("XMLA",a,n,null,[h],!1)}});h.attachEvent("onFilterStart",function(a,b){r=b;return!0});d.show(g);h.getFilterElement(0).focus();h.getFilterElement(0).value=m;_44._12(!1)}
function _46(a,b,d){var c=_108(null,1,"FILETEST.PDF","IMPRIME",a);""!=b&&(c=_106(c,1,0,b,d));c=_106(c,1,0,"IdUser",_44._72());c=_105(c,1,0,_44._83());b=_1(c);c=null;_89("XMLA",b,function(a,b,c){_52(c)&&_52(c[0])&&(a="http://"+_44._62()+":"+_44._61()+"/DOWNLOAD?FileName="+encodeURIComponent(b),window.open(a,"_self"))},null,[a],!1)}
function _48(a,b,d,c){function g(b,c,d){e.startFastOperations();e.clearAll();_52(c)&&e.loadCSVString(c);e.stopFastOperations();_40(a,!1)}var k="",e,l="Select TOP 20 IdEtat, Libelle From dbo.WRFnPrint(IdEcran, IdUser) Where Libelle Like :Libelle Order By Libelle",l=l.replace("IdEcran",b),l=l.replace("IdUser",_44._72()),l=l.replace("Identifiant",c);b=_108(null,1,"ETATS","SELECT",l);b=_106(b,1,0,"LIBELLE","%");var m=_1(b);b=null;_89("XMLA",
m,g,null,[e],!0);_40(a,!0);var f=new dhtmlXPopup({mode:"right"});e=f.attachGrid(350,320);e.startFastOperations();e.setIconsPath(_44._76());e.setImagePath(_44._71());e.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;"]);e.attachHeader("#text_filter");e.setColTypes("ro");e.setColAlign("left");e.setColSorting("str");e.enableValidation(!0,!1);e.setInitWidths("*");e.enableDistributedParsing(!0,10,300);e.init();_41(e);e.csv.row=String.fromCharCode(3);
e.csv.cell=String.fromCharCode(2);e.enableCSVAutoID(!1);e.stopFastOperations();_40(a,!1);e.attachEvent("onHeaderClick",function(a,b){var g=e.getSelectedRowId();g&&(f.hide(),e.clearSelection(),_46(g,d,c))});e.attachEvent("onRowDblClicked",function(a){f.hide();e.clearSelection();_46(a,d,c)});e.attachEvent("onFilterEnd",function(b){if(15>=e.getRowsNum()){_40(a,!0);b=_108(null,1,"ETATS","SELECT",l);var c=k[0].trim();b=_106(b,1,0,"LIBELLE",""==c?"%":"%"+c+"%");b=_1(b);
_89("XMLA",b,g,null,[e],!1)}});e.attachEvent("onFilterStart",function(a,b){k=b;return!0});f.show(50,50,350,300);e.getFilterElement(0).focus();_44._12(!1);return f}
function _8(a,b,d){var c,g=0,k=!1,e=!1;d="Select IdObs, IdUser, Auteur, DateObs, Obs, Statut From dbo.WRFnObs(@IdUser_, '@Auteur_', '@Identifiant_') Order By IdObs desc".replace("@Identifiant_",b);d=d.replace("@IdUser_",_44._72());d=d.replace("@Auteur_",_44._82());d=_108(null,1,"OBS","SELECT",d);var l=_1(d);d=null;_89("XMLA",l,function(b,d,m){_52(d)&&(c.startFastOperations(),c.clearAll(),c.loadCSVString(d),0<c.getRowsNum()?(c.selectRow(0),
g=c.getSelectedRowId(),c.cells(g,0).getValue()):(c.addRow(c.uid(),[_44._72(),_44._82(),_81(),"",""],0),c.selectRow(0),g=c.getSelectedRowId(),e=k=!0),c.stopFastOperations(),c.forEachRow(function(a){"M"==c.cells(a,1).getValue()?c.setRowColor(a,"green"):c.setRowColor(a,"red")}),c.selectRow(0));_40(a,!1)},null,[c],!0);_40(a,!0);d=_44._70();var m=_49.dhxWins.createWindow("myWind"+d,100,100,2*a.getWidth()/3,2*a.getHeight()/3);m.centerOnScreen();
m.setModal(!0);m.denyPark();m.setText("Ecran de contr\u00f4le");c=m.attachGrid();d=m.attachToolbar();d.setIconsPath(_44._76());d.addButton("N",0,"Nouveau","new.gif");d.addButton("S",1,"Sauvegarder","save.gif");d.addButton("F",2,"Fermer","close.gif");d.attachEvent("onClick",function(d){if("F"==d&&0==e)m.close();else if("F"==d&&1==e)dhtmlx.confirm({type:"confirm-warning",title:"Nafys",cancel:"Annuler",ok:"Fermer",text:"Confirmez l'abandon de cette saisie.",callback:function(a){1==a&&
m.close()}});else if("N"==d&&0==k)g=c.uid(),c.addRow(g,[_44._72(),_44._82(),_81(),"",""],0),"M"==_44._82()?c.setRowColor(g,"green"):c.setRowColor(g,"red"),c.selectRow(0),k=e=!0;else if("S"==d&&1==e&&_52(g)){_40(a,!0);var l=1==k?"Insert into WRObs(Identifiant, IdUser, Auteur, Obs, Statut) values(:Identifiant, :IdUser,  :Auteur, :Obs, :Statut)":"Update WRObs Set Obs = :Obs, Statut = :Statut Where IdObs = :IdObs";d=c.cells(g,3).getValue();var n=
c.cells(g,4).getValue(),n="Validation"==n?"G":"Attention"==n?"Y":"Erreur"==n?"R":"Non Controle"==n?"W":"Corrige"==n?"B":"W",l=_108(null,1,"OBS","EXECUTE",l),l=_106(l,1,0,"Identifiant",b),l=_106(l,1,0,"IdUser",_44._72()),l=_106(l,1,0,"Auteur",_44._82()),l=_106(l,1,0,"Obs",d),l=_106(l,1,0,"Statut",n),l=_106(l,1,0,"IdObs",g);d=_1(l);l=null;_89("XMLA",d,null,null,null,!1);k=e=!1}});c.startFastOperations();c.setIconsPath(_44._76());
c.setImagePath(_44._71());c.setHeader(["User","Auteur","Date Obs","Observations","Statut"]);c.setColTypes("ro,ro,ro,txt,context");c.setColAlign("right,center,center,left,center");c.setColSorting("int,str,int,str,str");c.enableValidation(!0,!1);c.setInitWidthsP("0, 10, 20, 60, 10");c.enableDistributedParsing(!0,10,300);d=new dhtmlXMenuObject;d.setIconsPath(_44._76());d.addNewChild(d.topId,0,"G","Validation",!1,"green.gif");d.addNewChild(d.topId,1,"Y","Attention",!1,"yellow.gif");
d.addNewChild(d.topId,2,"R","Erreur",!1,"red.gif");d.renderAsContextMenu();c.setSubContext(d,4,0);c.enableAutoHeight(!0);c.init();_41(c);c.csv.row=String.fromCharCode(3);c.csv.cell=String.fromCharCode(2);c.enableCSVAutoID(!1);c.stopFastOperations();_40(a,!1);c.attachEvent("onEditCell",function(a,b,d,k,h){if(_52(b)&&_52(g))if(0==a){if(b!=g||_44._72()!=c.cells(g,0).getValue())return!1}else 2==a&&(e=!0);else return!1;return!0});_44._12(!1)};
