var Cession;
(function(){var a=-1,b="",c=0,d=0,f="192.168.1.167",h=8E3,e="",l=!1,m=0,k="",r=[],p={};Cession=function(){};Cession.prototype._66=function(){return a};Cession.prototype._23=function(b){a=b};Cession.prototype._69=function(){return c};Cession.prototype._26=function(a){c=a};Cession.prototype._61=function(){return b};Cession.prototype._20=function(a){b=a};Cession.prototype._64=function(){return d};Cession.prototype._22=function(a){d=a};Cession.prototype._56=function(){return f};
Cession.prototype._16=function(a){f=a};Cession.prototype._55=function(){return h};Cession.prototype._15=function(a){h=a};Cession.prototype._54=function(){return e};Cession.prototype._14=function(a){e=a};Cession.prototype._63=function(){return m};Cession.prototype._21=function(a){m=a};Cession.prototype._51=function(){return k};Cession.prototype._12=function(a){k=a};Cession.prototype._50=function(){return l};Cession.prototype._11=
function(a){l=a};Cession.prototype._76=function(){return r};Cession.prototype._29=function(a){r=a};Cession.prototype._98=function(a){r.push(a)};Cession.prototype._93=function(){r=[];r.push([0,"IdUser_",a])};Cession.prototype._83=function(a){for(var b=r.length-1,c=!0;0<=b&&c;)r[b][0]>=a?(r.pop(),b--):c=!1};Cession.prototype._59=function(){return p};Cession.prototype._19=function(a){p=a};Cession.prototype._70=function(){return"../imgs/"};Cession.prototype._65=
function(){return"../codebase/imgs/"}})();var _40=new Cession,_45;
window.onload=function(){window.applicationCache.addEventListener("updateready",function(){window.applicationCache.swapCache();window.location.reload()},!1);window.applicationCache.addEventListener("obsolete",function(a){window.applicationCache.update()},!1);dhtmlx.image_path="codebase/imgs/";_45=new dhtmlXLayoutObject({parent:document.body,pattern:"4I",skin:"dhx_skyblue"});var a=_45.cells("a");a.setText("Entete");a.setHeight("120");a.hideHeader();a.fixSize(0,1);var b=a.attachLayout("2E"),
a=b.cells("a");a.setText("Logo");a.setHeight("70");a.hideHeader();a.fixSize(0,1);a.attachHTMLString('<div id="MyCssGris" <span style="color:#F1F5F8;font-family:tahoma;font-size:58px;text-align:center;"><strong>Web@Report</strong></span></div>');var c=b.cells("b");c.hideHeader();c.fixSize(0,1);c.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:15px;text-align:center;z-index:20;">_</span></div>');c.setHeight("30");b=_45.cells("b");b.setText("Menu");
b.setWidth("220");b.fixSize(1,0);var d=b.attachTree();d.setSkin("dhx_skyblue");d.setImagePath("../codebase/imgs/dhxtree_skyblue/");var f=_45.cells("c");f.setText("Etat");f.hideHeader();var h=_45.cells("d");h.hideHeader();h.fixSize(0,1);h.attachHTMLString('<div id="MyCssBleu" <span style="color:#ffffff;font-family:tahoma;font-size:17px;text-align:center;z-index:20;">Copyright \u00a9 2014 by NtSoft &nbsp;&nbsp; &#0149;&nbsp;&nbsp;All Rights reserved  &nbsp;&nbsp; &#0149;&nbsp;&nbsp; E-Mail: support@nt-soft.ma</span></div>');
h.setHeight("25");_45.attachEvent("onResizeFinish",function(){c.setHeight("30");h.setHeight("25")});b.collapse();b.hideArrow();d.enableHighlighting(!0);d.attachEvent("onSelect",function(a){if(a&&a.startsWith("M")&&null!=f&&0<_40._66()){for(;0<_40._64();)f.unloadView("Page"+_40._64()),_40._22(_40._64()-1);var b='<div id="MyCssColor" <span style="color:#ffffff;font-family:tahoma;font-size:25px;text-align:center;z-index:20;">'+d.getItemText(a)+
"</span></div>";c.attachHTMLString(b);_40._93();f.showView("def");b=a.substring(1,2);a=parseInt(a.substring(2));0<a?"A"==b||"B"==b?_8(f,b,a,1):"C"==b||"D"==b?_9(f,b,a,1):"E"==b||"F"==b?_10(f,b,a,1):"G"==b?_42(a,LibIdent,rId):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."}):dhtmlx.alert({title:"Web@Report",type:"alert-error",text:"Module En cours de Construction."})}});f.hideHeader();_40._19(f);_7(f,
d,a,b)};window.onunload=function(){if(null!=_40._59()){var a=_40._59().getAttachedToolbar();a&&(_40._59().detachToolbar(),a.unload())}};function _30(a,b,c){a=b.split(String.fromCharCode(5));for(b=0;b<a.length;b++){var d=a[b].split(String.fromCharCode(4));0==d[1]&&""!=d[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:d[4]});"LOGIN"==d[2]&&"PROCEDURE"==d[3]&&1<=d[5].length?(d=_6(d[5]),_40._23(_53(d,"IdUser_")),_40._20(_53(d,"LibUser_")),_40._26(_53(d,"IdEcran_"))):"MENU"==d[2]&&"SELECT"==d[3]&&10<=d[5].length&&(d=_87(d[5]),c[0].deleteChildItems(0),c[0].loadCSVString(d),
c[0].openAllItems(0))}c[1]&&c[1].hide&&(c[1].hide(),c[1].unload(),c[1]=null);if(c[2]&&c[2].showView){for(c[2].detachObject(!0);0<_40._64();)c[2].unloadView("Page"+_40._64()),_40._22(_40._64()-1);c[2].showView("def")}_40._93();c[0].selectItem("G1");c[4]&&c[4].isCollapsed&&c[4].isCollapsed()&&(c[4].expand(),c[4].showArrow());c[5]&&c[5].unload}
function _7(a,b,c,d){var f={login:"Votre login personnel",pwd:"Votre Mot de Passe Confidentiel."};_40._22(_40._64()+1);a.showView("Page"+_40._64());_90("MyContainer");_92("#MyContainer","position:absolute;left: 50%;top: 50%;width: 350px; height: 280px; margin-left: -175px; margin-top: -140px;");_95("#MyContainer","MyContainer",!1);a.attachObject("MyContainer");var h=new dhtmlXForm("MyContainer",[{type:"settings",position:"label-top",
labelWidth:"150",inputWidth:"280"},{type:"fieldset",label:"Bienvenue",width:320,offsetLeft:10,offsetTop:10,list:[{type:"block",list:[{type:"label",name:"Titre",label:"<img src='../imgs/about.gif' />   NafysWeb"}]},{type:"input",name:"login",label:"Login",value:"",tooltip:"Login",required:!0},{type:"password",name:"pwd",label:"Mot de Passe",value:"",required:!0},{type:"button",name:"proceed",value:"Valider",width:"120",offsetLeft:"50"}]}]);h.setFontSize("17px");var e=new dhtmlXPopup({form:h,id:["login",
"pwd"]});h.attachEvent("onFocus",function(a){e.attachHTML("<div style='margin: 5px 10px;'>"+f[a]+"</div>");e.show(a)});h.attachEvent("onBlur",function(a){e&&e.hide&&e.hide()});h.attachEvent("onButtonClick",function(f){if("proceed"==f){f=h.getItemValue("login");var m=h.getItemValue("pwd");f=_34(_40._56(),f,m,_40._55(),0);_82("XMLZ",f,_30,null,[b,e,a,c,d,h],!1)}})};function _10(a,b,c,d){function f(){_40._83(d);e&&e.forEachItem(function(a){var b="",c=e.getItemType(a);"calendar"==c?(c=e.getItemValue(a),_48(c)&&(b=c.toString("dd/MM/yyyy")),"30/12/1899"==b&&(b=""),_40._98([d,a,b])):"input"==c?(b=e.getItemValue(a),_40._98([d,a,b])):"checkbox"==c&&(b=e.getItemValue(a),_40._98([d,a,b]))})}var h,e,l=0,m=0,k="",r,p;_40._83(d);_36(a,!0);var x=_99(null,1,"GRIDEF","WRDIAG","WRPSGRIDEF"),
x=_97(x,1,0,"IdEcran_",c),x=_96(x,1,0,_40._76()),g=_1(x),x=null;_82("XMLZ",g,function(c,g,n){if(_48(n)&&0<_40._66()){c=g.split(String.fromCharCode(5));g=null;for(g=0;g<c.length;g++)if(n=c[g].split(String.fromCharCode(4)),0==n[1]&&""!=n[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:n[4]}),"GRIDEF"==n[2]&&"WRDIAG"==n[3]&&1<=n[5].length){var t=_6(n[5]);n=_53(t,"fForm_");l=parseInt(_53(t,"fWinHeight_"));m=parseInt(_53(t,
"fWinWidth_"));k=_53(t,"fDblClick_");t=null;0==m&&(m=2*a.getWidth()/3);0==l&&(l=2*a.getHeight()/3);if("E"==b)var z=t=10;else u.setDimension(m+100,l+100),u.centerOnScreen(),t=20,z=10;n=n.replace("NtsOffsetLeft",t);n=n.replace("NtsOffsetTop",z);var x;eval("x="+n);"E"==b?(_90("MyContainer"),n="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;",n=n.replace("wwpx",m+"px"),n=n.replace("hhpx",l+"px"),n=n.replace("llpx",Math.round(m/2)+"px"),
n=n.replace("ttpx",Math.round(l/2)+"px"),_92("#MyContainer",n),_95("#MyContainer","MyContainer",!1),a.attachObject("MyContainer"),e=new dhtmlXForm("MyContainer"),e.setFontSize("17px")):e=u.attachForm();r.form=e;e.enableLiveValidation(!0);e.setFontSize("17px");e.loadStruct(x);n=x=null;e.forEachItem(function(a){var b="",b=null,b=e.getItemType(a),c=e.getUserData(a,"Key"),f=e.getUserData(a,"Sql");_48(c)&&_48(f)&&r.id.push(a);if("calendar"==b)e.setCalendarDateFormat(a,"%d/%m/%Y",
"%d/%m/%Y"),b=e.getInput(a),b.style.textAlign="center",b=e.getItemValue(a),_40._98([d,a,b]);else if("input"==b){b=e.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";b=e.getItemValue(a);_40._98([d,a,b])}else"checkbox"==b&&(b=e.getItemValue(a),_40._98([d,a,b]),"0"==b||"N"==b?e.uncheckItem(a):e.checkItem(a))});e.attachEvent("onKeyUp",function(b,c,d){if(9!=c.keyCode&&0<=r.id.indexOf(d)){b=e.getUserData(d,"Key");
var g=e.getUserData(d,"Sql");c=String.fromCharCode(c.keyCode);f();_32(e,a,p,b,d,b,d,g,c,350)}});p=new dhtmlXPopup(r);""!=k&&e.attachEvent("onButtonClick",function(c,e){_48(h)&&(h.unload(),h=null);if("BtOui"==c){f();var g=k.substring(0,1),l=parseInt(k.substring(1));0<l&&("F"==b&&_48(u)&&(_48(p)&&(p.unload(),r=p=null),u.close()),"A"==g||"B"==g?_8(a,g,l,d+1):"C"==g||"D"==g?_9(a,g,l,d+1):"E"==g||"F"==g?_10(a,g,l,d+1):"G"==g&&_42(l,"",""))}else"BtNon"==
c&&("E"==b?(_48(p)&&(p.unload(),r=p=null),a.unloadView("Page"+_40._64()),_40._22(_40._64()-1),g=_40._64(),0==g?(a.showView("def"),_40._93()):(a.showView("Page"+g),_40._83(d))):"F"==b&&_48(u)&&(_48(p)&&(p.unload(),r=p=null),u.close(),_40._83(d)))})}else if(!("GRIDEF"==n[2]&&"DATA"==n[3]&&10<=n[5].length)&&"GRIDEF"==n[2]&&"TOOLS"==n[3]&&10<=n[5].length)for(n=n[5].split(String.fromCharCode(3)),g=
0;g<n.length;g++)t=n[g].split(String.fromCharCode(2)),"A"==t[2]?w.addButton("A"+g,g,t[1],t[5],t[6]):"B"==t[2]?w.addButton("B"+g,g,t[1],t[5],t[6]):"C"==t[2]?w.addText("C"+g,g,t[1]):"D"==t[2]?w.addSeparator("D"+g,g):w.addButton("E"+t[4]+t[3],g,t[1],t[5],t[6]);c=null;_36(a,!1)}},null,[a],!0);a.setText("Liste");if("E"==b){_40._22(_40._64()+1);a.showView("Page"+_40._64());var w=a.attachToolbar()}else{var x=_40._64(),u=_45.dhxWins.createWindow("myWind"+
x,100,100,400,400);u.centerOnScreen();u.setModal(!0);u.denyPark();u.setText("Web@Report");w=u.attachToolbar()}r={form:null,id:[]};w.setIconsPath(_40._70());w.attachEvent("onClick",function(e){_48(h)&&(h.unload(),h=null);var g=e.substring(0,1);"A"==g?(f(),h=_44(a,c,"","")):"B"==g&&"E"==b?(_48(p)&&(p.unload(),r=p=null),a.unloadView("Page"+_40._64()),_40._22(_40._64()-1),e=_40._64(),0==e?(a.showView("def"),_40._93()):
(a.showView("Page"+e),_40._83(d))):"B"==g&&"F"==b?_48(u)&&(_48(p)&&(p.unload(),r=p=null),u.close(),_40._83(d)):"E"==g&&(g=e.substring(1,2),e=parseInt(e.substring(2)),0<e&&(f(),"F"==b&&_48(u)&&(_48(p)&&(p.unload(),r=p=null),u.close()),"A"==g||"B"==g?_8(a,g,e,d+1):"C"==g||"D"==g?_9(a,g,e,d+1):"E"==g||"F"==g?_10(a,g,e,d+1):"G"==g&&_42(e,"","")))});_40._11(!1)};function _9(a,b,c,d){var f,h,e=0,l=0;_40._83(d);_36(a,!0);var m=_99(null,1,"GRIDCD","WRFORM","WRPSGRIDCD"),m=_97(m,1,0,"IdEcran_",c),m=_96(m,1,0,_40._76()),k=_1(m),m=null;_82("XMLZ",k,function(c,g,f){if(_48(f)&&0<_40._66()){c=g.split(String.fromCharCode(5));g=null;for(g=0;g<c.length;g++)if(f=c[g].split(String.fromCharCode(4)),0==f[1]&&""!=f[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:f[4]}),
"GRIDCD"==f[2]&&"WRFORM"==f[3]&&1<=f[5].length){var k=_6(f[5]);f=_53(k,"fForm_");e=parseInt(_53(k,"fWinHeight_"));l=parseInt(_53(k,"fWinWidth_"));k=null;0==l&&(l=2*a.getWidth()/3);0==e&&(e=2*a.getHeight()/3);if("C"==b)var m=10,y=10;else m=20,y=10;f=f.replace("NtsOffsetLeft",m);f=f.replace("NtsOffsetTop",y);var n;eval("n="+f);"C"==b?(_90("MyContainer"),f="position:absolute;left: 50%;top: 50%;width: wwpx; height: hhpx; margin-left: -llpx; margin-top: -ttpx;",f=f.replace("wwpx",
l+"px"),f=f.replace("hhpx",e+"px"),f=f.replace("llpx",Math.round(l/2)+"px"),f=f.replace("ttpx",Math.round(e/2)+"px"),_92("#MyContainer",f),_95("#MyContainer","MyContainer",!1),a.attachObject("MyContainer"),h=new dhtmlXForm("MyContainer"),h.setFontSize("17px")):(p.detachObject(!0),h=p.attachForm(),p.setDimension(l+100,e+100),p.setText("Web@Report"),p.centerOnScreen(),p.setModal(!0),p.denyPark(),p.button("close").enable());h.enableLiveValidation(!0);h.setFontSize("17px");h.loadStruct(n);
f=n=null}else if("GRIDCD"==f[2]&&"DATA"==f[3]&&10<=f[5].length)k=_6(f[5]),h.forEachItem(function(a){var b="",b=null,b=h.getItemType(a);if("calendar"==b)h.setCalendarDateFormat(a,"%d/%m/%Y","%d/%m/%Y"),b=h.getInput(a),b.style.textAlign="center",(b=_53(k,a))&&h.setItemValue(a,b),_40._98([d,a,b]);else if("input"==b){b=h.getInput(a);if("0"==b.value||"0.00"==b.value||0<Math.abs(parseFloat(b.value)))b.style.textAlign="right";(b=_53(k,a))&&h.setItemValue(a,b);_40._98([d,
a,b])}else"checkbox"==b&&(b=_53(k,a),"0"==b||"N"==b?h.uncheckItem(a):h.checkItem(a),_40._98([d,a,b]))}),k=null;else if("GRIDCD"==f[2]&&"TOOLS"==f[3]&&10<=f[5].length)for(f=f[5].split(String.fromCharCode(3)),g=0;g<f.length;g++)m=f[g].split(String.fromCharCode(2)),"A"==m[2]?r.addButton("A"+g,g,m[1],m[5],m[6]):"B"==m[2]?r.addButton("B"+g,g,m[1],m[5],m[6]):"C"==m[2]?r.addText("C"+g,g,m[1]):"D"==m[2]?r.addSeparator("D"+g,g):r.addButton("E"+m[4]+m[3],g,m[1],m[5],m[6]);c=null;_36(a,
!1)}},null,[a],!0);a.setText("Liste");if("C"==b){_40._22(_40._64()+1);a.showView("Page"+_40._64());var r=a.attachToolbar()}else{var m=_40._64(),p=_45.dhxWins.createWindow("myWind"+m,20,30,400,280),r=p.attachToolbar();p.setText("Web@Report : En cours ... ");p.centerOnScreen();p.setModal(!0);p.denyPark();p.button("close").disable();p.attachChart({view:"pie",value:"#sales#",color:"#color#"}).parse([{sales:"10",month:"3",color:"#ee9e36"},{sales:"10",
month:"4",color:"#eeea36"},{sales:"10",month:"5",color:"#a9ee36"},{sales:"10",month:"6",color:"#36d3ee"},{sales:"10",month:"7",color:"#367fee"},{sales:"10",month:"8",color:"#9b36ee"}],"json")}r.setIconsPath(_40._70());r.attachEvent("onClick",function(e){_48(f)&&(f.unload(),f=null);var g=e.substring(0,1);"A"==g?f=_44(a,c,"",""):"B"==g&&"C"==b?(a.unloadView("Page"+_40._64()),_40._22(_40._64()-1),e=_40._64(),0==e?(a.showView("def"),
_40._93()):(a.showView("Page"+e),_40._83(d))):"B"==g&&"D"==b?_48(p)&&(p.close(),_40._83(d)):"E"==g&&(g=e.substring(1,2),e=parseInt(e.substring(2)),0<e&&("D"==b&&_48(p)&&p.close(),"A"==g||"B"==g?_8(a,g,e,d+1):"C"==g||"D"==g?_9(a,g,e,d+1):"E"==g||"F"==g?_10(a,g,e,d+1):"G"==g&&_42(e,"","")))});_40._11(!1)};function _8(a,b,c,d){function f(b,c,d){k.startFastOperations();k.clearAll();_48(c)&&k.loadCSVString(c);k.stopFastOperations();_36(a,!1)}var h=[],e=[],l=[],m,k,r=null,p="",x="",g=0,w=0;_36(a,!0);var u=_99(null,1,"GRIDAB","WRGRID","WRPSGRIDAB"),u=_97(u,1,0,"IdEcran_",c),u=_96(u,1,0,_40._76()),A=_1(u),u=null;_82("XMLZ",A,function(t,z,u){if(_48(u)&&0<_40._66()){var A=u="",C=z.split(String.fromCharCode(5));
z=null;for(t=0;t<C.length;t++){var q=C[t].split(String.fromCharCode(4));0==q[1]&&""!=q[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:q[4]});if("GRIDAB"==q[2]&&"WRGRID"==q[3]&&1<=q[5].length){var q=_6(q[5]),v=_53(q,"gHeader_"),s=_53(q,"gFilter_"),D=_53(q,"gTypes_"),B=_53(q,"gColAlig_"),G=_53(q,"gColSort_"),E=_53(q,"gColType_"),H=_53(q,"gColWidth_");r=_53(q,"gCmdeSQL_");u=_53(q,"gTotaux_");var A=_53(q,"gFooter_"),I=_53(q,"gColVars_");p=_53(q,
"gLibIdent_");x=_53(q,"gDblClick_");g=parseInt(_53(q,"gWinHeight"));w=parseInt(_53(q,"gWinWidth"));var F="O"==_53(q,"gRecSrv_");e=E.split(",");l=F?I.split(","):[];E=q=null;k.startFastOperations();k.setHeader(v.split(","));""!=s&&k.attachHeader(s);k.setColTypes(D);k.setColAlign(B);k.setColSorting(G);k.enableValidation(!0,!1);k.setInitWidths(H);if("O"==u){q=A.split(String.fromCharCode(10));for(v=0;v<q.length;v++)s=q[v].trim(),5<s.length&&(s=s.split("&&"),k.attachFooter(s[0],s[1]),s=s=null);
q=null}k.init();k.csv.row=String.fromCharCode(3);k.csv.cell=String.fromCharCode(2);k.enableCSVAutoID(!1);k.clearAll();k.stopFastOperations()}else if("GRIDAB"==q[2]&&"DATA"==q[3]&&10<=q[5].length)z=q[5];else if("GRIDAB"==q[2]&&"FOOTER"==q[3]&&10<=q[5].length&&"O"==u){q=_6(q[5]);s=_79(A);for(v=0;v<s.length;v++)if(D=document.getElementById(s[v]))if(B=_53(q,s[v]))B=parseFloat(B),D.innerHTML=B.toMoney();q=s=null}else if("GRIDAB"==q[2]&&"TOOLS"==q[3]&&10<=q[5].length)for(q=q[5].split(String.fromCharCode(3)),
v=0;v<q.length;v++)s=q[v].split(String.fromCharCode(2)),"A"==s[2]?y.addButton("A"+v,v,s[1],s[5],s[6]):"B"==s[2]?y.addButton("B"+v,v,s[1],s[5],s[6]):"C"==s[2]?y.addText("C"+v,v,s[1]):"D"==s[2]?y.addSeparator("D"+v,v):"P"==s[2]?y.addButton("P"+v,v,s[1],s[5],s[6]):"X"==s[2]?y.addButton("X"+v,v,s[1],s[5],s[6]):y.addButton("E"+s[4]+s[3],v,s[1],s[5],s[6])}C=q=null;for(t=0;t<e.length;t++)u=parseInt(e[t].substring(1)),2==u?k.setNumberFormat("0,000.00",t,"."," "):3==u&&k.setNumberFormat("0,000.00%",t,".",
" ");k.startFastOperations();k.loadCSVString(z);k.stopFastOperations();z=null;"B"==b&&_48(n)&&(0==w&&(w=2*a.getWidth()/3),0==g&&(g=2*a.getHeight()/3),n.setDimension(w,g),n.centerOnScreen());""!=x&&k.attachEvent("onRowDblClicked",function(c,e){_48(m)&&(m.unload(),m=null);if(null!=c){_40._83(d);_40._98([d,p,c]);for(var f=0;f<l.length;f++){var g=l[f],h=k.cells(c,f).getValue();_40._98([d,g,h])}}f=x.substring(0,1);g=parseInt(x.substring(1));0<g&&("B"==
b&&_48(n)?n.close():"A"==f||"B"==f?_8(a,f,g,d+1):"C"==f||"D"==f?_9(a,f,g,d+1):"E"==f||"F"==f?_10(a,f,g,d+1):"G"==f&&_42(g,p,c))});F&&(k.attachEvent("onFilterEnd",function(b){_48(m)&&(m.unload(),m=null);if(25>k.getRowsNum()){_36(a,!0);_40._83(d);for(var g=_99(null,1,"SQL","SELECT",r),g=_97(g,1,0,"IdEcran_",c),p=!0,n=0;n<b.length;n++){var q=b[n][1],t=parseInt(e[q].substring(1));if(4==t||5==t)p=p&&(""==h[n]||_47(h[n]));g=_97(g,
1,0,l[q],h[n])}p&&(g=_96(g,1,0,_40._76()),b=_1(g),_82("XMLA",b,f,null,[a],!1))}}),k.attachEvent("onFilterStart",function(a,b){h=b;for(var c=!0,d=0;d<a.length;d++){var f=parseInt(e[a[d]].substring(1));if(4==f||5==f)c=c&&(""==h[d]||_47(h[d]))}return c}));_36(a,!1)}},null,[a],!0);a.setText("Liste");if("A"==b){_40._22(_40._64()+1);a.showView("Page"+_40._64());var y=a.attachToolbar();k=a.attachGrid()}else{var u=_40._64(),
n=_45.dhxWins.createWindow("myWind"+u,100,100,2*a.getWidth()/3,2*a.getHeight()/3);n.centerOnScreen();n.setModal(!0);n.denyPark();n.setText("Web@Report");k=n.attachGrid();y=n.attachToolbar()}y.setIconsPath(_40._70());y.attachEvent("onClick",function(f){_48(m)&&(m.unload(),m=null);var e=f.substring(0,1);if("A"==e){if(_40._83(d),f=k.getSelectedRowId(),null!=f){_40._98([d,p,f]);for(var g=0;g<l.length;g++){var h=l[g],r=k.cells(f,g).getValue();_40._98([d,
h,r])}m=_44(a,c,p,f)}}else if("B"==e&&"A"==b)a.unloadView("Page"+_40._64()),_40._22(_40._64()-1),e=_40._64(),0==e?(a.showView("def"),_40._93()):(a.showView("Page"+e),_40._83(d));else if("B"==e&&"B"==b)_48(n)&&(n.close(),_40._83(d));else if("P"==e)k.toPDF("../codebase/grid-pdf-php/generate.php");else if("X"==e)k.toExcel("../codebase/grid-excel-php/generate.php");else if("E"==e){var e=f.substring(1,2),q=
parseInt(f.substring(2));_40._83(d);f=k.getSelectedRowId();if(null!=f)for(_40._98([d,p,f]),g=0;g<l.length;g++)h=l[g],r=k.cells(f,g).getValue(),_40._98([d,h,r]);0<q&&("B"==b&&_48(n)&&n.close(),"A"==e||"B"==e?_8(a,e,q,d+1):"C"==e||"D"==e?_9(a,e,q,d+1):"E"==e||"F"==e?_10(a,e,q,d+1):"G"==e&&_42(q,p,f))}});k.startFastOperations();k.setIconsPath(_40._70());k.setImagePath(_40._65());k.enableValidation(!0,
!1);k.enableDistributedParsing(!0,10,300);k.setDateFormat("%d/m/Y");k.i18n.decimal_separator=".";k.i18n.group_separator=" ";k.enableCSVAutoID(!1);k.stopFastOperations();_40._11(!1);k.attachEvent("onRowSelect",function(a,b){_48(m)&&(m.unload(),m=null)})};"undefined"===typeof Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});function _79(a){for(var b=[],c=_80(a,' id="','"');0<c.length;)b.push(c),a=_31(a,c),c=_80(a,' id="','"');return b}function _80(a,b,c){return(a=a.match(b+"(.*?)"+c))&&0<a.length?a[1]:""}function _31(a,b){var c=a.indexOf(b);return-1!=c?a.substr(c+b.length):a}
function _41(a,b){var c=[a];for("string"==typeof b&&(b=[b]);0<b.length;){for(var d=0;d<c.length;d++)var f=c[d].split(b[0]),c=c.slice(0,d).concat(f).concat(c.slice(d+1));b.shift()}return c}function _90(a){var b=document.getElementById(a);b?(b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)"):(b=document.createElement("div"),b.id=a,b.style.background="rgb(0,102,153)",b.style.color="rgb(255,255,0)",document.body.appendChild(b))}
function _92(a,b){var c=document.createElement("style");c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);(c.sheet||{}).insertRule?c.sheet.insertRule(a+"{"+b+"}",0):(c.styleSheet||c.sheet).addRule(a,b)}function _95(a,b,c){"string"==typeof b.valueOf()&&(b=document.getElementById(b));b&&(b.className=c?b.className.replace(new RegExp("\\b"+a+"\\b","g"),""):b.className+" "+a)}
function _39(a){function b(a,b,c){if(_48(c)&&0<_40._66()){var d=a=_40._68();b=b.split(String.fromCharCode(5));for(var m=0;m<b.length;m++){var k=b[m].split(String.fromCharCode(4));0==k[1]&&""!=k[4]&&dhtmlx.alert({title:"Web@Report",type:"alert-error",text:k[4]});"PUBIDT"==k[2]&&"PROCEDURE"==k[3]&&1<=k[5].length?(d=_6(k[5]),d=_53(d,"IdPub_"),d=parseInt(d),0<d&&_40._25(d)):"PUBDET"==k[2]&&"BLOB"==k[3]&&10<=k[5].length&&a!=d&&c[0].attachHTMLString(k[5])}}else _38()}
if(0>=_40._66()||!_48(a))_38();else{var c=_99(null,1,"PUBIDT","PROCEDURE","WRPsPub"),c=_97(c,1,0,"IdUser_",_40._66()),c=_97(c,1,0,"IdPub_",_40._68()),c=_99(c,2,"PUBDET","BLOB","Select * From WRfnPub(:IdPub_)"),c=_97(c,2,1,"IdPub_",0),d=_1(c),c=null;_82("XMLZ",d,b,null,[a],!1)}}function _38(){var a=_40._58();_48(a)&&clearInterval(_40._58());_40._18(null)}var DEBUG=!1;
if(!DEBUG){window.console||(window.console={});for(var methods="log debug warn info dir dirxml trace profile".split(" "),i=0;i<methods.length;i++)console[methods[i]]=function(){}}function _2(a,b,c,d,f,h){a()?window.setTimeout(_2,h,a,b,c,d,f,h):b(c,d,f)}function _37(a){(window.dhx4.isIPad||window.dhx4.isChrome||window.dhx4.isOpera||window.dhx4.isKHTML||window.dhx4.isFF)&&a.enableEditEvents(!0,!1,!1)}
function _77(a){return 1==a?"doc":2==a?"xls":3==a?"rtf":4==a?"xls":5==a?"pdf":6==a||7==a?"jpg":8==a?"zip":9==a?"rar":"pdf"}function _78(a){return"doc"==a?1:"xls"==a?2:"rtf"==a?3:"pdf"==a?5:"jpg"==a?6:"zip"==a?8:"rar"==a?9:"txt"==a?3:5}String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});String.prototype.formatedfloat||(String.prototype.formatedfloat=function(){return parseFloat(this.replace(",",".").replace(" ",""))});
"function"!=typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return this.slice(0,a.length)==a});"function"!=typeof Number.prototype.toMoney&&(Number.prototype.toMoney=function(a,b,c){var d=this;a=isNaN(a)?2:Math.abs(a);b=b||".";c="undefined"===typeof c?" ":c;var f=0>d?"-":"",h=parseInt(d=Math.abs(d).toFixed(a))+"",e=3<(e=h.length)?e%3:0;return f+(e?h.substr(0,e)+c:"")+h.substr(e).replace(/(\d{3})(?=\d)/g,"$1"+c)+(a?b+Math.abs(d-h).toFixed(a).slice(2):"")});
function _48(a){return"undefined"!=typeof a&&null!=a&&""!=a}function _72(a){return a.substr((~-a.lastIndexOf(".")>>>0)+2)}function _86(a,b){var c=Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()),d=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate());return Math.floor((d-c)/864E5)}
function _88(a){var b=String.fromCharCode(3),c=String.fromCharCode(2);a=a.split(b);for(var b=[],d=[],f=-1,h=-1,e=[],l={},m=0;m<a.length;m++){var k=a[m].split(c),l={},h=parseInt(k[3]);f!=h&&(-1!=f&&(l.id=e[0]+"_"+e[3],l.text=e[4],l.item=d,b.push(l),l={},d=[]),f=h,e=k);l.id=k[0];l.text=k[2];d.push(l)}l={};l.id=e[0]+"_"+e[3];l.text=e[4];l.item=d;b.push(l);return"{id:0,  item:"+JSON.stringify(b)+"}"}
function _87(a){var b=String.fromCharCode(3),c=String.fromCharCode(2);a=a.split(b);for(var d=b=-1,f="",h="",e=0;e<a.length;e++){var l=a[e].split(c),d=parseInt(l[4]);b!=d&&(b=d,f="G"+(e+1),h=h+"\n"+f+",0,"+l[5]);h=h+"\nM"+l[1]+l[0]+","+f+","+l[3]}return h}
function _89(a){var b=String.fromCharCode(3),c=String.fromCharCode(2);a=a.split(b);var b=[],d=a[0].split(c);d[0]="value";d[1]="text";for(var f=0;f<a.length;f++){var h={},e=a[f].split(c);h[d[0]]=e[0];h[d[1]]=e[1];b.push(h)}return"{options:"+JSON.stringify(b)+"}"}
var _60=function(){var a;if("undefined"!=typeof window.ActiveXObject)for(var b="Msxml2.DOMDocument.6.0 Msxml2.DOMDocument.5.0 Msxml2.DOMDocument.4.0 Msxml2.DOMDocument.3.0 MSXML2.DOMDocument MSXML.DOMDocument Microsoft.XMLDOM".split(" "),c=0;c<b.length;c++)try{a=new ActiveXObject(b[c]);_60=function(){return new ActiveXObject(b[c])};break}catch(d){}return a};
function _6(a){var b=null;if(window.DOMParser&&!window.ActiveXObject){var c=new DOMParser;try{b=c.parseFromString(a,"text/xml")}catch(d){try{b=_60(),b.async=!1,b.loadXML(a)}catch(f){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}}}else try{b=_60(),b.async=!1,b.loadXML(a)}catch(h){return dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Browser Error : XML parsing error"}),null}return b}
function _1(a){return window.ActiveXObject?a.xml:(new XMLSerializer).serializeToString(a)}function _36(a,b){}
function _99(a,b,c,d,f){_48(a)||(a=_6("<?xml version='1.0' encoding='UTF-16'?><Actions></Actions>"));var h=a.getElementsByTagName("Actions"),e=a.createElement("Action"),l=a.createElement("Type"),m=a.createElement("SQL");d=a.createTextNode(d);f=a.createTextNode(f);m.appendChild(f);l.appendChild(d);e.setAttribute("ID",b);e.setAttribute("Name",c);e.appendChild(l);e.appendChild(m);h[0].appendChild(e);return a}
function _96(a,b,c,d){for(var f=d.length-1,h="",e=0,l=0;l<=f;l++)e=h.search(d[f-l][1]),0>e&&(h=h+";"+d[f-l][1],a=_97(a,b,c,d[f-l][1],d[f-l][2]));return a}function _97(a,b,c,d,f){var h=a.getElementsByTagName("Action"),e=a.createElement("Param"),l=a.createElement("Value");null==f&&(f="");f=a.createTextNode(f);l.appendChild(f);e.setAttribute("Source",c);e.setAttribute("Name",d);e.appendChild(l);for(c=0;c<h.length;c++)h[c].getAttribute("ID")==b&&h[c].appendChild(e);return a}
function _62(a){var b=a.match(/[^\x00-\xff]/g);return a.length+(b?b.length:0)}function _91(a,b){var c=new XMLHttpRequest;"withCredentials"in c?c.open(a,b,!0):"undefined"!=typeof XDomainRequest?(c=new XDomainRequest,c.open(a,b)):c=null;return c}
var _49=function(){var a;try{a=new XMLHttpRequest,_49=function(){return new XMLHttpRequest}}catch(b){for(var c=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],d=0,f=c.length;d<f;++d)try{a=new ActiveXObject(c[d]);_49=function(){return new ActiveXObject(c[d])};break}catch(h){}}return a};
function _94(a){var b=a.byteLength;a=new Uint8Array(a);if(8192>b)return String.fromCharCode.apply(null,a);for(var c=0,d="";c<b;)d+=String.fromCharCode.apply(null,a.subarray(c,c+8192)),c+=8192;return d}var _33=function(a,b){try{return a.readAsBinaryString(b),_33=function(a,b){a.readAsBinaryString(b);return 1},1}catch(c){return a.readAsArrayBuffer(b),_33=function(a,b){a.readAsArrayBuffer(b);return 2},2}};
function _82(a,b,c,d,f,h){function e(a,b,c){dhtmlx.alert({title:a,type:b,text:c});d&&d(f)}var l=!1,m=null;h&&_40._11(!0);var k="http://"+_40._56()+":"+_40._55()+"/"+a;if(500<b.length){var r=new JSZip;r.file("Z.ZIP",b,{base64:!1,binary:!0,compression:"DEFLATE"});b=r.generate({type:"blob"})}else b=new Blob([b],{type:"image/png"});m=_49();_48(m)&&(m.ontimeout=function(){e("Nafys","alert-error","Erreur Systeme : TimeOut")},m.onload=function(b){if(4===
m.readyState)if(200===m.status){try{var d=new Uint8Array(this.response,0,4);if(4==d.byteLength&&80==d[0]&&75==d[1]&&3==d[2]&&4==d[3])try{var g=(new JSZip(this.response,{base64:!1})).file("Z.ZIP").asBinary()}catch(k){e("Nafys","alert-error","Erreur : "+k);return}else g=_94(this.response)}catch(r){g=_94(this.response)}"XMLA"==a?(b=g.split(String.fromCharCode(4)),3!=b.length?e("Nafys","alert-error","Donn\u00e9es non lues du serveur"):(l=b[0],_40._14(b[2]),
0!=l&&3>b[1].length?_48(c)&&(h?_2(_40._50,c,this,b[2],f,100):c(this,b[2],f)):0!=l&&3<b[1].length?(_48(c)&&(h?_2(_40._50,c,this,b[2],f,100):c(this,b[2],f)),e("Nafys","alert-warning",b[1])):3<b[1].length?e("Nafys","alert-warning",b[1]):e("Nafys","alert-error","Erreur Systeme"))):(_40._14(g),_48(c)&&(h?_2(_40._50,c,this,g,f,100):c(this,g,f)))}else e("Nafys","alert-error","Donn\u00e9es non lues du serveur")},m.open("POST",
k,!0),m.timeout=3E4,m.responseType="arraybuffer",m.send(b))}
function _81(a,b,c){var d="http://"+_40.getsAdrGed()+":"+_40._55Ged()+"/DOWNLOAD?FileName="+encodeURIComponent(a),f=null,f=_49();_48(f)&&(f.ontimeout=function(){dhtmlx.alert({title:"Nafys",type:"alert-error",text:"Erreur Systeme : TimeOut"})},f.onload=function(d){if(4===f.readyState&&200===f.status){d=new Blob([this.response],{type:"image/png"});var e=new FileReader;e.addEventListener("loadend",function(){var d=(new JSZip(e.result,{base64:!1})).file("Z.ZIP").asBinary();
_48(b)&&b(this,a,d,c)});e.readAsArrayBuffer(d)}},f.open("POST",d,!0),f.timeout=3E4,f.responseType="blob",f.send(null))}function _34(a,b,c,d,f){a=(new Fingerprint({canvas:!0,ie_activex:!0,screen_resolution:!0})).get();d=_99(null,1,"LOGIN","PROCEDURE","WRpsLogin");d=_97(d,1,0,"Login_",b);d=_97(d,1,0,"PassWord_",c);d=_97(d,1,0,"MachineId_",a);d=_99(d,2,"MENU","SELECT","Select * From WRfnListeMenus(:IdUser_)");d=_97(d,2,1,"IdUser_",0);return _1(d)}
function _47(a){var b=/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(a);if(b){a=a.split("/");var c=new Date(+a[2],a[1]-1,+a[0]);"[object Date]"===Object.prototype.toString.call(c)&&(b=!isNaN(c.getTime())&&c.getDate()==a[0]&&c.getMonth()==a[1]-1)}return b}function _3(a,b){"D"==b?a||(a="NULL"):"N"==b?a||(a=0):"S"==b?a||(a=""):"M"==b&&(a||(a=1));return a}function _75(){return Date.today().toString("dd/MM/yyyy")}
function _71(a,b){var c=a.getItemValue(b,!0).toString("dd/MM/yyyy");return"30/12/1899"==c?"":c}function _4(a){return 0==a.length?"&nbsp;":a}function _46(a,b){return null==a?!0:a.match(/^\d+$/)?!0:b&&a.match(/^\d+\.\d+$/)?!0:b&&a.match(/^\d+\,\d+$/)?!0:!1}function _35(a,b,c){b=b.keyCode;var d=String.fromCharCode(b);if(null==b||0==b||8==b||9==b||13==b||27==b||-1<"0123456789".indexOf(d))return!0;c&&"."==d&&a.form.elements[c].focus();return!1}
function _73(a,b){for(var c=b.split(String.fromCharCode(201)),d=0;d<c.length;d++){var f=c[d].split(String.fromCharCode(200));a.put(f[0],f[1])}}
function _27(a,b,c,d){6==a.cells(b,c[0]).getValue()?d?a.setCellExcellType(b,c[1],"ron"):(a.setCellExcellType(b,c[1],"edn"),a.setCellTextStyle(b,c[1],"color:red;border:1px solid gray;")):7==a.cells(b,c[0]).getValue()?d?a.setCellExcellType(b,c[1],"ro"):(a.setCellExcellType(b,c[1],"coro"),a.setCellTextStyle(b,c[1],"color:red;border:1px solid gray;"),d=a.getCustomCombo(b,c[1]),a=a.cells(b,c[2]).getValue(),_73(d,a)):a.setCellExcellType(b,c[1],"ron")}
function _53(a,b){try{var c=a.getElementsByTagName(b)[0].childNodes[0].nodeValue}catch(d){c=""}return c}function _85(a){a=a.split(/\D/);return new Date(Date.UTC(+a[0],--a[1],+a[2],+a[3],+a[4],+a[5],0))}function _84(a,b){b=b.replace("DD",(10>a.getDate()?"0":"")+a.getDate());b=b.replace("MM",(9>a.getMonth()?"0":"")+(a.getMonth()+1));return b=b.replace("YYYY",a.getFullYear())}function _5(a){a=_85(a);return _84(a,"DD/MM/YYYY")}
function _52(a,b){try{var c=a.getElementsByTagName(b)[0].childNodes[0].nodeValue,d=_85(c),c=1900>d.getFullYear()?"":_84(d,"DD/MM/YYYY")}catch(f){c=""}return c}function _13(a,b,c){try{a.getElementsByTagName(b)[0].childNodes[0].nodeValue=c}catch(d){alert("Erreur ==> "+d.message)}return a}
function _32(a,b,c,d,f,h,e,l,m,k,r){function p(a,c,d){g.startFastOperations();g.clearAll();_48(c)&&g.loadCSVString(c);g.stopFastOperations();_36(b,!1)}var x="",g,w=_99(null,1,h,"SELECT",l),w=_97(w,1,0,e,m+"%"),w=_97(w,1,0,"IdUser",_40._66()),w=_96(w,1,0,_40._76()),u=_1(w),w=null;_82("XMLA",u,p,null,[g],!0);_36(b,!0);g=c.attachGrid(k,320);g.startFastOperations();g.setIconsPath(_40._70());g.setImagePath(_40._65());
g.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;background-color:yellow;"]);g.attachHeader("#text_filter");g.setColTypes("ro");g.setColAlign("left");g.setColSorting("str");g.enableValidation(!0,!1);g.enableAutoWidth(!0);g.setInitWidths("300");g.enableDistributedParsing(!0,10,300);g.init();_37(g);g.csv.row=String.fromCharCode(3);g.csv.cell=String.fromCharCode(2);g.enableCSVAutoID(!1);g.clearAll();g.stopFastOperations();_36(b,!1);g.attachEvent("onHeaderClick",
function(b,e){var h=g.getSelectedRowId();h&&(a.setItemValue(d,h),a.setItemValue(f,g.cells(h,0).getValue()),c.hide(),g.clearSelection(),_48(r)&&r())});g.attachEvent("onRowDblClicked",function(b){a.setItemValue(d,b);a.setItemValue(f,g.cells(b,0).getValue());c.hide();g.clearSelection();_48(r)&&r()});g.attachEvent("onFilterEnd",function(a){if(15>=g.getRowsNum()){_36(b,!0);a=_99(null,1,h,"SELECT",l);var c=x[0].trim();a=_97(a,1,0,e,""==c?"%":"%"+c+"%");a=_97(a,1,0,
"IdUser",_40._66());a=_96(a,1,0,_40._76());a=_1(a);_82("XMLA",a,p,null,[g],!1)}});g.attachEvent("onFilterStart",function(a,b){x=b;return!0});c.show(f);g.getFilterElement(0).focus();g.getFilterElement(0).value=m;_40._11(!1)}
function _42(a,b,c){var d=_99(null,1,"FILETEST.PDF","IMPRIME",a);""!=b&&(d=_97(d,1,0,b,c));d=_97(d,1,0,"IdUser",_40._66());d=_96(d,1,0,_40._76());b=_1(d);d=null;_82("XMLA",b,function(a,b,c){_48(c)&&_48(c[0])&&(a="http://"+_40._56()+":"+_40._55()+"/DOWNLOAD?FileName="+encodeURIComponent(b),window.open(a,"_self"))},null,[a],!1)}
function _44(a,b,c,d){function f(b,c,d){e.startFastOperations();e.clearAll();_48(c)&&e.loadCSVString(c);e.stopFastOperations();_36(a,!1)}var h="",e,l="Select TOP 20 IdEtat, Libelle From dbo.WRFnPrint(IdEcran, IdUser) Where Libelle Like :Libelle Order By Libelle",l=l.replace("IdEcran",b),l=l.replace("IdUser",_40._66()),l=l.replace("Identifiant",d);b=_99(null,1,"ETATS","SELECT",l);b=_97(b,1,0,"LIBELLE","%");var m=_1(b);b=null;_82("XMLA",
m,f,null,[e],!0);_36(a,!0);var k=new dhtmlXPopup({mode:"right"});e=k.attachGrid(350,320);e.startFastOperations();e.setIconsPath(_40._70());e.setImagePath(_40._65());e.setHeader("Valider",null,["text-align:center;color:red;font-size:14px;"]);e.attachHeader("#text_filter");e.setColTypes("ro");e.setColAlign("left");e.setColSorting("str");e.enableValidation(!0,!1);e.setInitWidths("*");e.enableDistributedParsing(!0,10,300);e.init();_37(e);e.csv.row=String.fromCharCode(3);
e.csv.cell=String.fromCharCode(2);e.enableCSVAutoID(!1);e.stopFastOperations();_36(a,!1);e.attachEvent("onHeaderClick",function(a,b){var f=e.getSelectedRowId();f&&(k.hide(),e.clearSelection(),_42(f,c,d))});e.attachEvent("onRowDblClicked",function(a){k.hide();e.clearSelection();_42(a,c,d)});e.attachEvent("onFilterEnd",function(b){if(15>=e.getRowsNum()){_36(a,!0);b=_99(null,1,"ETATS","SELECT",l);var c=h[0].trim();b=_97(b,1,0,"LIBELLE",""==c?"%":"%"+c+"%");b=_1(b);
_82("XMLA",b,f,null,[e],!1)}});e.attachEvent("onFilterStart",function(a,b){h=b;return!0});k.show(50,50,350,300);e.getFilterElement(0).focus();_40._11(!1);return k};
